### ISSUE TITLE
What does the +m option do?

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#1003]
- Category
    - [x] fzf binary

What does the `+m` option to fzf do? Can't seem to find it in the man page, but it's used in many examples.

**Comment by junegunn** [comment]
It's the opposite of `-m` (a.k.a. `--multi`), so it explicitly disables `--multi`. `--multi` is not enabled by default, but we do this because users may have it in their `$FZF_DEFAULT_OPTS`. Likewise, `+i` is the opposite of `-i`, `+s` is the opposite of `-s`. And you're right that `+m` is currently missing in the man page.

Another things that is not clearly stated is that most options have their `--no-*` counterpart. `--no-multi`, `--no-sort`, `--no-reverse`, `--no-height`, etc. I'll update the man page.
