### ISSUE TITLE
Add ability to set width of fields

### ISSUE THREAD

**Issue by carnager** [junegunn/fzf#1012]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

  
fzf allows to hide certain fields with the `with-nth` argument, which is a great thing. Sometimes you want to be able to see what is in fields, but the content is far too much to be usable, because it pushes other fields out of view. I suggest a way to set the width of fields to work around this issue. Something like `-width-n=1:50,2:30,3:50`

**Comment by junegunn** [comment]
Thanks for the suggestion, but I think this should be done using external scripts that are much more flexible and capable. You can write a script to preprocess the data before feeding it to fzf and use `--with-nth` of fzf to hide raw data.

```sh
# Original data
rawdata

# Script prettifies the raw data (maybe with some ANSI colors)
# and appends formatted output to each line
rawdata Raw Data

# Use --with-nth to hide the raw data in the finder
#   fzf --with-nth 2.. --ansi | awk '{print $1}'
Raw Data
```

**Comment by cskeeters** [comment]
I took this recommended approach and formatted the input data.  It works until i use a template for `--with-nth`.  Can the `s` flag for placeholder expressions help here?

```
echo 'A           ;b;c' | fzf -d ';' --with-nth '{1} {2}'
```

**Comment by junegunn** [comment]
@cskeeters Can you give an actual example? I'm wondering why you want to use `--with-nth` when you can pre-process and format the input.

**Comment by cskeeters** [comment]
I'm working on selecting unicode characters via FZF in Neovim.  I like to use `--with-nth` so that I can hide the field that will be accepted (unicode hex value in this case) if it's not important to see or filter on while in the UI.  I'm pre-processing [UnicodeData.txt](https://www.unicode.org/Public/UNIDATA/UnicodeData.txt) and I want to see the name with 80 spaces and then the rendered character.

I read the file in to Lua and output the unicode hex (for `--accept-nth 1`, a delimiter, the name formatted to 80 characters (`string.format("%-80s", name)`), a delimiter, and then a rendered character.  I don't want to see the delimiters when I'm filtering as it's just not as nice (though it does work), but I want to retain the padding I added so the rendered characters align, making it easier to find the character for which I am looking.  I want the name before the character because the search works a bit better (I think).  I didn't expect the spaces I added in pre-processing to go away when I switched from `--with-nth 2,3` to `--with-nth '{2} {3}'`.

Will you provide an example of the `s` flag that preserves the spacing as the man page suggests in the section for `--preview`.  I couldn't figure out the syntax.  Can this flag apply to templates for `--with-nth`?

**Comment by junegunn** [comment]
So removing trailing whitespaces is not always desirable. Hmm. But that's how the template works and the flags (`f`, `s`, `+`) don't work with the template. But I can make `s` flag work in the future versions.

Anyway, for now, I'd use a tab character as the delimiter.

If your input is relatively simple and doesn't have many columns, you can even use `--tabstop` to format the input.

```sh
echo -e "foo\tbar\tbaz" |
  fzf -d"\t" --with-nth ..2 --tabstop 80 --accept-nth 3
```

If you do need custom formatting:

```sh
printf '%-80s\t%-20s\t%s' foo bar baz |
  fzf -d"\t" --with-nth ..2 --tabstop 1 --accept-nth 3
```
