### ISSUE TITLE
Feature request: A way to insert a field without stripping whitespace

### ISSUE THREAD

**Issue by ZDNoFYVe** [junegunn/fzf#1028]
It would be nice if there was a way to disable the behavior described in issue #1024. How about adding a new flag for placeholder expressions? Something like `{w1}` or `{s1}`.

If you're not opposed to this feature, I could try to implement it myself.

**Comment by junegunn** [comment]
What would be the use case?

**Comment by ZDNoFYVe7iBFr804xAf1** [comment]
I use fzf in a few scripts that operate on files. I store file names in one of the fields in the input. File names can occasionally have leading or trailing spaces. I try to make sure my scripts don't break when handling files like that. It's not foolproof (because I still need to worry about the characters I use as delimiters), but having a feature like this would let me avoid some complexity.

**Comment by ZDNoFYVe** [comment]
Implemented in #1242.
