### ISSUE TITLE
Suggestion: accept the special search syntax chars as postfixs too

### ISSUE THREAD

**Issue by olejorgenb** [junegunn/fzf#1041]
> aword
    annoying matchaword
    ...
    aword is what I want

\*sees result\* .. gosh dang it, prefix-exact-search would've been much better, but I have to move the cursor back to specify it  :( (and forward again if want to add more terms)

    > aword^
    aword is what I want

I don't see any reason that recognizing the syntax postfix  also would be problematic, but I might have overlooked something

**Comment by junegunn** [comment]
> I have to move the cursor back to specify it

I don't think it's really necessary because fzf supports all relevant Emacs-style readline key bindings. You can just hit CTRL-A to move to the front, prepend `^`, then you can go back to the end by pressing CTRL-E if you want. Word-wise movements via ALT-B and ALT-F are also supported, and I use them every day both on my shell and on fzf.

> any reason that recognizing the syntax postfix also would be problematic

The change will confuse users who would expect `^` in the pattern to match literal `^`. It may not matter much in practice, but I'd rather not add more exceptions and keep it simple. Thanks for the suggestion anyway.

**Comment by kaddkaka** [comment]
I would also like this post-fix notation as mentioned in #2069 I often realize I have to make a word literal to filter my search enough. So my biggest usecase is probably doing `'` as a postfix modifier. With this I need to press 1 key instead of 2+1(+2) for the `ctrl-a`+`'`(+`ctrl-e`)

Perhaps the postfix notation can be opt-in via a switch or envvar?
