### ISSUE TITLE
fzf search is weirdly slow

### ISSUE THREAD

**Issue by YoungxHelsinki** [junegunn/fzf#1104]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

fzf is weirdly slow. Here's a benchmark video: [https://youtu.be/k1XYRAzkgME](https://youtu.be/k1XYRAzkgME)

Here's my environment:
MacOS 10.12.6
iTerm2 3.1.4
tmux 2.6
FZF 0.17.1

Here's my fzf conf in `.zshrc`:
```
# fzf + ag configuration
if _has fzf && _has ag; then
      #export FZF_DEFAULT_COMMAND='ag --hidden --nocolor --ignore .git -g ""'
      export FZF_DEFAULT_COMMAND='ag --nocolor --hidden -g ""'
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
          export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
            export FZF_DEFAULT_OPTS='
              --color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
                --color info:108,prompt:109,spinner:108,pointer:168,marker:168
                  '
fi
```

I think it would be nice if I could use fzf within Vim but with this speed it's not pleasant. :\
Any idea?
Thanks :)

**Comment by junegunn** [comment]
The issue here is not the performance of fzf. You're basically waiting for ag command to complete.

```sh
cd ~
time ag --nocolor --hidden -g "" | wc -l
```

If you're unhappy with it, you can try replacing it with ripgrep, but I don't think it'll make a big difference. If you frequently need to traverse the whole file system (I believe most users don't), you'll have to use a solution that maintains the index of the file system in the background, such as `locate`.

**Comment by YoungxHelsinki** [comment]
Ok. I forgot that I had 20 times more files than [this guy here](https://statico.github.io/vim3.html)
Thanks anyway :)
