### ISSUE TITLE
Option to return text that is currently typed in when pressing enter 

### ISSUE THREAD

**Issue by hakonhagland** [junegunn/fzf#1137]
- Category
    - [x] Feature
- OS
    - [x] Linux

I would like to use `fzf` as both a previewer of available items and as a tool to create a new item. For example, suppose I have some filenames (here these represents the available items), now I would like to create a new filename and I will use `fzf` as a tool to preview the existing items. The problem is that if I select an item from the list in `fzf` and modifies the text (still inside `fzf`) or I just type in a new name that does not yet exist, `fzf` will return nothing. (I would like to have an option of returning the text that is currently typed in when pressing enter inside `fzf`)

Also it would be nice to have an option to paste the currently highlighted/selected item from the list of candidates onto the text field inside `fzf`. In this way the user could modify the item (without having to retype the whole item) before accepting it.

**Comment by junegunn** [comment]
> I would like to have an option of returning the text that is currently typed in when pressing enter inside fzf

There's `--print-query` option. There's also `print-query` action you can bind to a key with `--bind` option. You might want to check out `man fzf` if you haven't already.

I'll think about your suggestion in the second paragraph, though some might find it confusing because in some corner cases the pasted line may contain characters that may conflict with the search syntax of fzf.

**Comment by hakonhagland** [comment]
Yes `print-query` works perfect. I totally missed that when reading the `fzf --help` output. However, it would be even better if we also could paste from the candidates list. Thanks for the quick reply!
