### ISSUE TITLE
Consistent color scheme by default

### ISSUE THREAD

**Issue by dtcyganok** [junegunn/fzf#1171]
Is it possible to implement using colors from palette of the terminal by default?

**Comment by junegunn** [comment]
You can force fzf to use default 16 ansi colors instead of its 256-color palette, by setting `--color 16`. See `man fzf` for details.

**Comment by dtcyganok** [comment]
I already did it that way) With `--color 16` this looks consistent.

Maybe by default use `16` instead `dark`?

**Comment by junegunn** [comment]
"dark" has been the default color scheme for more than 4 years so I would rather not surprise the old users by suddenly changing it. Also, fzf automatically chooses 16-color scheme on terminals that do not support 256 ANSI colors.

You may already know but you can define `$FZF_DEFAULT_OPTS` so that any set of options are globally applied.
