### ISSUE TITLE
Update terminal buffer title [gvim8/windows10]

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf#1174]
- Category
    - [x] fzf binary
    - [x] Vim
- OS
    - [x] Windows
- Shell
    - [x] cmd

Follow this comment in PR https://github.com/junegunn/fzf/pull/1173#issuecomment-349317753.  
_fzf 0.17.1, lastest fzf.vim, gvim8 1-1358, windows 10, +terminal_  

Issue: When invoke fzf, terminal buffer has default name: `!cmd.exe`, It should be changed to something more related to one that called it, for example of title: `fzf` when invoked by command `:FZF`  
`Commits` when invoked by command `:Commits` ..etc.

@janlazo : Appreciate if you can have a look or maybe a PR.

**Comment by junegunn** [comment]
Changing the name of a buffer is discouraged as it has unwanted side-effects, so we don't do it. A better approach would be to configure buffer-local `&statusline`, or [simply to hide it](https://github.com/junegunn/fzf.vim#hide-statusline).

`&statusline` is automatically set if you use [fzf.vim](https://github.com/junegunn/fzf.vim#status-line-of-terminal-buffer). We used to do that only for Neovim (because Vim didn't have terminal buffer until recently), but I just [updated the code](https://github.com/junegunn/fzf.vim/commit/11b7fb91e152258c59b0bb0526c3fb04469cf38c) to activate also on Vim 8. So update fzf.vim and see if it works for you.

> Commits when invoked by command :Commits ..etc.

That's an idea we can consider. Most commands in fzf.vim already set `--prompt` to that, so I don't think it's urgent. But I'll think about it.

By the way, please upgrade fzf to 0.17.3 which fixed "double-enter" problem on Windows Vim, though it won't make a difference in this particular case.

**Comment by tuyenpm9** [comment]
It doesn't seem related to statusline, please refer to this [**video**](https://drive.google.com/file/d/11asjlSx5Ci3c50QgekaK9mS_UMM1Qg67/view?usp=sharing) for demonstration.  
So when invoke fzf's commands, the title of gvim shows that it has name `!cmd.exe [running]`

**Comment by janlazo** [comment]
The problem with setting `term_name` is it must be a unique name because Vim won't append a unique label like `(1)` on the buffer name. You can observe this if you run `:terminal` consecutively and check the buffer names with `:ls`. Vim will append some label to the buffer name if `term_name` is not set.

There is a `term_marker` used in Neovim to track the terminal buffer so that could be reused for the `term_name` in Vim but it is not unique enough for a buffer name if calling `FZF` consecutively.
