### ISSUE TITLE
wiki code review request

### ISSUE THREAD

**Issue by magnetophon** [junegunn/fzf#1175]
I added some code to the wiki that adds a preview to some of the [git commands](https://github.com/junegunn/fzf/wiki/Examples#git):
- fco_preview
- fcoc_preview
- fshow_preview

These work nicely for me, and might warrant replacing the non-preview versions in the wiki, but since I'm not very well versed in shell scripting, I'd like to request a code-review for them.

**Comment by junegunn** [comment]
Thanks. I just tried one of your functions and I realized you didn't set `--ansi` option for fzf so the ANSI escape sequences are shown in the list. Do you have it in your `FZF_DEFAULT_OPTS`? I don't recommend doing so, since it adds some overhead to fzf parser and makes it slower even when you don't have ANSI colors in the input.

**Comment by magnetophon** [comment]
Thank *you*!
Yes, I have ``--ansi`` in my ``FZF_DEFAULT_OPTS``.
I'll change that in the wiki.

**Comment by joaqo** [comment]
Hey @magnetophon thanks for the great scripts. I've been trying to use them but couldn't get them to run. I am currently trying to use `fshow_preview` which seems insanely useful, but had the following problems:
- Initially I got a `-bash: local: can only be used in a function` message, which was caused by 
```
local _gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
local _viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always % | diff-so-fancy'"
```
I moved them into `fshow_preview` and that error dissapeared.
- After that I got the error `unknown option: {}` which I think is caused by
```
local _gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
```
but I dont really know how to solve it.


Do you have any idea of what I could be doing wrong? Thanks!

**Comment by magnetophon** [comment]
@joaqo I'm sorry to say I can't help you there; these are all googled together...
[This](https://github.com/magnetophon/.dot/blob/master/zprezto/.zshrc#L239) is what I'm using atm, if that helps.

**Comment by joaqo** [comment]
I ended up solving it, pasting the code here if anybody else is interested:

```bash
alias glNoGraph='git log --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" "$@"'
_gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
_viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always %'"
# _viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always % | diff-so-fancy'"

# fcheckout - checkout git commit with previews
fcoc_preview() {
  local commit
  commit=$( glNoGraph |
    fzf --no-sort --reverse --tiebreak=index --no-multi \
        --ansi --preview="$_viewGitLogLine" ) &&
  git checkout $(echo "$commit" | sed "s/ .*//")
}

# fshow - git commit browser with previews
fshow() {
    glNoGraph |
        fzf --no-sort --reverse --tiebreak=index --no-multi \
            --ansi --preview="$_viewGitLogLine" \
                --header "enter to view, alt-y to copy hash" \
                --bind "enter:execute:$_viewGitLogLine   | less -R" \
                --bind "alt-y:execute:$_gitLogLineToHash | xclip"
}
###################################### O ###############################################
```

**Comment by magnetophon** [comment]
@joaqo Cool, that seems to work on zsh as well.
Thanks for solving it, I\ll update the wiki.
