### ISSUE TITLE
Feature request: let tab key move upwards in the list

### ISSUE THREAD

**Issue by QiangF** [junegunn/fzf#1186]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

**Comment by QiangF** [comment]
The keybinding can be changed with --bind, but it would be nice to make this as default.

**Comment by junegunn** [comment]
I suppose by left-tab you mean shift-tab. We bind shift-tab to "toggle-up" action by default. It's used when `--multi` is set.

**Comment by QiangF** [comment]
Since the list grows in the up direction, I think the default way should be like this:

    fzf --cycle --bind 'tab:toggle-up,btab:toggle-down'

**Comment by junegunn** [comment]
fzf changes its layout depending on `--reverse`, so we provide `toggle-in` and `toggle-out` as well.

https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0112

However, I don't use them as I find them more confusing rather than helpful. They are many users who have used fzf for more than 4 years by now, and are perfectly comfortable with shift-tab going up, so I don't want to change the default and surprise those users (including myself).
