### ISSUE TITLE
Generation of $HOME/.fzf.bash (home directory resolution)

### ISSUE THREAD

**Issue by joaospinto** [junegunn/fzf#1209]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

Every time I update fzf, I seem to have to edit `$HOME/.fzf.bash` to fix the directories from `/home/myuser/...` to `$HOME/...`, due to the way home folders are configured at work (they're network folders). I would presume other people may have similar setups, especially in corporate environments, so consider just keeping the `$HOME` variable in the `.fzf.bash` file instead of explicitly (and in my case wrongly) resolving it.

**Comment by junegunn** [comment]
I see your point, but fzf can be installed outside of one's home directory.

```sh
git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/fzf
/tmp/fzf/install
```

If you read the install script, you'll notice that it does not refer to `$HOME`, but to the directory where fzf is cloned as `$fzf_base`.

Since `~/.fzf.bash` is pretty short and simple, I suggest that you put the lines in directly in your .bashrc, and from that point run install script with `--bin` option so that it only downloads the latest binary.

```sh
cd ~/.fzf && git pull && ./install --bin
```
