### ISSUE TITLE
Select candidate by typing but do not filter display

### ISSUE THREAD

**Issue by jacobdufault** [junegunn/fzf#1226]
For certain usages of fzf, like when there is a preview window open, it would be very handy if typing only selected a candidate but did not filter candidates, as the candidate list may provide valuable context (ie, if filtering a tree).

For example, if using fzf to show git diff then you can type a filename you want to view, but still use arrow keys to navigate nearby files.

As another example, here are git branches as shown in fzf:

![image](https://user-images.githubusercontent.com/356714/36694831-632e0e44-1af4-11e8-9163-b05f8a88a10c.png)

Here is what happens when filtering:

![image](https://user-images.githubusercontent.com/356714/36694869-76ceb9ee-1af4-11e8-9f1b-496b7d2a64b7.png)

By filtering valuable context information is lost - but filtering is a very convenient way to quickly select a candidate.

**Comment by junegunn** [comment]
Yeah, I also thought about this feature when I tried to use fzf with `tree` command.

```sh
tree | fzf --reverse --no-sort
```

This was unusable, as in your case, it's not possible to see the full path after any filtering. A slightly better way is to make tree command print the full path of each entry.

```sh
tree -f | fzf --reverse --no-sort
```

It's still not ideal, as we end up with a fractured tree structure.

Unfortunately, implementing the suggested idea on fzf requires significant rework of the internal structures. Also, it complicates the code for the UI (think about scrolling, cursor movements, etc) and it might cause some performance issues with large input lists. So I decided that it's worth the effort, considering that the use case is quite niche. Maybe there are better tools out there that are specifically designed for such use cases.

**Comment by nkh** [comment]
@jacobdufault @junegunn it would be a useful feature indeed but I understand the complication.

Anything with a structure and a specific way to fold is going to look bad when split in pieces.

For the tree structure, as mentioned by @junegunn, there's broot but IMHO it's completely broken and  not very useful  but the idea is good.

So what can we do and what are exactly the requirements and what's needed to implement something which may not be fantastic but still usable? can we hack something together?

requirements
- input search
- search (potentially fuzzy) for items
- display search results with "enough" context to be usable, but not full path for each entry that's noisy
- navigate in the searches
- get as a result the full path for the selected results

the first thing I did, because I'd like to add it in my file manager, was to use grep, grep can give us some context with -A/B/C, it's unfortunately not enough context but there's a solution to that

grep doesn't do fuzzy and I didn't find a way to get results from fzf without running the UI; there's hope in ugrep, tre-agrep, fstrcmp, and may be even fzf

for input, display, and navigation, I believe fzf can be used and the search as well as the generation of the text to be displayed can be left to an outside script(s) that's already by binding +disable-search+reload as explained by the example in https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration

the scripts needs to:

- accept the search string, do a (possibly fuzzy) search and add enough context
- take the selected entries and transform them to a real result, IE a full path for tree output

and example output of a search in a tree is
`
88-│   │   ├── reserved.def
89-│   │   ├── return.def
90-│   │   ├── setattr.def
91-│   │   ├── set.def
92:│   │   ├── shift.def
93-│   │   ├── shopt.def
--
226-│   │   │   ├── substr
227-│   │   │   ├── substr2
228-│   │   │   ├── whatis
229-│   │   │   ├── whence
230:│   │   │   └── which
231-│   │   ├── INDEX.html
...
`

I left the line number because it's doing half the job, the line numbers are unique which means that we can look it up to get the selection full path, if necessary we can "hide"  them with some ANSI codes

we're stil missing context; we can see that grep/rg, ... separate the entries with a '--' which means that we can search for the different entries, before they are displayed by fzf, and transform it from

`--
226-│   │   │   ├── substr
227-│   │   │   ├── substr2
228-│   │   │   ├── whatis
229-│   │   │   ├── whence
230:│   │   │   └── which
231-│   │   ├── INDEX.html
`
to

`--
/home/nadim/nadim/devel/repositories/bash/examples/functions/
226-│   │   │   ├── substr
227-│   │   │   ├── substr2
228-│   │   │   ├── whatis
229-│   │   │   ├── whence
230:│   │   │   └── which
231-│   │   ├── INDEX.html
`

that gives an "honest" context, and -A/B/C can be changed to the user's liking

I'm working on implementing the details and one thing that needs to be taken care of is speed, to add the "honest context" a lookup table needs to be generated, for small tree it's very fast but an example I have takes around 0.3 sec for 17000 entries, 95% of the time spend in 'tree'; there may be faster tree programs one can use. That needs to be done asynchronously and even then fzf has already started to display entries and accept input. The good thing is that it needs to be done once only during the session.

If you guy are interested leave a comment and I'll put my proof of concept somewhere.

**Comment by nkh** [comment]
Here's an implementation https://github.com/nkh/fzf_scripts/blob/main/fzf_tree
