### ISSUE TITLE
Multiple search terms: prefer "in-order" matches over "out-of-order" ones?

### ISSUE THREAD

**Issue by ivanbrennan** [junegunn/fzf#1262]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

When querying with multiple search terms, is it possible to give a higher score to lines whose matches occur in-order than lines where the matches are out-of-order? For example, when I run:
``` sh
cat <<EOF | fzf --exact
ice cube
cube ice
EOF
```
and query for `cube ice`, the initial selection is `ice cube`, even though `cube ice` matches the search terms in the same order they were queried.

**Comment by junegunn** [comment]
No, but if you don't use `--exact`, you can just type in `icu` or `cui`, etc.

**Comment by unphased** [comment]
I'll try to clarify what @junegunn is saying, @ivanbrennan  

The space separated terms are treated as ANDs (afaict)

If you use fuzzy (non --exact) search it will always keep track of relative order. simply dont place a space in there.. 

my use case is i dump annotated code file content into fzf to use it to filter millions of lines for me interactively... So, say im looking for "twilio" inside go code, instead of attempting to search for `\.go twilio` which will yield me results that contain lines containing twilio followed by go, I would want to have a fuzzy search like `.go:::twilio` (colon is always there to separate file from line no from line content). This then has a long tail of stuff so if i want to filter them out i would adjust and add an exact item so my query might look like `.go::: 'twilio`

i think the semantics are already clear enough and powerful due to the AND composition that theres no need to add order dependent prioritization of the terms.
