### ISSUE TITLE
Re-Indexing after every reboot

### ISSUE THREAD

**Issue by jagsus** [junegunn/fzf#1284]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hey, I'm not exactly sure if this is an Issue or if it's working as intended, but on every system startup fzf does a complete re-index (when pressing ctrl+T in terminal). This takes quite long (ca. 5min).
There are no network shares or similar mounted, just local files.

**Comment by junegunn** [comment]
fzf is just a Unix filter and the implementation of CTRL-T binding does not cache the result, but always starts a new "find" process by default. Implementing a caching scheme is beyond the scope of this project. If you can come up with such a command, you can specify it in your `$FZF_CTRL_T_COMMAND`, so the binding uses it instead of the default command.

https://github.com/junegunn/fzf#key-bindings-for-command-line
