### ISSUE TITLE
Quote filenames with spaces or special characters

### ISSUE THREAD

**Issue by HaleTom** [junegunn/fzf#1300]
- Category
    - [x ] fzf binary
- OS
    - [x ] Linux
- Shell
    - [x ] bash

```
$ /bin/ls -l
total 4,096
-rw-r--r-- 1 ravi ravi 4 May 23 10:43 'file with spaces'
$ cat $(fzf)
cat: file: No such file or directory
cat: with: No such file or directory
cat: spaces: No such file or directory
$
```

Perhaps do something like:

```
$ printf "%q\n" file*
file\ with\ spaces
$
```

I'd also suggest that this output be used when displaying filenames.

Eg:
```
$ /bin/ls -l
total 12
-rw-r--r-- 1 ravi ravi 5 May 23 10:56 'bad'$'\b\b\b''pretending file'
-rw-r--r-- 1 ravi ravi 4 May 23 10:43 'file with spaces'
-rw-r--r-- 1 ravi ravi 4 May 23 10:42 'two'$'\n''lines'
```
In this directory, `fzf` incorrectly shows:
```
  bad???pretending file
  file with spaces
  nes
> two
  4/4
>
```

Note:
1. The count should not be 4, but rather 3
1. The characters "li" are missing from the filename with the '\n' character
1. The backspace chars are replaced by '?', meaning they can't be differentiated from literal '?' characters

For security reasons (eg accidentally operating on "file" should "file name" exist), I strongly recommend that quoting filenames be the default.

**Comment by junegunn** [comment]
Thanks for raising the issues. But fzf is a general-purpose text filter rather than a file finder, so it shouldn't transform the output by default, the same way we don't expect `grep` to escape or quote its output stream. If needed, post-processing should be done by another program or script in the command pipeline.

```sh
ls -l | fzf | post-process-for-safety.sh
```

fzf uses a new line character as the default record delimiter, if you need to process input with multi-line entries, you might want to take a look at `--read0` or `--print0` options.

```sh
find . -print0 | fzf --read0 --print0
```

Not sure what's going on with `li` in your case. It works for me as expected.

```sh
# "two" and "lines"
echo two$'\n'lines | fzf

# "two lines"
echo two$'\n'lines | fzf --read0

# Same as the first command
(echo two; echo lines) | fzf
```

**Comment by HaleTom** [comment]
Thanks for your time on this and explaining the use case for `fzf`. 

I'm not sure what was going on with my example... probably an interaction with `ls` and quoting.
