### ISSUE TITLE
Option to cycle between literal, reg-exp, and fuzzy matching when selecting

### ISSUE THREAD

**Issue by jeetsukumaran** [junegunn/fzf#1305]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

(Suggestion) Option to cycle between literal, reg-exp, and fuzzy matching when selecting.

I love fzf. And the "fuzzy" is, of course, is what makes it great. But sometimes it would be nice to have a more exact matching algorithm applied on the fly or on demand. E.g., when working with a project with lots of similar files, typing a few letters may get it filtered down to a some dozen (or hundred), but then after that it is often difficult to thin it out more due to the similarity of filenames. Being able to switch to literal of reg-exp matching would help a lot in cases like this.

The switch/cycling/toggling can be triggered by a Ctrl key (e.g., "CTRL-R") so as to disambiguate from standard filter/fuzzy search text.

Thank you for fzf!

**Comment by junegunn** [comment]
Hi, there is no plan for supporting mode switching, or regex mode. But you can already mix exact search terms and fuzzy terms by prefixing each term with `'` character. I use it a lot.

```
fzzy 'exact
```

See:
- https://github.com/junegunn/fzf#search-syntax
- https://github.com/junegunn/fzf/issues/1265#issuecomment-382248569

**Comment by jeetsukumaran** [comment]
Oh, [this](https://github.com/junegunn/fzf#search-syntax) is _excellent_, and does exactly what is needed. Thanks!

**Comment by hcgatewood** [comment]
Hey @junegunn, first off just wanted to say thank you so much for the amazing project, I use it every day and it's saved me countless hours

I wanted to add a quick note in favor of potentially adding a `toggle-exact` action to fzf:

1. Flow state: being able to e.g. `ctrl-r` to quickly, immediately, and rapidly switch back and forth between the two views would be super helpful when I'm doing an "I'm not quite sure what I'm looking for yet" type of investigation -- the few seconds saved per switch sums up to a substantial amount of time (especially considering loss of flow state due to the effort to context switch) over the course of an investigation
2. Approachability: I also develop fzf wrappers for my team and others. The users are generally less familiar with fzf search syntax (and often don't even realize they're using fzf at all). Having a simple `ctrl-r: toggle exact search` header makes it infinitely more approachable for them to understand what to do, since there's generally no way they will otherwise go read the docs

Thanks so much again for the awesome project and appreciate your thoughts!
