### ISSUE TITLE
[FR] Add suggestion for same as the query

### ISSUE THREAD

**Issue by acomagu** [junegunn/fzf#1307]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I love fzf. :heart:

I want to use fzf as kind of prompt, so I want it to show the query without changes as one of suggestion(maybe at last line).

Now fzf has ability to print the final query but sometimes the user can't express what they select is the one of options(e.g. `abc`) or exact they typed(e.g. `a`).

Usage example:

```
git branch | awk '{ print $NF }' | fzf | xargs git diff
```

We can choose from branches now, and I hope we can also send `HEAD^^` by typing the whole(and I want to show preview if it's implemented. This is also motivation for this feature because now previewing is disabled when no matching).

Thanks.

**Comment by junegunn** [comment]
> sometimes the user can't express what they select is the one of options(e.g. abc) or exact they typed(e.g. a).

In that case, I would use `--expect` option so I can explicitly express different intentions.

```sh
fzf --expect=ctrl-x,ctrl-y --print-query
```

> This is also motivation for this feature because now previewing is disabled when no matching

Starting an arbitrary command with a query string as an argument usually doesn't makes sense since fzf is a fuzzy finder that allows inaccurate search terms and has [its own search syntax](https://github.com/junegunn/fzf#search-syntax). I mean there's no guarantee at all that a query string from fzf corresponds to a valid entity. 

```sh
# Can we start a preview command with "mstr !monster"?
git branch | fzf -q 'mstr !monster'
```

But since fzf already supports `{q}` in command template, I can consider making fzf still render preview window if any of the placeholder expressions in the template evaluates to a non-empty string. Making sure that `{q}` can be a valid command argument will be still up to the users.

```sh
fzf --preview '[ -f {} ] && cat {} || echo {q}'
```

**Comment by junegunn** [comment]
Check out the example in 2c26f02f5ce263820a339595517152b70ed63b80. It's not exactly what you suggested, but I think it should help.
