### ISSUE TITLE
Make it possible to specify history options in CTRL-R?

### ISSUE THREAD

**Issue by kbd** [junegunn/fzf#1308]
- Category
    - [x] Key bindings
- Shell
    - [x] zsh

I was hoping `FZF_CTRL_R_OPTS` would allow me to specify options to send to `history` but after reading `fzf_history_widget` in [key-bindings.zsh](https://github.com/junegunn/fzf/blob/2cd0d4a9f7a0a0a86c1ee70da9fb970ec18eac50/shell/key-bindings.zsh#L69) it looks like that's not possible. I'd like to be able to configure history output to show timestamps, like `history -i`.

**Comment by junegunn** [comment]
The problem is that if we change the format of the input, the subsequent processing of the selected line should be changed accordingly, so we can't just allow users to use any command via `FZF_CTRL_R_COMMAND`, because it may not work. For example, CTRL-R implementation for zsh expects the selected line to start with a number so it can restore the old command with `zle vi-fetch-history`, but if the line starts with a timestamp, for example, `vi-fetch-history` will fail. So it's tricky to make the command configurable while not breaking the feature.

I suggest that you just override the implementation in your shell configuration file. It's just a few lines of code.

**Comment by kbd** [comment]
> For example, CTRL-R implementation for zsh expects the selected line to start with a number...

If you do `history -i` the format is "`[number] [timestamp] [historyline]`", so it'll still start with a number.

I figured you could do something like:

```bash
selected=( $(fc -rl $FZF_HISTORY_OPTS 1 |
```

Thanks anyway for considering! And thanks for fzf!

**Comment by kbd** [comment]
> I suggest that you just override the implementation in your shell configuration file. It's just a few lines of code.

In case anyone else finds this issue and is interested, here's what I wound up doing. In my script that installs all my stuff, I patch `key-bindings.zsh` like so:

```
perl -pi -e 's/fc -rl 1/fc -rli 1/' "$(brew --prefix fzf)/shell/key-bindings.zsh"
```

**Comment by vimiPonyai** [comment]
@kbd thanks your tips and thanks for fzf again.
