### ISSUE TITLE
LINES/COLUMNS not set properly

### ISSUE THREAD

**Issue by MaienM** [junegunn/fzf#1314]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

The values of `$LINES` and `$COLUMNS` in the environment that the preview window runs in is identical to that of the outer shell, instead of the actual size of the preview window.

```
> uname -a
Linux MICHON-SPECTRE 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
> zsh --version
zsh 5.5.1 (x86_64-unknown-linux-gnu)
> fzf --version
0.17.4 (f0fe79d)
> echo $TERM
(when not in tmux) xterm-256color
(when in tmux) screen-256color
> echo ${COLUMNS}x${LINES}
271x64
> echo | fzf --preview='echo ${COLUMNS}x${LINES}'
(in the preview) 271x64
```

**Comment by junegunn** [comment]
Works for me as expected. Justed tested on macOS and Arch Linux (`make docker`).

**Comment by MaienM** [comment]
After some more testing it seems this is caused by something in my profile/rc files. The problem vanishes when running without those on the same machine. I'll update if I figure out what is causing this.

**Comment by trevorah** [comment]
@MaienM did you have any luck?

I'm having the same issue but on Mac OS X with both bash and zsh.

Even running straight with `/bin/bash --noprofile --norc` so even my own $PATH is reset, im still getting the outer shell dimensions in the preview.
```console
-bash-3.2$ echo ${COLUMNS}x${LINES}
80x24
-bash-3.2$ echo | /usr/local/bin/fzf --preview='echo ${COLUMNS}x${LINES}' --preview-window up
(in the preview) 80x24
```

Could it be something to do with $COLUMNS and $LINES not being passed to non-interactive scripts?
```console
-bash-3.2$ cat a.sh 
#!/bin/bash
echo "Lines: " $LINES
echo "Columns: " $COLUMNS

-bash-3.2$ ./a.sh 
Lines: 
Columns: 
```

**Comment by trevorah** [comment]
Interestingly, if I tweak the names of the environment variables like so:
```diff
diff --git a/src/terminal.go b/src/terminal.go
index cae349d..539b6a1 100644
--- a/src/terminal.go
+++ b/src/terminal.go
@@ -1477,8 +1477,8 @@ func (t *Terminal) Loop() {
                                        cmd := util.ExecCommand(command, true)
                                        if t.pwindow != nil {
                                                env := os.Environ()
-                                               env = append(env, fmt.Sprintf("LINES=%d", t.pwindow.Height()))
-                                               env = append(env, fmt.Sprintf("COLUMNS=%d", t.pwindow.Width()))
+                                               env = append(env, fmt.Sprintf("TEST_LINES=%d", t.pwindow.Height()))
+                                               env = append(env, fmt.Sprintf("TEST_COLUMNS=%d", t.pwindow.Width()))
                                                cmd.Env = env
                                        }
                                        var out bytes.Buffer
```

Then the preview is correct!

```console
-bash-3.2$ echo | target/fzf-darwin_amd64 --preview='echo ${TEST_COLUMNS}x${TEST_LINES}'
(in the preview) 36x22
```

**Comment by ALPHA-60** [comment]
I believe I was able to reproduce this issue when I set zsh as login shell in Dockerfile. This is consistent with the behaviour I've seen on my machine - if the login shell is zsh, it seems to override COLUMNS in children processes.

I had to change the Dockerfile a bit so that it can run tests. Most of the changes to Dockerfile are not relevant (changing the base image, generating locales and removing deprecated gem arguments). The `chsh` line is crucial.

```diff
diff --git a/Dockerfile b/Dockerfile
index d71aa0b..de87404 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
-FROM archlinux/base:latest
+FROM base/archlinux:latest
 RUN pacman -Sy && pacman --noconfirm -S awk git tmux zsh fish ruby procps go make
-RUN gem install --no-ri --no-rdoc minitest
+RUN gem install minitest
 RUN echo '. /usr/share/bash-completion/completions/git' >> ~/.bashrc
 RUN echo '. ~/.bashrc' >> ~/.bash_profile
 
@@ -8,4 +8,8 @@ RUN echo '. ~/.bashrc' >> ~/.bash_profile
 RUN rm -f /etc/bash.bashrc
 COPY . /fzf
 RUN cd /fzf && make install && ./install --all
-CMD tmux new 'set -o pipefail; ruby /fzf/test/test_go.rb | tee out && touch ok' && cat out && [ -e ok ]
+RUN echo LANG=en_US.UTF-8 >> /etc/locale.conf
+RUN echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
+RUN locale-gen
+RUN chsh -s /usr/bin/zsh
+CMD export LANG=en_US.UTF-8 && tmux new 'set -o pipefail; ruby /fzf/test/test_go.rb | tee out && touch ok' && cat out && [ -e ok ]
```

If the `chsh` line is commented out, the tests pass. If the login shell is changed to zsh, the test output is:

```
Finished in 105.977051s, 1.1040 runs/s, 1.1229 assertions/s.

  1) Error:
TestGoFZF#test_preview:
RuntimeError: timeout
    /fzf/test/test_go.rb:40:in `wait'
    /fzf/test/test_go.rb:133:in `until'
    /fzf/test/test_go.rb:1366:in `test_preview'

  2) Error:
TestGoFZF#test_preview_flags:
RuntimeError: timeout
    /fzf/test/test_go.rb:40:in `wait'
    /fzf/test/test_go.rb:133:in `until'
    /fzf/test/test_go.rb:1413:in `test_preview_flags'

  3) Error:
TestGoFZF#test_preview_hidden:
RuntimeError: timeout
    /fzf/test/test_go.rb:40:in `wait'
    /fzf/test/test_go.rb:133:in `until'
    /fzf/test/test_go.rb:1377:in `test_preview_hidden'

  4) Failure:
TestGoFZF#test_execute [/fzf/test/test_go.rb:901]:
--- expected
+++ actual
@@ -1 +1 @@
-["[foo'bar]", "[foo'bar]", "/foo\"barfoo\"bar/", "/foo\"barfoo\"bar/", "/foo$barfoo$barfoo$bar/"]
+["/foo\"barfoo\"bar/", "/foo\"barfoo\"bar/", "/foo$barfoo$barfoo$bar/"]


117 runs, 119 assertions, 1 failures, 3 errors, 0 skips
```

If this confirms the issue, may I suggest that a new pair of variables is added to the preview process environment: `FZF_COLUMNS` and `FZF_LINES`? Old variables can be kept for backwards compatibility, and new ones won't clash with special variables under zsh.

**Comment by junegunn** [comment]
Hmm, okay, looks like zsh does not allow overriding LINES or COLUMNS unlike bash.

```sh
> COLUMNS=100 bash -c 'echo $COLUMNS'
100
> COLUMNS=100 zsh -c 'echo $COLUMNS'
272
```

A (very unsatisfactory) workaround would be to set `SHELL` to `bash` when running fzf like so:

```sh
alias fzf='SHELL=bash fzf'
fzf --preview 'echo $LINES/$COLUMNS'
```

> If this confirms the issue, may I suggest that a new pair of variables is added to the preview process environment: `FZF_COLUMNS` and `FZF_LINES`? Old variables can be kept for backwards compatibility, and new ones won't clash with special variables under zsh.

This makes the most sense to me. I can't think of a better way.

**Comment by trevorah** [comment]
I'd suggest executing the `--preview` string with `sh` rather than `$SHELL`. This way you have consistent behaviour. If someone posts an example like `fzf --preview 'bat {}'`, you know its not going to subtly break on different people's machines. If someone *really* wants to run a zsh command in `--preview`, then they can run `fzf --preview 'zsh -c "my zshell command"'`.

Exporting `FZF_COLUMNS` and `FZF_LINES` isn't obvious and will catch a lot of people out.

**Comment by junegunn** [comment]
> I'd suggest executing the `--preview` string with `sh` rather than `$SHELL`

Though I do not disagree with your point, breaking backward compatibility (#481) after three years is the last thing I want to do. As @ALPHA-60 suggested, we are going to keep the old variable overrides to minimize the surprises.

However, it would be much better if there's a way we can override LINES and COLUMNS in zsh (and fish), so that we don't have to introduce FZF_LINES and FZF_COLUMNS.

**Comment by trevorah** [comment]
> breaking backward compatibility (#481) after three years is the last thing I want to do

Fair point. It's a tricky one, but I guess if someone is using `--preview`, then they might be setting an alias already, so setting `$SHELL` wouldn't be too bad.
