### ISSUE TITLE
FR: new action execute-print()

### ISSUE THREAD

**Issue by cpriest** [junegunn/fzf#1343]
- [X] Etc.
    - [X] Linux
    - [X] zsh

Describe your problem or suggestion from here ...

Adding a new action execute-print which would let you take the input, execute it and take the output of the execute and exit as the result of fzf (like accept).

Example:
`execute-print(realpath {} | sed 's/^/cd ')` 
This would take the first selection, run realpath on in, prepend cd on results of realpath and return that as the output of fzf.

Perhaps an `exec-silent-print()` would make sense along with the above.

Thanks!

**Comment by junegunn** [comment]
Hi,

This can be handled by the script that invokes fzf like so:

```sh
realpath "$(fzf)" | sed 's/^/cd /'
```

If you're trying to assign a special key to the action, you can use `--expect` option.

```sh
#!/usr/bin/env bash

readarray -t lines < <(fzf --expect alt-c,alt-d)
[[ ${#lines[@]} -lt 2 ]] && exit 1
key=${lines[0]}
item=${lines[1]}
echo "$key pressed on $item"
```

Obviously it's longer than a single line of the suggested option, but it's much more flexible, and fzf tries to follow Unix philosophy whenever possible. `execute` action is supported only because it's not otherwise possible.

**Comment by cpriest** [comment]
Makes sense, wasn't thinking outside of 'fzf' at the time.  Great program by the way, love it!
