### ISSUE TITLE
`select-all` selects all matches, whereas `deselect-all` deselects everything

### ISSUE THREAD

**Issue by cs** [junegunn/fzf#1364]
There appears to be a discrepancy between `select-all` and `deselect-all`. The former, selects all matches, whereas the latter deselects literally everything (i.e. all selections including the ones that are not matching the current search string). This is confusing. I would have expected `deselect-all` to be the reverse of `select-all`.

One possibility to make this clearer would be add two more actions:
* `select-all` - select everything regardless of current matches. This is a new action.
* `deselect-all` - deselect everything regardless of current matches. No changes here. This is already implemented.
* `select-all-matches` - select all matches (leaving all other selections alone). This is the current behavior of `select-all`.
* `deselect-all-matches` - deselect all matches (leaving all other selections alone). This is a new action.

**Comment by ahal** [comment]
Note that `toggle-all` follows the same behaviour as `select-all`, so `deselect-all` is the odd one out here. This also means that `toggle-all` can be used as a workaround if `deselect-all-matches` behaviour is desired.

Rather than changing names, would it be possible to change the behaviour of `deselect-all`? Waiting for the next major release of course. This would only break backwards compatibility if a query is entered, makes `deselect-all` consistent with `select-all`/`toggle-all` and seems to be what users expect to happen.

**Comment by junegunn** [comment]
I decided to make `deselect-all` consistent with the rest as you guys suggested, even if that can be seen as broken backward compatibility. But let's just say that we've finally fixed a long-standing bug.
