### ISSUE TITLE
Feature request: A toggleable help window with custom text

### ISSUE THREAD

**Issue by jdevera** [junegunn/fzf#1382]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I use fzf for many tools and after a while I forget some of my bindings. It'd be great if I could always define something like C-h to toggle a preview-like window with some predefined text that I can use as help.

**Comment by junegunn** [comment]
You can set up header section with `--header` or `--header-lines` for that purpose. See how I use it for CTRL-R binding.

```sh
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview' --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' --header 'Press CTRL-Y to copy command into clipboard' --border"
```

Header section is always visible, and for that to be toggleable, we need to add a few more options. I'd like to avoid that as the use case seems niche and I don't think I'm going to need it.

Since you can already toggle preview window, I suggest that you print out the message on it.

```sh
fzf --preview 'man -P cat fzf' --preview-window top:hidden --bind 'ctrl-h:toggle-preview'
```

**Comment by jdevera** [comment]
I am already using the preview window, but I did not know about the --header option and it is good enough for my use, the messages I need to show are short enough that it is okay to keep visible all the time.

Thanks!
