### ISSUE TITLE
Preview commands are not cancelled when changing line

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#1383]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

As an example:

``` sh
    printf '%s\n' 1 0.2 3 0.1 5 | fzf --preview='sleep {}; echo {}'
```

If you change lines while a preview command is running, you still have to wait for all previous previews to finish running before the selected line will show.

This becomes a bigger problem with potentially expensive or slow preview commands.

**Comment by junegunn** [comment]
While I think #1384 should be fixed, this was intentional. I probably should have explicitly mentioned that  preview process should finish quickly.

- Selection can move pretty quickly, especially when you use mouse wheel. If we immediately kill the running preview process on every movement, we'll end up starting and killing numerous child processes in a very short interval, and I'm concerned that it can have negative impact on the system.
- I have noticed that not cancelling immeditely provides better user experience. Currently, if you hold down CTRL-N/P or cursor key, with a relatively slow preview command, you'll notice preview window keeps updating. However, if we cancel the running process immediately, not a single command will finish, and the preview window will not update until you stop moving the cursor.

> you still have to wait for all previous previews to finish running before the selected line will show.

Technically, not all, but only the last one. Preview requests are not queued. Here is a pseudo-code of how it works.

```
preview-thread {
  loop {
    poll (last-request) {
      runs the command synchronously and updates the window
    }
  }
}

ui-thread {
  on-move {
    last-request <- preview
  }
}
```

A better approach would be to set a timeout (e.g. 500ms) before killing the running process. I'll experiment with the idea later.

**Comment by junegunn** [comment]
Fix pushed to master. Let me know if you still have the issue.

**Comment by dimo414** [comment]
Just wanted to add that #2215 has really improved the UX of slow previews, so the `sleep` example in the original report "feels" much better now.
