### ISSUE TITLE
Is it possible to hide prompt ?

### ISSUE THREAD

**Issue by sigzegv** [junegunn/fzf#1396]
Has subject says, I would like to hide prompt and just after pointer selector.

Is there a way to do that ?

**Comment by junegunn** [comment]
The whole line? It's not supported. `--prompt ''` is your best bet.

**Comment by slowpeek** [comment]
@junegunn I wonder what is the idea behind `--phony` without an option to hide the prompt? As a workaround I use `--phony --prompt='' --bind=change:clear-query` so that it looks and behaves like a pure item selector, but the flickering cursor is still there.

I probably overlook something, but isnt the prompt useless in `--phony` mode??

**Comment by junegunn** [comment]
> isnt the prompt useless in --phony mode

No, it's not useless. Here's an example: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-interative-ripgrep-launcher (`--disabled` is the new name for `--phony`)

> a pure item selector

For a pure item selector, there are many, possibly better, alternatives to fzf such as [smenu](https://github.com/p-gen/smenu).
