### ISSUE TITLE
Bash/Emacs-style Key-Bindings

### ISSUE THREAD

**Issue by nordlow** [junegunn/fzf#1414]
I really love fzf except for the default key-bindings as I want the Bash/Emacs mappings. Especially:

- **Ctrl-k**: Delete rest of the line into the kill buffer
- **Ctrl-t**: Transpose characters around cursor
- **Alt-t**: Transpose words around cursor
and probably more I'll disover as I needed them.

Is there a way to change these?

**Comment by eqyiel** [comment]
This depends on the shell you're using, for example

zsh: https://github.com/junegunn/fzf/blob/b46227dcb6f1718d66ad828443d9f03a4bd58c4c/shell/key-bindings.zsh#L36
bash: https://github.com/junegunn/fzf/blob/b46227dcb6f1718d66ad828443d9f03a4bd58c4c/shell/key-bindings.bash#L75

You can just override these in your shell initialization files.  For example, zsh's bindkey: https://github.com/eqyiel/dotfiles/blob/dff548627e65fd06a318de4d38f892768eaec1b0/nix/.config/nixpkgs/home/config/zsh/default.nix#L330-L337

**Comment by junegunn** [comment]
CTRL-K functionality is available via `kill-line` action

```sh
fzf --bind ctrl-k:kill-line
```

If you use it a lot, you might want to add `--bind` option to your `FZF_DEFAULTS_OPTS`.

`transpose-words` is not needed since fzf doesn't care about the order of the search terms. i.e. `foo bar` and `bar foo` are treated the same. If you want `foo` to appear before `bar`, type in `foobar` instead.

`transpose-chars` is not available.

**Comment by nnathan** [comment]
Apologies to open up an old issue.

I really don't want fzf keybindings clobbering my `C-t` keybinding to `transpose-chars`.

I have the following in my `.bash_profile`:

```sh
if [ -f /usr/share/doc/fzf/examples/key-bindings.bash ]
then
  source /usr/share/doc/fzf/examples/key-bindings.bash
  bind '"\C-t": transpose-chars'
fi
```

This fixes `\C-t` but I lose the keybinding for `\C-r` as it's completely removed (according to `bind -X`). The auxiliary bind command run after the source seems to do more than just set C-t, but also removes the existing keybindings.

Anyone know how to properly reset the `\C-t` keybinding?

**Comment by JonathanDoughty** [comment]
Another year later and I come to note that the following work for me to reset CTRL-T - after fzf's key bindings change it - back to what my muscle memory knows as transpose characters, and puts `fzf-file-widget` on an otherwise unused, and more mnemonic,  control character that I don't use in Emacs anyway.
```
bind -m emacs-standard -x '"\C-t": transpose-chars'
bind -m emacs-standard -x '"\C-f": fzf-file-widget'
```

`bind -X` in BASH_VERSINFO[0] greater than macOS's ancient bash 3 now says I have
```
"\C-f": "fzf-file-widget"
"\C-r": "__fzf_history__"
"\C-t": "transpose-chars"
```
