### ISSUE TITLE
How to install key bindings ?

### ISSUE THREAD

**Issue by tudor07** [junegunn/fzf#1428]
Title.
If I press Ctrl-R I get the basic reverse search, how do I get the fzf one ?

**Comment by tudor07** [comment]
$(brew --prefix)/opt/fzf/install

**Comment by FrancoLeiva** [comment]
I have this message:
-bash: syntax error near unexpected token `/opt/fzf/install'

**Comment by drw** [comment]
> I have this message:
> -bash: syntax error near unexpected token `/opt/fzf/install'

This happens if you omit the leading `$` symbol from the command. It's easy to mistake that `$` for the command prompt, but actually `$(brew --prefix)` uses shell parameter expansion to take the result of running `brew --prefix` (which returns the path to the brew directory) and prepend it to the rest of the path. 

So, for instance, if your brew directory is /usr/local, running `$(brew --prefix)/opt/fzf/install` is equivalent to running `/usr/local/opt/fzf/install`.

**Comment by Fr4nc0L31v4** [comment]
oh, thanks for aswering. Is solved!
