### ISSUE TITLE
--with-nth implies it wont effect searching but it does

### ISSUE THREAD

**Issue by i-am-eva** [junegunn/fzf#1440]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

**From the manual**

       -n, --nth=N[,..]
              Comma-separated  list  of  field  index expressions for limiting
              search scope.  See FIELD INDEX EXPRESSION for the details.

       --with-nth=N[,..]
              Transform the  presentation  of  each  line  using  field  index
              expressions

To me, this reads that "`--with-nth` will alter what you *see* in the list, while `--nth` will alter what you *search*. This behaviour doesn't seem to occur though, so either (to my brain) the docs need a bit of a tune up or there is a bug.

**Here is a demo**

```
printf "all_files\nfile_a_only_1\nfile_a_only_2\n" > file-a
printf "all_files\nfile_b_only_1\nfile_b_only_2\nfile_b_and_file_c\n" > file-b
printf "all_files\nfile_c_only_1\nfile_c_only_2\nfile_b_and_file_c\nfile_c_only_3\n" > file-c

ls | xargs -I {} sh -c 'printf "{}:"; cat {} | tr "\n" " "; printf "\n"' | fzf -e --delimiter ":" --nth 1,2 --with-nth 1 --preview="cat {1}" --preview-window="up:40"
```

**What I want to happen**

I want to see a list of filename (`file-a`, `file-b`, `file-c`) and be able to filter them by *content*. I.e: type `file_b_only` and see the list view highlight `file-b` and see `file-b` in the preview window. 

**What does happen**

As soon as I get to `file_`, all results disappear because none of the filenames match, even though the content *is* passed to `fzf`.

If you run the same command but with `--with-nth 1,2`, 

```
ls | xargs -I {} sh -c 'printf "{}:"; cat {} | tr "\n" " "; printf "\n"' |  fzf -e --delimiter ":" --nth 1,2 --with-nth 1,2 --preview="cat {1}" --preview-window="up:40"
```

You will see the desired behaviour, but displayed in an undesirable manner. This wouldn't actually be *too* bad but when the files are quite long, it tends to break `fzf`s rendering and text starts to flow over the bottom 3 "interface" lines (with and without a preview window).

I'm 99% sure this is actually behaving as intended, but as the docs read, if it is intended, I'm not sure I can figure why you'd have both `--with-nth` and `--nth` if they both alter search scope.

```
fzf --version
0.17.5 (brew)
```

**Comment by rktjmp** [comment]
I wanted to do something nearly exactly similar and hit the same problem.

It seems that when we make [a `chunkList`](https://github.com/junegunn/fzf/blob/e67cc75063d0a1a2e7aa6090a3d9845d517ed5c2/src/core.go#L101-L114) we do include `origText`. I traced the call to `Transform` which ends up in `Terminal` then sets stuff on`EventBox`, which makes me think I'm not looking in the right place.

I looked around `Merger` and `Item`, `Item#AsString()` seems to take `origText` into account.

I wonder if it's an effect [here in `core.go`](https://github.com/junegunn/fzf/blob/e67cc75063d0a1a2e7aa6090a3d9845d517ed5c2/src/core.go#L154-L178)

The `if` block for `streamingFilter` uses `opts.Printer(item.text.ToString())` where as the non streaming `else` uses `opts.Printer(merger.Get(i).item.AsString(opts.Ansi))`.

I'm unsure how to test this, I *think* my original demo will be considered as "streaming" since it's using a pipe and fills as more STDIN appears. I'm not sure how to convert it into a non-streaming demo.

**Comment by rktjmp** [comment]
These functions [`basicMatch`](https://github.com/junegunn/fzf/blob/e67cc75063d0a1a2e7aa6090a3d9845d517ed5c2/src/pattern.go#L320) and [`extendedMatch`](https://github.com/junegunn/fzf/blob/e67cc75063d0a1a2e7aa6090a3d9845d517ed5c2/src/pattern.go#L333) in `Pattern.go` both check if `p.nth` is true and then call `transformInput` which uses 

```
	if item.transformed != nil {
		return *item.transformed
	}
```

I think this is a bug.

`item.transformed` is set when we make [an item that is transformed by the `--with-nth` option](https://github.com/junegunn/fzf/blob/e67cc75063d0a1a2e7aa6090a3d9845d517ed5c2/src/core.go#L101-L114) but when we're doing our matches we should be operating either on `origText` or some hypothetical `transformed_for_nth_option` field.

I'm not a Go programmer so getting around this is a bit beyond me right now but I think that is where the behaviour originates.

**Comment by rktjmp** [comment]
As a hack, altering [transformInput](https://github.com/junegunn/fzf/blob/e67cc75063d0a1a2e7aa6090a3d9845d517ed5c2/src/pattern.go#L383), to be

```
func (p *Pattern) transformInput(item *Item) []Token {
  // skip this, safe to remove? unsure when we'd want to match on the transformed "--with-nth" text
  // if item.transformed != nil { 
  //    return *item.transformed
  //  }

  tokens := Tokenize(item.text.ToString(), p.delimiter)
  ret := Transform(tokens, p.nth)
  // this actually looks like a code smell to me, we reuse transformed for
  // --with-nth and --nth (at least here)
  // unsure if this is just a cache field that is supposed to be dual purpose
  // probably better to split them to two fields if they are a cache.
  item.transformed = &ret 

  // HACK, shortcut any thing done above, just tokenize on the items original text
  // this should probably be some kind of TokenizeForNth(items.text, p.nth, p.delimiter)
  return Tokenize(item.AsString(true), p.delimiter)
}
```

Makes the original issues behaviour work as expected. I'm unsure how safe this change is to make though in regards to how the system interacts with the --nth option. It seems like they're a bit intermixed.

**Comment by rktjmp** [comment]
@junegunn see pull request #1447

**Comment by rktjmp** [comment]
Apologies, I didn't realise there was a second test suite (`test_go.rb`) before opening the pull.

It seems that the failed tests are because the original behaviour is intended.

I think it would probably be more accurate to describe `--with-nth` as "reorders the input line by delimiters for display and for search" and `--nth` as "specifies which indexes on the `--with-nth`-reordered line to search (or original if no `--with-nth` is present)"

I'm not sure what the usecase for reordering/selecting-parts-of a string then searching within that reorder compared to just having both nth options operating on the original line. That seems like the more  obvious behaviour.

I wonder if it would be possible to add another option, `--show-only` or something, for altering how lines are shown vs searched?

My reason for wanting something like this is so I can do

```
git log --pretty="format:%h%x00%s%x00%N%x00%cn" | fzf -e --delimiter="\0" --with-nth=1,2 --nth=1,2,3,4
```
and have `fzf` show the git commit hash and subject line, but allow me to filter via hash, subject, other commit message lines or author.

**Comment by TamaMcGlinn** [comment]
It would still make a lot more sense if --n-th and --with-nth could be changed to both apply to the original list. That would also allow the usecase where you want to display field 1 but search in field 2. From reading [the original discussion of this flag](https://github.com/junegunn/fzf/issues/102), since the interplay between the new and existing parameters was not discussed, it was just an accident that it works in the current, unintuitive way.

**Comment by aktau** [comment]
I too would have liked to include a (giant) hidden field today, to be used only for searching (I would neither display nor return it).

I know it's not the original design/intention, but I suppose it's a use-case that sometimes comes up. (I haven't needed it before, and I've been using fzf for years, so there's that).
