### ISSUE TITLE
Option to hide the "rail"

### ISSUE THREAD

**Issue by erusev** [junegunn/fzf#1468]
By "rail" I mean the vertical bar on the left where the `>` shows the selected item.

For me, the different background of the selection is enough to indicate which is the selected item and the rail with the `>` pointer doesn't feel necessary.

**Comment by chdiza** [comment]
Or at least allow that rail to be colorable independently of other elements.

**Comment by cevhyruz** [comment]
@erusev I don't think it's possible, but you could atleast set it to match the background color of fzf 
(`fzf --color=dark,bg+:234,bg:234`). See the "Display" section of the man page.

**Comment by junegunn** [comment]
The closest you can do is to set the color of `bg+` to match that of `bg` as suggested by @cevhyruz. Since `bg` by default uses the default background color of the terminal. You can just set `bg+` to `-1` to have the same effect.

```sh
fzf --color=bg+:-1
```

I'm not planning to add more options for tweaking minor visual elements, trying not to bloat fzf with ni che features few people actually use.
