### ISSUE TITLE
Suboptimal sorting of file names

### ISSUE THREAD

**Issue by yglukhov** [junegunn/fzf#1483]
In case of file names fzf suggests a suboptimal result.
Steps to reproduce:
```
mkdir -p test/mysuperproject test/tests
cd test
touch mysuperproject/myfile.c tests/test_myfile.c
fzf -q myfile
```
**Expected result**: fzf would suggest `mysuperproject/myfile.c` as the best result.
**Actual result**: fzf suggests `tests/test_myfile.c` as the best result.

**Comment by sudo-nice** [comment]
IIRC, it happens because fzf is unaware of the strings it sorts, to be paths. It picks the shortest matched string by default, and you can see that:

```sh
tests/test_myfile.c # - this is shorter
mysuperproject/myfile.c
```

A solution here might be providing `--tiebreak=end`, or to apply the search pattern to the last path component only with `--delimiter=/ --nth=-1`. But be warned, though any of this approach could be helpful in this particular case, it can get into your way in some other cases.

**Comment by sudo-nice** [comment]
>but it seems to have no effect in this case

@yglukhov my bad, you are right.

**Comment by junegunn** [comment]
```sh
$ fzf -f myfile | head -1
mysuperproject/myfile.c

$ fzf --version
0.50.0 (d169c951)
```
