### ISSUE TITLE
GDB History and FZF

### ISSUE THREAD

**Issue by Degiorgio** [junegunn/fzf#1516]
Is it possible to use FZF with GDB history?

More specifically,  gdb has a 'command' history,  can I use FZF to search for past commands using FZF instead of the default? If so how?

**Comment by junegunn** [comment]
No idea.

There is a Ruby implementation of Readline which allows using fzf for history search, but I don't think it's possible with gdb.

https://stackoverflow.com/questions/46167332/how-to-i-make-reverse-i-search-history-use-fzf-in-irb-or-pry-console

**Comment by filipkilibarda** [comment]
I wrote a [short patch for GDB that integrates FZF](https://github.com/filipkilibarda/gdb_fzf_patch/blob/master/gdb.patch) into it.

I included the [installation instructions](https://github.com/filipkilibarda/gdb_fzf_patch) in the README of the repo. It includes instructions for building GDB.

As @junegunn mentioned, there is no other way. FZF works with bash because bash has the `bind` builtin with the `-x` option (see `man bash`). This allows FZF to work with readline in Bash.

GDB doesn't have this feature so the only way is to customize it. The patch is simple. Fork FZF on <kbd>Ctrl+R</kbd>, pipe the history in, read the result and populate the readline buffer/prompt with the selection from FZF.

**Comment by lebr0nli** [comment]
Hi @Degiorgio, I wrote a [GDB plug-in](https://github.com/lebr0nli/GEP) that supports fzf history search and make it public a few hours ago, you can try it if you still have the same problem.
The difference between my plug-in and @filipkilibarda  's patch is that I build with GDB's Python API.
BTW, I'm still working on this plug-in, so if you find any bug, please let me know!
Thanks!

**Comment by EgorDuplensky** [comment]
> Hi @Degiorgio, I wrote a [GDB plug-in](https://github.com/lebr0nli/GEP) that supports fzf history search and make it public a few hours ago, you can try it if you still have the same problem. The difference between my plug-in and @filipkilibarda 's patch is that I build with GDB's Python API. BTW, I'm still working on this plug-in, so if you find any bug, please let me know on my repo's issue page. Thanks!

This is a pure gold. Thank you!
