### ISSUE TITLE
Simplify modification of default command

### ISSUE THREAD

**Issue by memeplex** [junegunn/fzf#1522]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Currently the proposition of modifying the (rather complex) provided default command is of the all-or-nothing kind. It's not really possible to add some option to find or whatever without changing the whole command. It's not even possible to redefine find as an alias or function since the default uses `command find`.

Why not adding an environment variable to pass additional find options or, alternatively, some way of dumping the current command to the stdout in order to alter it?

**Comment by junegunn** [comment]
I don't want another option for that. fzf was designed to be a unix filter like grep (`ls | fzf`), so the "default command" thing is just an optional feature for minor convenience.

fzf by default uses `find` only because it's universally available. I would choose an alternative that is easier to use like fd if I were to change the default.

https://github.com/junegunn/fzf/blob/master/README.md#respecting-gitignore
