### ISSUE TITLE
Question about +m option (and other undoc'd options)

### ISSUE THREAD

**Issue by unphased** [junegunn/fzf#153]
I feel dumb for writing dumb questions like this, but I really can't figure out what these options are, and they are littered all over the helper shell scripts and examples here. It's not listed in the `--help` text. What does `+m` do?

**Comment by unphased** [comment]
Is it perhaps `do not allow multi select`? I figured omitting `-m` would accomplish that.

**Comment by junegunn** [comment]
> I think perhaps +m is do not allow multi select? I figured omitting -m would accomplish that, though, but I think I understand that it is to override the FZF_DEFAULT_OPTS setting -m.

Correct! It's a shared convention of some unix tools to unset an option (`-` prefix for setting, `+` for unsetting, and `--no-LONGOPT`) so it's not explicitly documented. And you're right that its purpose is to explicitly override possible `-m` in FZF_DEFAULT_OPTS.

> but why the trailing ,..?

To allow search against the first field as well. Sometimes there are many similar entries in history, and you want you pinpoint one using its index number. Then you might ask why we use `--nth` option in the first place. The reason is to allow some flexibility in `--extended` search mode. If you have `--extended` in FZF_DEFAULT_OPTS, then you can use patterns like `^git` or `pull$`. So for example, let's say we have this in our history:

```
  7890     git clone
```

Having both `2..` and `..` allows me to do both `^78` (`2..`) and `^git` (`..`). Makes sense?

**Comment by unphased** [comment]
@junegunn Makes sense! :+1: Thanks for taking the time to clarify. Awesome

**Comment by unphased** [comment]
Can I put even more fields to the -n option? like `-n2..,4..,..`

I have a special history logger for my z shell and it stores many fields (timestamp, command, working dir of command, terminal environment name (whether i'm on my mac or putty, in the VM, over SSH, inside tmux), which of /dev/ttyX) so i figured it would be neat if I could have it let me use those anchors like `^git` and `^Thu Apr 23`... 

I mean i guess it is practically moot since i have so much raw information presented to fzf that I can just keep typing to narrow it down.

**Comment by junegunn** [comment]
> Can I put even more fields to the -n option? like -n2..,4..,..

Yes you can, there's no limit to the number of field expressions.
But the search will be proportionally slow.
