### ISSUE TITLE
rsync complains about error in bash-completion

### ISSUE THREAD

**Issue by mcepl** [junegunn/fzf#1546]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

This is fzf 0.17.4, because I haven't managed to persuade openSUSE build system to build with more recent Go, but I don't think file ``shell/completion.bash`` is the same.

However, whenever I run rsync, I get this error:
```sh
~$ rsync -avz --delete home:Knihy/ /home/matej/Knihy/
/usr/share/bash-completion/completions/fzf: line 33: bind: warning: line editing not enabled
receiving incremental file list

sent 49 bytes  received 25,553 bytes  17,068.00 bytes/sec
total size is 350,759,695  speedup is 13,700.48
~$
```
Actually, looking at this, I am not sure whether the error is on my side or on the other side of ``rsync``.

**Comment by junegunn** [comment]
In the latest version, we have an extra guard statement (see https://github.com/junegunn/fzf/commit/8cf45a519788c42ae4312fe9295e3cd9b988f372) so that the script is not loaded in a non-interactive session.

Note that the change is only needed if you don't use the install script to generate `~/.fzf.bash` which already handles the case: https://github.com/junegunn/fzf/blob/ff951341c993ed84ad65344e496e122ee3dddf67/install#L261

**Comment by mcepl** [comment]
[prefs.js.source.txt](https://github.com/junegunn/fzf/files/3038103/prefs.js.source.txt)
[prefs.js.target.txt](https://github.com/junegunn/fzf/files/3038107/prefs.js.target.txt)
