### ISSUE TITLE
New feature: auto height

### ISSUE THREAD

**Issue by eplanet** [junegunn/fzf#1558]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I've been proposing a change in `kubectx` ([#143](https://github.com/ahmetb/kubectx/pull/143)), to adjust the `fzf` size within temrinal using `--height` parameter and providing the number of items plus 2.

After discussing the details, we went to the conclusion that it might be interesting to have `--height=auto` directly implemented in `fzf` rather than fiddling around with some workaround to achieve the same result.

Would it be acceptable to offer such a value for automatically adjust height when making an interactive choice within the terminal?

**Comment by ahmetb** [comment]
I second this proposal. 

If fzf knows the input line count, it can use it to render auto height based on that. 
Otherwise specifying —height would require calling the target program twice, which isn’t as performant. 

Not to mention, the output can change between the two invocations (one for calculating line count vs one from fzf) to the target command. This can cause consistency issues.  It would be better if fzf handled it.

**Comment by junegunn** [comment]
I like the idea but implementing it is going to be non-trivial because:

1. fzf reads the input asynchronously; it starts the finder before knowing the exact number of candidates as it was inherently designed to work with long-running processes (e.g. `find / | fzf`)

2. And because it has a lot of options that affect the number of items that can fit on the screen.  Properly implementing "auto" height without breaking any of these can be quite tricky.

```sh
for i in $(seq 100); do echo $i; sleep 1; done |
    fzf --height 50% --header $'multi-line\nheader' \
        --header-lines 3 \
        --border \
        --inline-info \
        --preview 'echo {}' \
        --preview-window up \
        --margin 2,10 \
        --layout reverse
```

I'm not really bothered by a few extra lines when using a fixed height (e.g. `fzf --height 40%`), so this is not my priority.

**Comment by kdheepak** [comment]
It would be nice to have an option that chooses the height based on the current cursor location. This way if the user runs `fzf` after <kbd>C + l</kdb> or `clear`, it would use the full screen. But if the cursor is at the bottom of the screen, it could fallback to the default height passed in (i.e. `40%` or `60%`). Thoughts?

**Comment by junegunn** [comment]
```sh
fzf --height=~100%
```

https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0340
