### ISSUE TITLE
Minor bug with scrolling inside preview and coloring

### ISSUE THREAD

**Issue by mike239x** [junegunn/fzf#1609]
- Category: fzf binary
- OS: Linux 18.04
- Shell: bash as well as fish

Say I got the command `echo whatever | fzf --ansi --preview='cat colored_file' --height=1`, where the `colored_file` contains a ANSI color code, then some text with line breaks. Now, if we run that command and try to scroll with the mouse inside of the preview area past the ANSI code, then the text inside of the preview window will no longer be colored.

I think this is a bug, even though a really tiny one.

Just in case - an attachment with the two file from above: [color-preview-bug.zip](https://github.com/junegunn/fzf/files/3302055/color-preview-bug.zip)

**Comment by lberrymage** [comment]
I can confirm this with the demo you provided in zsh on Arch Linux - it seems to be universal for anyone wondering where to start looking

**Comment by mike239x** [comment]
Well, I think I understand where this is coming from:

For the `preview` fzf just takes the text output from the command run, and puts needed lines into the preview window. After ones scrolls past the escape codes for coloring those are no longer put on the screen, and so the text in there "loses color". The code is kinda "working as expected".

So if one actually wants to fix that - one would have to probably write a tool that would duplicate the escape codes at the start of every line, and put that tool in between the output from `--preview` command and the resulting preview text.

Alternatively one could add some text styling functionality inside of fzf code itself, but I think having a separate tool for that would be a better solution.

**Comment by junegunn** [comment]
Yes, I'm aware of the problem, but I implemented that way for performance reasons and to keep the implementation relatively simple. In order to emulate the perfect ANSI color state, fzf has to find and parse ANSI codes from the beginning of the text even when it's displaying the 1,000th page, and that can become quite inefficient when you scroll the page up and down. Also, there are ANSI escape sequences that are really hard to emulate on the preview window, such as the sequences for moving cursor up and down. So I would say that this is just a limitation of fzf preview window, but I believe it's still good enough for simple "previewing" purposes.
