### ISSUE TITLE
How to let fzf follow the symbolic links?

### ISSUE THREAD

**Issue by roycyt** [junegunn/fzf#161]
Hi,
Thank you for this great work!
I used "Unite file_rec/async" in neovim to find files before.
After I found fzf, this is now my favorite. It is super fast.

Could I know how to let fzf follow the symbolic links?
I checked the man page and command help and did not find any information about that.

**Comment by junegunn** [comment]
Hi, fzf currently does not work on neovim, I'll probably be working on neovim support during the weekend (see #137).

Having said that,
- fzf works as a unix filter, like grep, so you have to feed some input into it. e.g. `seq 10000 | fzf`
- But since most people use fzf with the list of files, I made fzf to spawn its own `find` process when input is not explicitly given.
    - The hard-coded default command is `find * -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null`
- You can override the default command with `$FZF_DEFAULT_COMMAND`
```sh
export FZF_DEFAULT_COMMAND='seq 1 100'
fzf
```
- And `:FZF` command of Vim plugin is built upon this behavior. You can make it follow symlinks by setting FZF_DEFAULT_COMMAND to the command that works that way.
- Or you can define your own command with `fzf#run()` function as described in the readme page. (see https://github.com/junegunn/fzf#usage-as-vim-plugin for details)

**Comment by junegunn** [comment]
Try this:
```sh
export FZF_DEFAULT_COMMAND="find -L * -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null"
```
