### ISSUE TITLE
fzf better behavior on fish shell compared to zsh

### ISSUE THREAD

**Issue by hovnatan** [junegunn/fzf#1629]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [x] fish

If I use `C-T` binding at the end of `vim /home/hk/lib/` in fish shell the suggestions come from the  files in `/home/hk/lib/` but in zsh shell the suggestions come up from the current working dir (e.g., home dir). Is this the intended behavior?

**Comment by junegunn** [comment]
I would say it's an undocumented *bonus* feature for fish. CTRL-T was initially designed/implemented without the feature, but for fish, it was added in https://github.com/junegunn/fzf/pull/759. There are some other minor differences in the implementations due to the difference of the capabilities of the three shells.
