### ISSUE TITLE
Feature Request: Don't display preview pane if preview command returns nonzero status code

### ISSUE THREAD

**Issue by casey** [junegunn/fzf#1647]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have a custom preview command that looks like this:

```
#!/usr/bin/env bash

if [[ -d $1 ]]; then
  # preview directory contents with `exa`
  exa --color always -l $1
elif [[ -f $1 ]]; then
  # preview file contents with `bat`
  bat --color always --paging never $1
fi
```

If `$1` isn't a directory or a file, I'd like to be able to signal to FZF that it shouldn't display the preview pane. This would be useful in cases where I'm using FZF to search my command history.

A possible solution is, if the preview command returns a non-zero exit code, FZF could hide the preview pane.

This might break existing preview commands, so a way to make this backwards compatible would be to use a particular status code, say, `15` to indicate to FZF that it shouldn't display the preview pane.

What do you think?

**Comment by junegunn** [comment]
> This would be useful in cases where I'm using FZF to search my command history.

Sounds like you have global `--preview` option set in your `FZF_DEFAULT_OPTS`. (Sorry if it's not the case, but otherwise, I don't really see why you would need it.)

And I don't think it's a great idea, because fzf is a general-purpose text filter, and is not just for file paths. e.g. `ps -ef | fzf`, `git log --oneline | fzf`, etc. By doing so, you're starting failing preview process numerous times every time you use fzf with lists that are not paths, which is extremely wasteful.

Instead of relying on `FZF_DEFAULT_OPTS`, consider creating a script or an alias that sets the file preview option and use it in the right context.

```sh
alias fzfp='fzf --preview ...'
```

> This might break existing preview commands, so a way to make this backwards compatible would be to use a particular status code, say, 15 to indicate to FZF that it shouldn't display the preview pane.

Thanks for the suggestion, but I want to keep things simple, and I really don't want to encourage users to use a global preview option.

**Comment by 103sbavert** [comment]
Fzf is often used as a fuzzy finder for completions and it is possible that it makes sense for a command to show a preview for some arguments/options but not for others. For examplle `ls<TAB>` would show me file names while `ls --<TAB>` would show me options available to ls. It makes sense to show preview for file names but not for arguments given to `ls`.

Would be a nice addition to collapse the preview window, or, make a available a way for the preview command to modify the preview window dynamically (similar to `--bind 'key:event'` functionality).

**Comment by 103sbavert** [comment]
As a side note, i actually use a slightly modified version of the experimental `fzf-preview` script found in the source which shows files/directory/image previews and I use it to render the preview window contents for a subset of commands on `<TAB>` press (namely, `ls`, `cd`, `cp`, `trash`)
