### ISSUE TITLE
Feature request - search with trailing comment, do not expand comment

### ISSUE THREAD

**Issue by vmalloc** [junegunn/fzf#1675]
I had an idea to annotate some of my ZSH history with trailing comments to help me find important commands I use often, so the history entry would be something like:

```
: 1556195037:0;find . -name "*.JPG" | wc -l # count number of pictures
```
Then I would be able to use fzf through Ctrl+R and start typing "number of pictures" to find my command.

It would be nice to have an option to tell fzf to expand the entry *without* the trailing comment to avoid clutter. I'm also ok with having a global toggle for it.

Thanks again for this amazing project!

**Comment by junegunn** [comment]
Makes sense, but I decided not to add more options due to the maintenance burden. (https://github.com/junegunn/fzf/pull/1492#issuecomment-461670530)

The implementation of the key binding is pretty short and should be straightforward. So consider customizing the function and put it in your `.zshrc` to override the default implementation.

https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh#L66-L83
