### ISSUE TITLE
fzf -1 should still display a lone match while waiting for input

### ISSUE THREAD

**Issue by stephentalley** [junegunn/fzf#1721]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

When running "fzf -1", fzf waits until a 2nd entry is found before displaying the interactive TUI. **This prevents the user from manually selecting the lone entry to short-circuit what could be a considerable time until the input has all been read.**

This example simulates a use case where data may take a long time to gather:

    % (echo hello; sleep 10; echo there) | fzf -1

In this case, no interaction is possible until "there" is read.  fzf -1 should instead show the interactive TUI right away, and only auto-select the first entry and exit when the input stream is closed.

**Comment by junegunn** [comment]
That is by design. `--select-1` was added to address a different requirement than yours; not to start the interactive finder if possible to avoid an unnecessary flickering of the screen during the script execution.

```sh
# No need to start fzf and close it immediately
a-quick-command-that-generates-a-single-line-matches-foo | fzf -1 -q foo
```

See my previous comment on the option: https://github.com/junegunn/fzf/issues/1686#issuecomment-531292390

I decided not to support the alternative option which terminates fzf *after* starting the UI, as I believe sudden termination can be confusing to the users. e.g. fzf terminates just before I tried to change the search query, etc.
