### ISSUE TITLE
CTRL+T conflict with CTRL+SHIFT+T which has been used to create a new tab of terminal

### ISSUE THREAD

**Issue by GopherJ** [junegunn/fzf#1765]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

hit together CTRL+SHIFT+T, it triggers also fzf while it shouldn't because it's for creating a new tab of terminal.

**Comment by 0ion9** [comment]
These instructions are inadequate, as fzf does not bind ctrl-t by default, thus triggering ctrl-t would have no effect.

However, with the necessary addition -- `--bind ctrl-t:replace-query` when invoking fzf --
I cannot reproduce your report. Ctrl-T correctly takes the action it is bound to, and SHIFT+CTRL+T does not effect fzf, but only makes the terminal open a new tab. 

This is with Sakura, a libVTE based terminal. 

Using `fish` shell in order to get the use of the keypress debugging utility `fish_key_reader`, it becomes apparent that pressing Shift+Ctrl+T does not send any key combination to the shell.

**Comment by LuRsT** [comment]
@GopherJ are you still experiencing this issue?

**Comment by GopherJ** [comment]
Yes, after installing fzf, CTRL + T has been binded to fzf's file fuzz searcher, I don't quite understand why @0ion9  was saying:

> These instructions are inadequate, as fzf does not bind ctrl-t by default, thus triggering ctrl-t would have no effect.

At least for me it has effect! It triggers fzf. I'm on ubuntu & deepin.

**Comment by GopherJ** [comment]
I still have this problem, but it just happens to `deepin-terminal`, while using `gnome-terminal` I don't have this problem.

**Comment by 0ion9** [comment]
@GopherJ 
Right. The thing you didn't clarify in OP was that the Ctrl+T binding was a binding of zsh. I assumed it was a binding within fzf.

Still, from what you have said more recently,  it seems rather likely that the cause I suggested was correct (terminal is propagating keypresses that instead should be consumed by the GUI).

**Comment by LuRsT** [comment]
@GopherJ, seems like the mystery has been solved, you're stuck with using `gnome-terminal` (or another one that works well). Happy to close this issue?

**Comment by GopherJ** [comment]
Yes. I'll try to use gnome-terminal
