### ISSUE TITLE
Multi-select in reverse history search mode

### ISSUE THREAD

**Issue by farzadmf** [junegunn/fzf#1806]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Hi, these are my settings:
```bash
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_R_OPTS="--multi --preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
```
But it seems to me that the `--multi` option in `CTRL+R` doesn't have any effect. If I do `CTRL+T`, then I can use `TAB`, `SHIFT+TAB` to select/deselect multiple items, but when I do `CTRL+R`, and I press `TAB`/`SHIFT+TAB`, nothing happens.

Is there an additional setting that I need to set?
Thank you

**Comment by junegunn** [comment]
The current implementation doesn't work with multiple selected entries because it uses `zle vi-fetch-history`. So it explicitly disables `--multi` flag by appending `+m` (a.k.a `--no-multi`).

https://github.com/junegunn/fzf/blob/577024f1e9bfc98f48e7c5bead445bc9d7dfc3c5/shell/key-bindings.zsh#L67-L84

Currently, your only option is to reimplement the function in your zsh configuration file.

**Comment by propilideno** [comment]
Of course you can, `export FZF_DEFAULT_OPTS="--multi #"` or `export FZF_CTRL_R_OPTS="--multi #"`,, `#` will comment the `+m` option and will ignoring everything after it.
