### ISSUE TITLE
Change Tab and S-Tab

### ISSUE THREAD

**Issue by nomasprime** [junegunn/fzf#1840]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Is it possible to change this? Would like to try using space instead.

**Comment by 0ion9** [comment]
See the AVAILABLE ACTIONS section of the man page; specifically `toggle+down` and `toggle+up`

Short answer: yes, use the `--bind` option. 

Binding space will, of course, effectively disable certain functions that depend on space being enterable in the input field (such as matching against multiple patterns at once).

**Comment by junegunn** [comment]
@0ion9 Thanks for the great answer.

**Comment by nomasprime** [comment]
Thanks @0ion9. Haven't actually tried multiple select yet, wanted to know about the bindings beforehand, didn't realise the implications. Sounds like a non-starter.

**Comment by 0ion9** [comment]
@nomasprime 'Multiple selection' (with `-m`) is different from 'matching based on multiple patterns' (`foo ogo$` matching the single item 'foogopogo'), just to clarify. The former would be unaffected. Couldn't tell which you actually meant from your comment. Because patterns are fuzzy, losing out on multiple-pattern matching wouldn't be a big deal to me personally.

(You posting this issue made me think. I'm currently considering binding space to `toggle+down+clear-query`, it seems to make selecting multiple items super fast. For non `-m` invocation, binding space to `accept` looks like it'll make things faster.)
