### ISSUE TITLE
Example function vg() doesn't work after running function fe() 

### ISSUE THREAD

**Issue by zysimplelife** [junegunn/fzf#1859]
- [*] I have read through the manual page (`man fzf`)
- [*] I have the latest version of fzf
- [*] I have searched through the existing issues

## Info

- OS
    - [* ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [* ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Example function vg() doesn't work after running function fe() 
Both functions are in  page https://github.com/junegunn/fzf/wiki/Examples, but they  conflict with each other. 
The problem is fe() function try to set  IFS=$'\n' , which break the behavior of command read in function vg().  

fe() {
  local files
  **IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))**
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

vg() {
  local file
  local line
  **read -r file line <<<"$(ag --nobreak --noheading $@ | fzf -0 -1 | awk -F: '{print $1, $2}')"**
  if [[ -n $file ]]
  then
     vim $file +$line
  fi
}

Solution can be two alternative
a) unset IFS in function fe() before return. (recommended)
b) set IFS in function vg()

**Comment by junegunn** [comment]
Thanks for pointing it out. The wiki page is maintained by the community and I don't test or review the code.

It looks like an easy fix to the problem is use parentheses instead of braces. I updated the examples.

https://github.com/junegunn/fzf/wiki/Examples/_compare/8d61e430db165f10156afcc6ebf83842b7c80cf2...e066eb01f569822cffa1bd27dafe1fd412d13bbc
