### ISSUE TITLE
`CTRL-S/V/T` are not working when using fzf#run

### ISSUE THREAD

**Issue by schmooser** [junegunn/fzf#187]
HI Junegunn,

I'm trying to use `fzf` to replace `ctrl.p`, but when I implemented custom searches (within git project, mru, buffers) using `fzf#run` I'm unable to use `CTRL-S/V/T` shortcuts.

Here is the excerpt from my `.vimrc` (buffers and mru are from fzf wiki)

    " Current Buffers
    nnoremap <silent> <C-b> :call fzf#run({
    \   'source':  reverse(<sid>buflist()),
    \   'sink':    function('<sid>bufopen'),
    \   'options': '+m',
    \   'down':    len(<sid>buflist()) + 2
    \ })<CR>

    nnoremap <silent> <C-p> :call fzf#run({
    \   'source': v:oldfiles,
    ->  \   'sink' : 'e ',  <-- IS THE SPACE AFTER e NECESSARY?
    \   'options' : '-m --no-sort',
    \ })<CR>

    function! FZFGit()
        " Remove trailing new line to make it work with tmux splits
        let directory = substitute(system('git rev-parse --show-toplevel'), '\n$', '', '')
        if !v:shell_error
        lcd `=directory`
        call fzf#run({'sink': 'e ', 'dir': directory, 'source': 'git ls-files'})
        else
        FZF
        endif
    endfunction

    nnoremap <silent> <C-f> :FZF<CR>
    nnoremap <silent> <C-g> :call FZFGit()<CR>

How to set the shortcuts?

And what about space after 'e' in the middle of the script (highlighted)?

**Comment by junegunn** [comment]
Hi, there is no default key binding. `:FZF` command uses [`--expect` option](https://github.com/junegunn/fzf/issues/163) so that fzf can finish on those keys. See the implementation of it [here](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L313-L354).

So the vim plugin for fzf only provides a primitive building block `fzf#run()` for more sophisticated features. This gives you greater flexibility, but it also means that you'll have to write some Vimscript. You might want to check out some third-party projects: https://github.com/search?utf8=%E2%9C%93&q=fzf+vim

> And what about space after 'e' in the middle of the script (highlighted)?

Not required. Maybe an outdated example.
