### ISSUE TITLE
Add more useful matching for files and caching

### ISSUE THREAD

**Issue by Aphexus** [junegunn/fzf#1872]
On Windows.

I have directories with names like "A - B - C" (A,B,C are variables, maybe more, maybe less)

I am trying to find the best matching files to stick in those directories. They may not match every entry because they might be stored like A\B\C or even A\C\B. (or may even be missing one)

When I use fzf I either get no matches or a huge number, depending on what I'm searching for.

I used fzf because the matches because the directory names are are not exactly the file names(may be quite different but should give all the info needed to find an appropriate match)

for /D %%q in (*) do (
    chdir /d C:\Data
    echo searching for "%%~nq"
    fzf -1 -0 -f "%%~nq"
    chdir /d %OLDDIR%
)

In Data there are millions of files. It would also be nice if they could be cached. I guess I could list them all to a file then pipe in to do this, but could a simple --cache=file switch be added?

As for "better" matching. All I can think of is that the directories be subdivided in to words and then the each "word" is searched and the ones that match the most words is returned.

I could try to do this manually by breaking up the directory in to the parts but I think it is just too messy.

Another feature might be to be able to match on the path too? (E.g., If I had C:\Data\A\B\C and trying to match A - B - C then it will match). The thing is, it shouldn't generally be exact since because of misspellings, etc.  Generally if there is any reasonable match then it will be the one.

The idea is to simply find the best ranking match as that will almost surely be the correct file, but not to over do it or crap out on minor things.

**Comment by junegunn** [comment]
> I guess I could list them all to a file then pipe in to do this

You should do it that way. fzf can internally start a program according to FZF_DEFAULT_COMMAND just for a minor convenience but that's it. We are not interested in developing a more efficient directory traversal algorithm or caching scheme, just like it's not a valid concern for `grep` (or `head` or `tail`, etc).

As for the matching scheme, it's not clear to me what you're suggesting here. But I have to say that fzf is a general-purpose text filter rather than a specialized filter for file paths, we will not implement a specialized algorithm for a specific type of input. fzf can only implement a generic algorithm that is expected to work okay with most of the input types.

**Comment by junegunn** [comment]
Having said that, it looks like you're not "piping in" the input, then the next version of fzf will probably perform better in your case. See https://github.com/junegunn/fzf/pull/1847
