### ISSUE TITLE
execute-multi aka {+} limitations

### ISSUE THREAD

**Issue by tagwint** [junegunn/fzf#1880]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

execute-multi bound to a key is not executed if the number of selected lines is bigger than 32760

Code to reproduce:

```
$ cat test
#!/bin/bash
[ -f SelectedLines ] && rm SelectedLines
for i in `seq 32767`
do
 echo A
done |  fzf -m --bind "f5:execute: printf \"%s\" {+}>SelectedLines" --bind "alt-s:select-all" 
wc SelectedLines 
getconf ARG_MAX
```

Actions to reproduce:

- run code above 
- select all using alt-s
- try f5
nothing happens unless you decrease number of selected lines down to 32760
then f5 prints all selected lines to SelectedLines file

my output is 
```
$ bash test
    0     1 32759 SelectedLines
2097152

```
I understand that may be some limitation of system and want to know what exactly that is 
since my ARG_MAX value shows  a number 2097152 which is more than 32760.
Would like to know the nature of the limitation.

**Comment by junegunn** [comment]
For me this command

```sh
for i in `seq 63900`; do echo A; done | fzf -m --sync --bind "space:select-all+execute-silent(printf \"%s\" {+}>SelectedLines)+abort"; wc -c SelectedLines
```

stops writing the file at around 63900. Which seems to make sense because my ARG_MAX is 256K and fzf will expand `{+}` to `'A' 'A' 'A' 'A' ...` which quadruples the number of bytes. I'm not quite sure why the math doesn't check out in your case.

Having said that, for this ARG_MAX limitation, there is `f` flag for writing the selected entries to a temporary file rather. You can read about it in https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0190
