### ISSUE TITLE
Question: use [neo]vim for --preview

### ISSUE THREAD

**Issue by ghetto-ch** [junegunn/fzf#1884]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I tried to use nvim as preview command but it doesn't work. here is what I did:
`--preview 'nvim --noplugin -R {}'`
but I only get some strange output and no preview.
Is there a reason vim can't be used for preview? Is it because is not terminating?

**Comment by LuRsT** [comment]
Hi @ghetto-ch,

The reason you can't use vim for preview is because vim doesn't output to STDOUT, which is why you see the wierd characters. Why don't you try `cat` or `bat` or `highlight`?

`highlight` gives you syntax highlighting for example:

![2020-02-22-171853_1336x435_scrot](https://user-images.githubusercontent.com/263583/75096433-746dd880-5597-11ea-8602-8673a0c84a87.png)

**Comment by ghetto-ch** [comment]
Thank you @LuRsT for the explanation. I'm curreently using bat and the only reason I tried to use nvim is the highlighting being different between the two. Not really a problem, it just looks inconsistent when using preview inside vim. I will check highlight as well as you suggested.
