### ISSUE TITLE
[VIM] Quickfix Example Action in g:fzf_action Doesn't Work

### ISSUE THREAD

**Issue by levouh** [junegunn/fzf#1885]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
### Problem
_README-VIM_ example to populate the `quickfix` list doesn't work.

### System Information

_Vim_: 8.2.227
_OS_: Fedora 31
_Bash_: 5.0.11

### Vim Configuration

_~/.vimrc_

```
set rtp+=~/.fzf

call plug#begin('~/.vim/plugged')

    Plug 'junegunn/fzf.vim'

call plug#end()

let mapleader = ','

nnoremap <silent> <Leader>b :Buffers<CR>

function! s:build_quickfix_list(lines)
    call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
    copen
    cc
endfunction

let g:fzf_action = {
                    \ 'ctrl-q': function('s:build_quickfix_list'),
                    \ 'ctrl-t': 'tab split',
                    \ 'ctrl-x': 'split',
                    \ 'ctrl-v': 'vsplit' }
```

### Steps to Reproduce

```
$ vim
:e ~/.vimrc
:vs ~/.bashrc

<Leader>b
<C-q>
```

### Behavior

`~/.vimrc` buffer is opened in the window where `~/.bashrc` exists, so at the end of it all I have two vertically split windows both containing the same `~/.vimrc` buffer.

### Expected Behavior

The `quickfix` list is populated and opened, containing two entries for `~/.vimrc` and `~/.bashrc`.

**Comment by junegunn** [comment]
Unfortunately, commands in fzf.vim that doesn't print regular file paths are incompatible with `g:fzf_action`. The sink functions of those commands incorrectly assume that each value of `g:fzf_action` is a regular Vim command for opening a new window.

- https://github.com/junegunn/fzf.vim/blob/dc4c4c22715c060a2babd5a5187004bdecbcdea7/autoload/fzf/vim.vim#L602-L605
- https://github.com/junegunn/fzf.vim/blob/dc4c4c22715c060a2babd5a5187004bdecbcdea7/autoload/fzf/vim.vim#L966-L970

I don't have a good idea on how to fix this, because clearly, a function is only compatible with a certain type of list. i.e. `s:build_quickfix_list` can only process files, not buffer numbers, or Vim marks, etc.

**Comment by u0931220** [comment]
>commands in fzf.vim that doesn't print regular file paths are incompatible with g:fzf_action

I'm not 100% sure what you mean by this. What is an example of a command that doesn't print a regular file path?

>I don't have a good idea on how to fix this

I might be misunderstanding part of the problem here, but perhaps it would be useful to leave the handling up to the user if they wish to pass a function reference (`v:t_func`) for a mapping.

All functions could be required to implement:

```
function s:fzf_action_handler(cursor_index, selection_list)
    ...
endfunction
```

and the it is up to the user to understand what kind of information they are being passed, as they have defined the function themselves. I haven't delved this deep in to Vim yet, but it might also be useful to have a third argument that specifies `command_string` so that the user can handle different list values based on the command that is being used in conjunction with the binding?

This is all just a suggestion based on my very minimal understanding of how `fzf.vim` works, so if I am completely wrong here let me know. I will spend some time looking through the code, and perhaps look in to making a PR based on your advice and if it seems like this is the way to go.

There are two different use cases that I think would be useful:

1. Pass the single selection to the user-defined function.
2. Pass all selected items to user-defined function.

**Comment by junegunn** [comment]
> What is an example of a command that doesn't print a regular file path?

`:Buffers`. `[1] %   README.md` is not a regular file path, i.e. `vim "[1] %   README.md"` doesn't make sense. The "sink" function must know how to extract a file path from that line. `:Marks`, `:Colors`, `:Commits`, `:Lines`, etc.

Actually, `g:fzf_action` was designed to work only with fzf specs with no custom `sink` function. fzf.vim puts extra, hacky effort to make it work with some other commands as well, but we just realized that the trick doesn't always work well. 

Providing a set of fully customizable commands was never a goal of fzf.vim project. It was open-sourced to provide reference implementations of features that can be built on top of `fzf#run()` function from the main fzf repo (see https://github.com/junegunn/fzf.vim#rationale). Users are encouraged to implement their own commands using the low-level fzf library functions (`fzf#run()` and `fzf#wrap()`). Please read through https://github.com/junegunn/fzf/blob/master/README-VIM.md. You might want to also take a look at [some Vim examples in the wiki](https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim) to learn how things are implemented under the hood.

**Comment by junegunn** [comment]
Updated doc: https://github.com/junegunn/fzf/blob/master/README-VIM.md#global-options-supported-by-fzfwrap
