### ISSUE TITLE
Set multi-search result delimiter

### ISSUE THREAD

**Issue by rcywongaa** [junegunn/fzf#1920]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Currently, the default delimiter for multi-search results is a newline.  i.e. 
```
echo "aaa\nbbb\nccc" | fzf -m
```
And selecting `aaa`, `bbb` gives
```
aaa
bbb
```
Is there a way to configure it such that it outputs
```
aaa bbb
```
or
```
aaa,bbb
```
?

**Comment by rcywongaa** [comment]
This can easily be done by piping the result through `tr`

e.g. `echo "aaa\nbbb\nccc" | fzf -m | tr '\n' ' '`

**Comment by larsks** [comment]
It's not quite as easy as @rcywongaa would have you think, because fzf always includes a terminal delimiter. So for example, if you want `,` as a delimiter and naively run:

    printf "aaa\nbbb\nccc" | fzf -m | tr '\n' ','

And you make three selections, the output will be:

    aaa,bbb,ccc,

Note the trailing comma. Whether or not this is an issue depends on what you're doing, and may require additional filtering with e.g. `sed`. I ran into this trying to write a simple script for assigning github issues using the `gh` command line tool; if you were to do something like:

   gh issue edit 42 --add-assignee $(get-list-of-members | fzf -m | tr '\n' ',')

The command will fail with:

    failed to update https://github.com/yourorg/issues/issues/42: '' not found
    failed to update 1 issue

Life would be much simpler if (a) the fzf output delimiter were configureble and (b) if it were possible to drop the terminal delimiter. As it stands, you can do something like this:

    gh issue edit 42 --add-assignee $(get-list-of-members | fzf -m | tr '\n' ',' | sed 's/,$//')

**Comment by junegunn** [comment]
@larsks In that case, it would be slightly easier to use `paste` command.

```sh
fzf -m | paste -sd, -
```
