### ISSUE TITLE
Exiting Ctrl+R clears all my input

### ISSUE THREAD

**Issue by raymondchen625** [junegunn/fzf#1922]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Fzf brings up my history when I press Ctrl+R. Sometimes I couldn't find any match, due to in a different tab, and want to continue typing on my own. But it always clears anything I've input when I press Esc to exit. Is there a way to keep what I typed before?

**Comment by junegunn** [comment]
Fixed in #1886

**Comment by pdecat** [comment]
> Fixed in #1886

#1886 is about keeping what was typed on the command line **before** pressing Ctrl-R and Esc.

I believe the request in this issue was about keeping what was typed **after** Ctrl-R but **before** pressing Esc.

@raymondchen625 correct me if I'm wrong. If so, I'll open my own issue.

**Comment by raymondchen625** [comment]
@pdecat Yes, you're right. Keep the text I've typed after curl-r and before Esc.

**Comment by junegunn** [comment]
I see. While keeping what was typed before fzf makes sense, keeping what was typed on fzf is not always desirable. Because fzf is a "fuzzy finder" where you type in inaccurate search terms in any order. For instance, you can type `cln ^git` to find `git clone`, and you don't want it after you close fzf. Because of that, and because of [this concern](https://github.com/junegunn/fzf/pull/1492#issuecomment-461670530), I'm not going to add an option for this. But I believe you should be able to re-implement CTRL-R to have the behavior using something like `--bind esc:print-query+abort`

**Comment by pdecat** [comment]
Works perfectly (for me) with `--bind esc:print-query` in `FZF_CTRL_R_OPTS` environment variable.

Thanks!
