### ISSUE TITLE
Search and output hidden text?

### ISSUE THREAD

**Issue by kaukas** [junegunn/fzf#1951]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Amazing how powerful fzf is! This is not the issue though. :-)

I am sorry if this was answered but could not find it… Is it possible to feed text into fzf that would not be shown but could be (1) searched and/or (2) printed as output?

Example for (1) is like HTML `select`: choose by label, output id or value to stdout. E.g. given a list
```
Kubernetes
Docker
Virtualbox
```
and choosing an option would print its internal code (whatever it is).

Example for (2) is having a list of truncated words (among other things):
```
kube...s
loca...n
inte...n
```
but being able to find them via full text (e.g. `kubernetes` or `internationalization`).

Any ideas? Thank you!

**Comment by junegunn** [comment]
> Is it possible to feed text into fzf that would not be shown but could be (1) searched and/or (2) printed as output?

No, it's not supported. We decided that such a feature would be too confusing to the users.

**Comment by mattmc3** [comment]
You can achieve similar behavior by putting the text you're searching far off to the right, using the `--preview` window, and locking horizontal scrolling with `--no-hscroll`. For example, say you had the following tab delimited text file of HTML element descriptions that you wanted to search:

```
a	anchor tag for hyper links
b	bold text style
em	emphasis text style (typically italic)
i	italic text style
strong	strong text style (typically bold)
ul	underline style
```

Use awk to make an obscenely large first column so that the description is so far to the right it's essentially hidden, and then pipe to `fzf -e --preview='echo {2..}' --preview-window='wrap' --no-hscroll`:

```sh
awk -F$'\t' '{printf "%-500s %s\n", $1,$2}' ./html_elements.txt |
fzf -e --preview='echo {2..}' --preview-window='wrap' --no-hscroll |
awk '{print $1}
```

For this use case I highly recommend using `-e` for exact searches, because otherwise you will probably be confused by what turns up in the results since the preview window doesn't show the search highlighting. Search for 'bold' and 'b' and 'strong' show up in the results.
