### ISSUE TITLE
Is there another way to get the current index in preview, other than with the inflexible {n}?

### ISSUE THREAD

**Issue by levihb** [junegunn/fzf#1952]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have two arrays in bash, one which I want to send to fzf to display (let's call it desc), then the other which I want to display in the preview window (let's call it prev). My original plan was to do something simple like:

    --preview="printf %s ${prev[{n}]}"

But that gives a bash syntax error. Changing the double quotes to single quotes:

    --preview='printf %s ${prev[{n}]}'

But this just results in nothing showing up. I even tried:

    --preview='n={n}; printf %s ${prev[n]}'

But again it doesn't show anything up.

I'm loading the data from a file, so I then figured instead I could just sed the right line, then use that, but unfortunately:

    --preview="sed '{n}q;d' the_file.csv"

But because lines start at 1, this again leaves me off by 1. This wouldn't be a problem, but I can't manipulate {n} at all, it's really inflexible. Eventually I came up with this hacky workaround:

```bash
prev () {
    line=$(($1 + 1))
    printf %s "$(sed "${line}q;d" the_file.csv)"
}

export -f prev

... --preview="prev {n}"
```

When I found this workaround I tried to go back to originally passing in the array I already have, but still came across even more problems with that, so have settled on this for now.

Could we instead have a more flexible way to access variables like {n}? Why not just have it in a variable, e.g. FZF_N, that the preview function can then access? Because as it is, a ton of functionality is limited. Is there a reason?

**Comment by junegunn** [comment]
The way `{n}` (or `{+n}`, `{+fn}`) works is consistent with the other placeholder expressions and I don't want to introduce a different mechanism for this particular use case. Setting a new environment variable just for `{n}` doesn't provide much value because you can easily do the same with `--preview 'FZF_N={n}; ...'` and it's not easy to provide variables for the other placeholders. (e.g. How are we going to name an environment variable for `{+f..-3}` expression?)

> Eventually I came up with this hacky workaround

It doesn't look too bad to me even when compared to the case where FZF_N is provided.

```sh
fzf --preview 'n={n}; sed "$((n + 1))q;d" the_file.csv'

fzf --preview 'sed "$((FZF_N + 1))q;d" the_file.csv'
```
