### ISSUE TITLE
An option to score camelcase higher than underscore 

### ISSUE THREAD

**Issue by westandskif** [junegunn/fzf#1965]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Hello!
I have a question: is it possible to introduce a setting to score `FactoringDailyOrder` higher than underscored ones? Please see the example below:
```
FirstSecondThird
first_second_third_convert
first_second_third_query
831/151340

Tags> firsecth
```
Here I'm searching tags (Python project) and it would be great to pass an option to FZF to score classes higher than class variables.

**Comment by junegunn** [comment]
No, I'm not interested in add customization options. The ranking system is already quite complex and I don't want to make it even harder to grasp with different combinations of customization rules. But fzf is a free open source project, so feel free to fork it and change it to your needs.

The example you gave above is an unfortunate one because you would have better results if the search term was one of
- `fst`
- `first`
- `fist`
- `FST`
- or just `F` (uppercase)
