### ISSUE TITLE
Can this be used with vim autocompletion ?

### ISSUE THREAD

**Issue by mayuroks** [junegunn/fzf#199]
I am writing a python script and I used Jedi. So when the auto completion is triggered, I see a huge list of possible autocompletions. Can fzf vim plugin help me fuzzy search / select through that huge list ?

**Comment by junegunn** [comment]
Yes it's possible, though I'm not sure if it's better than using YCM or neocomplete (I don't have enough experience with either).

The following example will give you the idea.
```vim
function! s:fzf_insert(data)
  execute 'normal!' (empty(s:fzf_query) ? 'a' : 'ciW')."\<C-R>=a:data\<CR>"
  startinsert!
endfunction

function! s:fzf_words(query)
  let s:fzf_query = a:query
  let matches = fzf#run({
  \ 'source':  'cat /usr/share/dict/words',
  \ 'sink':    function('s:fzf_insert'),
  \ 'options': '--no-multi --query='.escape(a:query, "'"),
  \ 'down':    '40%'
  \ })
endfunction

inoremap <silent> <C-X><C-W> <C-o>:call <SID>fzf_words(expand('<cWORD>'))<CR>
```

(I just realized that `a:query` cannot contain `"` even in escaped form due to a bug/limitation in `fzf-tmux` script. :confused:)
