### ISSUE TITLE
Optionally disable number line

### ISSUE THREAD

**Issue by jebaum** [junegunn/fzf#202]
Personally I find that I almost never look at the line containing the number of items fzf is searching and the number currently matched (and occasionally the spinner), especially when I'm using fzf with vim/nvim. It would be nice to be able to optionally disable printing this and save a line, which on smaller screens can make a difference. Could an option like `--no-info` be implemented?

**Comment by junegunn** [comment]
Thanks for the suggestion. But I don't think saving a line would make a big difference and would rather not add yet another option which I don't think will be widely popular. You can easily increase the height of `:FZF` split with `g:fzf_height` (default: `40%`) or you can just use `:FZF!` on smaller screens. Also, since the info line shows the number of selected items when `--multi` option is set or if sorting is enabled when `--toggle-sort` option is used, it can be confusing to completely hide it. Instead I tried placing the numbers after the query on the last line, but I didn't like that how it moves along as I type in more characters.

**Comment by junegunn** [comment]
Added `--inline-info` option, will be released with 0.9.11.

**Comment by junegunn** [comment]
```vim
if has('nvim')
  let $FZF_DEFAULT_OPTS = $FZF_DEFAULT_OPTS.' --inline-info'
endif
```

**Comment by noahfrederick** [comment]
@junegunn 
Just chiming in to say I like the new `--inline-info` UI a lot.

**Comment by jebaum** [comment]
agreed, @junegunn has an impressive history of listening to suggestions and improving them. great work as always

**Comment by junegunn** [comment]
Thanks, I wasn't perfectly sure if it looks okay (colors, separator, ...), but glad to hear that you like it.
