### ISSUE TITLE
[FR] Add option to change the shell used to execute preview commands

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2025]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
My default shell loads a lot of scripts and is not intended for throwaway. evals; I use `dash` for that. But I haven't found any option to make `fzf` use `dash` for `--preview` and not start a new default shell every time.

**Comment by NightMachinary** [comment]
I have noticed using `SHELL=x fzf ...` seems to work. Still, having an API for it is better, as it will be documented and not broken in future versions.

**Comment by junegunn** [comment]
> `SHELL=x fzf ...`

is the recommended way to do it if you really must. And it will never break in the future.

> My default shell loads a lot of scripts and is not intended for throwaway

fzf starts a command with a non-interactive shell i.e. `$SHELL -c ...`. instead of `$SHELL -ci ...`. So it should be fast if your shell is properly configured (not loading non-essential things in non-interactive mode).

```sh
> time bash -c :

real    0m0.004s
user    0m0.002s
sys     0m0.002s
> time bash -ci :

real    0m0.422s
user    0m0.324s
sys     0m0.127s
```

The same holds true for zsh. I don't use zsh so my .zshrc is empty but even if I put `sleep 1` in it, I can see that it doesn't affect a non-interactive shell.

```sh
> time zsh -c :

real    0m0.009s
user    0m0.003s
sys     0m0.005s
> time zsh -ci :

real    0m1.031s
user    0m0.010s
sys     0m0.016s
```

**Comment by JustinLovinger** [comment]
@junegunn How would you change the preview shell for the default keybindings? As far as I can tell, you can only change the options passed to `fzf`.
