### ISSUE TITLE
Command history file location?

### ISSUE THREAD

**Issue by mohitWrangler** [junegunn/fzf#2070]
Hi,

Where does fzf get the command history from? I use zsh shell.

**Comment by junegunn** [comment]
You might want to read the source code to find out:

https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh#L99-L116

**Comment by mohitWrangler** [comment]
I tried to look into it. But it is difficult to locate.

**Comment by dsimon28** [comment]
i believe (could be wrong though as im pretty new to scripting and im on bash) it would be your user history as defined by your .zshrc $HISTFILE or echo $HISTFILE for bash its ~/.bash_history on mine but i guess it depends on if your talking about _FZF history or the history file created by fzf --history (not sure if they're the same file or not) but id command out a rediclously long line in cmd line and see if it pops up in the history your looking for (after checking my rc files first for $HISTORY $HISTFILE $HIST**)

**Comment by imambungo** [comment]
In bash, fzf get the history from `history` command. If someone wondering why the content of `HISTFILE` (default to `~/.bash_history` in bash) is different from the output of `history`, it's because normally when we execute a command, that command is stored in "history list" in memory or RAM first and only get written to `HISTFILE` when the shell exits. Note that each shell session has its own "history list".

If you want your commands get written to `HISTFILE` right after they're executed, add this to your `~/.bashrc`:
```
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
```
For zsh users, [here](https://askubuntu.com/q/23630/356625).
