### ISSUE TITLE
[FR] group conditions

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2127]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Something in this spirit:

`(banana yellow) | (apple red)` should match `myBananas are yellowish` and `Reddish apples!`, but not `Such yellow apples ...`.

**Comment by junegunn** [comment]
Thanks for the suggestion but I'm not interested in extending the syntax.

I don't want the new users of fzf to spend more than a couple of minutes to fully learn the search syntax of fzf, which they can't use anywhere else. I strongly believe that fzf has become so popular because of its (ostensible) simplicity. Maybe it's too simple for certain use cases, it isn't for everything, but I'm okay with that. The right tool for the right job.

As the author of fzf, I use fzf all the time and most of the time I can select what I want with just a few keystrokes in a few seconds, so I'm not really motivated to implement more sophisticated search syntaxes.

I'm also going to close #2126
