### ISSUE TITLE
esc not exiting finded when inside tmux

### ISSUE THREAD

**Issue by blueray453** [junegunn/fzf#2132]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am using fzf version 0.20.0 with shell/key-bindings.zsh

My tmux version is 3.0a.

The problem is when I am inside tmux and use '^R', `fzf-history-widget` is triggered. However, escape does not exit the widget as mentioned in https://github.com/junegunn/fzf#using-the-finder (bullet point 2). I have to press ctrl+c. I am  ~sure that it is not caused by any keybinding of tmux.

It is also true for, `fzf-file-widget` and `fzf-cd-widget`. It does not exit if I am inside tmux and press escape.

**P. S.** When I am not inside tmux the esc key behave as expected.

**Comment by blueray453** [comment]
I just realized `fzf --preview 'cat {}'` , `fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'` etc also not working in tmux. 

Just to be clear, I am using `set-option -g mouse on` in tmux.

**Comment by blueray453** [comment]
The issue was caused by

```
# switch pane
bind -r -T root C-[ {
       select-pane -t :.+
}
bind -r -T root C-] {
        select-pane -t :.-
}
```
Not sure why.

**Comment by ScrumpyJack** [comment]
This happens to me but it's due to the --height option (regardless of tmux)
In zsh, if i have fzf --height set to anything other than 100%, then pressing ESC exits fzf but does not return to the zsh shell prompt.

Also, if i enter vim and run fzf (which has the default height set) and then exit vim and run fzf, the fzf height is set to what it was in vim.

The workaround is to export FZF_DEFAULT_OPTS="--height=100%"
