### ISSUE TITLE
[neovim] resize split according to number of options

### ISSUE THREAD

**Issue by Tranquility** [junegunn/fzf#216]
You said in this https://github.com/junegunn/fzf/issues/137#issuecomment-91735586 it might be possible to write an autocmd. I would try to implement this but have no idea how the autocmd could work.

**Comment by junegunn** [comment]
This is what I've tried:

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 85f576d..f07365c 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -287,6 +287,9 @@ function! s:execute_term(dict, command, temps)
   call s:pushd(a:dict)
 
   let fzf = { 'buf': bufnr('%'), 'dict': a:dict, 'temps': a:temps }
+  if has_key(a:dict, 'onchange')
+    let fzf.on_stdout = a:dict.onchange
+  endif
   function! fzf.on_exit(id, code)
     let tab = tabpagenr()
     execute 'bd!' self.buf
@@ -356,6 +359,17 @@ function! s:cmd_callback(lines) abort
   endfor
 endfunction
 
+function! s:cmd_onchange(...)
+  let matches = matchstr(getline(line('$') - 1), '[0-9]\+\ze/[0-9]\+')
+  if empty(matches)
+    return
+  endif
+  let height = min([&lines, str2nr(matches) + 4])
+    " + 2 should suffice, but for some reason Neovim silently closes the buffer
+    " when the height of the split becomes that small
+  execute 'resize' height
+endfunction
+
 function! s:cmd(bang, ...) abort
   let s:action = get(g:, 'fzf_action', s:default_action)
   let args = extend(['--expect='.join(keys(s:action), ',')], a:000)
@@ -366,7 +380,10 @@ function! s:cmd(bang, ...) abort
   if !a:bang
     let opts.down = get(g:, 'fzf_height', get(g:, 'fzf_tmux_height', s:default_height))
   endif
-  call fzf#run(extend({'options': join(args), 'sink*': function('<sid>cmd_callback')}, opts))
+  call fzf#run(extend({
+        \ 'options': join(args) . ' --no-inline-info --no-reverse',
+        \ 'onchange': function('<sid>cmd_onchange'),
+        \ 'sink*': function('<sid>cmd_callback')}, opts))
 endfunction
 
 command! -nargs=* -complete=dir -bang FZF call s:cmd(<bang>0, <f-args>)
```

- It looks like there's no autocmd fired when the content of the terminal buffer is updated (none of TextChanged, TextChangedI, CursorMoved, CursorMovedI, InsertCharPre works), so I tried with `on_stdout` callback of `termopen()`. I noticed that no data is passed to the callback (`a:000` is an empty array). Is this normal?
- The layout of fzf can differ depending on `--reverse` and `--inline-info` option, I explicitly disabled them. (While doing this, I realized that `--inline-info` was not immediately displayed on terminal resize, https://github.com/junegunn/fzf/commit/5d9107fd15a5bca3973f8206884ddfa66d47b923 is the fix)
- If you run the above code, you'll notice that the resize does not immediately happen. I could fix it by doing `redraw!` twice after `resize`, but then we see awful flickering of the screen.

@tarruda Is using `on_stdout` a right approach?

**Comment by Tranquility** [comment]
Thanks for working on this! I applied the patch, but the cmd_onchange function never gets executed.

**Comment by Tranquility** [comment]
@tarruda could you take a look at this?

**Comment by tarruda** [comment]
sorry I had missed this

> @tarruda Is using on_stdout a right approach?

If I understood correctly, you want the terminal window to have the same height as the number of available lines, right?  If so, then yes, you need to listen for stdout  events. 

I see that your comment is from April. Since that time, the internal architecture of how nvim handles asynchronous events changed dramatically, can you try it again and see if it works?

**Comment by Tranquility** [comment]
@tarruda thanks for your reply. It does kind of work but there is a problem. 
I created a minimal patch to show the probem:

```patch
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index fddab51..2f344e2 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -321,6 +321,9 @@ function! s:execute_term(dict, command, temps)
   call s:pushd(a:dict)
 
   let fzf = { 'buf': bufnr('%'), 'dict': a:dict, 'temps': a:temps, 'name': 'FZF' }
+  if has_key(a:dict, 'onchange')
+    let fzf.on_stdout = a:dict.onchange
+  endif
   let s:command = a:command
   function! fzf.on_exit(id, code)
     let pos = s:getpos()
@@ -427,6 +430,10 @@ function! s:cmd_callback(lines) abort
   endtry
 endfunction
 
+function! s:cmd_onchange(...)
+  sleep 1
+  echom getline(line('$') - 1)
+endfunction
+
 function! s:cmd(bang, ...) abort
   let s:action = get(g:, 'fzf_action', s:default_action)
   let args = extend(['--expect='.join(keys(s:action), ',')], a:000)
@@ -437,7 +444,10 @@ function! s:cmd(bang, ...) abort
   if !a:bang
     let opts.down = get(g:, 'fzf_height', get(g:, 'fzf_tmux_height', s:default_height))
   endif
-  call fzf#run(extend({'options': join(args), 'sink*': function('<sid>cmd_callback')}, opts))
+  call fzf#run(extend({
+        \ 'options': join(args) . ' --no-inline-info --no-reverse',
+        \ 'onchange': function('<sid>cmd_onchange'),
+        \ 'sink*': function('<sid>cmd_callback')}, opts))
 endfunction
 
 command! -nargs=* -complete=dir -bang FZF call s:cmd(<bang>0, <f-args>)
```

The echo now always shows the state of the line before the ui updated not after. So the on_change is triggered after I press a button but before the interface updates.

**Comment by tarruda** [comment]
@Tranquility Now I see the real issue: nvim does not update the terminal buffer as soon as it receives data. Here's a high-level overview of how it works:

- Nvim receives data from the pty
- Data is fed to libvterm, which immediately updates its internal screen
- At most 10ms later, nvim updates the terminal buffer to reflect libvterm internal screen.

In other words, nvim updates the buffer at most once each 10 milliseconds. This is done because updating buffers is more expensive than simply updating a virtual screen, and if we updated the buffer every time data is received, there could be serious performance problems with programs that send large bursts of output(It is not a premature optimization, I actually noticed these problems while working on neovim/neovim#2076).

A relatively simple workaround is to expose a separate API for accessing libvterm screen state directly. This would allow @junegunn patch to be adapted to use this API to get the number of matches instead of `getline(line('$') - 1)`.
