### ISSUE TITLE
feature request: let the user enter their own option

### ISSUE THREAD

**Issue by cherrry9** [junegunn/fzf#2180]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Here is the snippet from my script:
```
mp=$(find /mnt -type d 2>/dev/null | fzf --prompt "mount point: ")
```
Problem is that I can only select a mount point from this list that I piped to fzf. I would like to specify a custom option e.g ~/dev instead of a directory from /mnt. If I try to write my own entry and accept it, I just get nothing. Therefore, I propose to add a flag to fzf which allows us to pass a custom option with for example shift-enter.

**Comment by 0ion9** [comment]
Isn't this a 'I don't know how to script what I want' problem, not an fzf problem?

In fish this problem is simple, because you can just pipe the output of a block, eg `set mp (begin;find /mnt -type d 2>/dev/null; echo "~/dev"; end | fzf --prompt "mount point: ")
In bash, there are no 'plain' blocks, so you have to pipe the output of a flow-control statement into fzf, like `mp=$(if true; then find /mnt -type d 2>/dev/null; echo "~/dev"; fi | fzf --prompt "mount point: ")`

It sounds like you might also want to set the initial query to the value of the custom option . Use `--query ~/dev` for that.

**Comment by rayiik** [comment]
There’s also the FZF_DEFAULT_COMMAND variable which lets you set the command that is executed when fzf is run without any input also (only been using bash for 4 months) but not sure why your using if true I’m pretty sure you can just set the command then call with indirection or process substitution or you can a escape the command so it’s defined when called instead of when the script starts or even a heredoc should be able to do it as well(though if I’m wrong I’m still leaning and would love to know more) but I don’t really know what theZsh  equivalent are for those processes

**Comment by 0ion9** [comment]
Sure, those work too. 

I was actually wrong about bash / zsh not having a plain block construct, that's `()`.
`if true; then [..]; fi` is just a block which will always execute. With a bit of testing, it seems that `( find /mnt -type d 2>/dev/null; echo "~/dev") | fzf` works similarly.

**Comment by rayiik** [comment]
Ahh so another form of grouping commands essentially?

**Comment by rayiik** [comment]
this also works in bash but without spanwing a subshell (which would let you throw variables around
```bash
 { find /mnt -type d 2>/dev/null ; echo "~/dev";  } | fzf
```
and 
```bash
fzf0 < <(find /mnt -type d 2>/dev/null; echo "~/dev")
# also works with herestring (but not a here doc)
fzf <<< "$(find /mnt -type d 2>/dev/null; echo "~/dev")"
```

**Comment by junegunn** [comment]
@0ion9 @rayiik Thanks for the comments.

Also, note that you can use `--print-query` option to print out the user query before the selected item.

```sh
readarray -t lines < <(seq 10 | fzf --expect alt-enter --print-query)
  # ${lines[0]}: query string
  # ${lines[1]}: empty string or "alt-enter"
  # ${lines[2]}: selected item
```
