### ISSUE TITLE
fzf-tmux -p not work when FZF_DEFAULT_OPTS contains '\n'

### ISSUE THREAD

**Issue by mars90226** [junegunn/fzf#2205]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
tmux version: `tmux next-3.3`
OS version: `Ubuntu 18.04.4 LTS` in Windows 10 WSL
fzf version: `0.23.0 (dba14d2)`

fzf setting:
```
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="
--ansi
"
```
Execute `fzf-tmux -p` does nothing.
But if I change `FZF_DEFAULT_OPTS="--ansi"`, then `fzf-tmux -p` work perfectly.

**Comment by junegunn** [comment]
I can't reproduce the problem. It works as expected.

```sh
export FZF_DEFAULT_OPTS="
--reverse

--border

--margin 3

--prompt
'test> '
"
```

![image](https://user-images.githubusercontent.com/700826/95575847-68715100-0a6a-11eb-8d70-bd7e797d2e47.png)

(FWIW, it is not a good idea to put `--ansi` in your `FZF_DEFAULT_OPTS` because fzf will always do extra work to find ANSI escape sequences in the input even when they are not expected.)

**Comment by junegunn** [comment]
Does https://github.com/junegunn/fzf/commit/246b9f313085fac4c9c84cf8bf55cc8a8fc29482 help?

**Comment by mars90226** [comment]
Yes, 246b9f3 fix this bug. Thank you!
BTW, I use `--ansi` as an example. Because my `FZF_DEFAULT_OPTS` is really long. 😄
