### ISSUE TITLE
Lacking "move to the bottom result" binding + Issue with 'top' action with --tac

### ISSUE THREAD

**Issue by elig0n** [junegunn/fzf#2237]
- [X] I have searched through the existing issues
- [X] I have the latest version of fzf
- [X] I have read through the manual page (`man fzf`)

## Info

- OS
    - [X] Linux
- Shell
    - [X] zsh
    
## Problem / Steps to reproduce

1. There is a 'top' binding action but no 'bottom'. Is there a reason?
2. Home is not bound to top by default. Being a very common and non-conflicting bind I don't see why not have that in place by default.

3. With the '--tac' option 'top' binding behaves "accordingly" that is reversed but that's not necessarily what one would want! 
**Explanation:** I usually prefer a top binding with key like Home to pick the screen's topmost item _all the times_, even and especially when results are reversed and the prompt and first selection is at the bottom

**Comment by junegunn** [comment]
> There is a 'top' binding action but no 'bottom'. Is there a reason?

Because fzf puts the most relevant match on the "top" position. It doesn't make much sense to provide an option to move to the least relevant match. Note that you should understand "top" as "the *top*-rated match" instead of "the *top* of the screen", as the behavior depends on the `--layout`. With the default layout, "top" moves the pointer to the bottom of the screen where the most relevant match is. With `--layout=reverse`, it moves the pointer to the top of the screen.

> Home is not bound to top by default. 

Home key moves the cursor to the front of the query prompt. End key moves it back to the query prompt. This has been the default forever and we're not going to change it.
