### ISSUE TITLE
Option to place the cursor

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#224]
I would love an option to have the cursor under control at the start of `fzf`. Something like: Move the cursor to index/line number x; move cursor to the top or the bottom. Perhaps this is possible via the Emacs style keybindings, in which case it could be something like `--execute-key-at-start=`.

**Comment by junegunn** [comment]
Yeah, I also considered this, but the problem is that fzf interface is asynchronous. Let's suppose you want to start fzf with its (vertical) cursor on the 10th item, but fzf reads the input stream asynchronously, so it's possible that there aren't 10 items when fzf is started.

```sh
for i in $(seq 10); do echo $i; sleep 1; done | fzf
```

Maybe we could reduce the complexity by implicitly applying `--sync` option when this is used.

**Comment by junegunn** [comment]
And this will naturally lead to another options like `--print-line-number`, `--start-at-index`, or `--start-at-string`, etc. I know you need these stuff for building fzf-fs, which is by far the most sophisticated project based on fzf, and I think it's awesome and very creative, but we can't expand the features of fzf endlessly and should draw the line at some point. Maybe what you're trying to accomplish is simply beyond the scope of fzf.

**Comment by D630** [comment]
Ok,  I see. And yes, it seems to be a bottomless pit...
