### ISSUE TITLE
Command failed fd type -f

### ISSUE THREAD

**Issue by lioaslan** [junegunn/fzf#2257]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
## Step to procedure
- `sudo apt-get update`
- `sudo apt-get upgrade`
-  `fzf`
A few days ago, everything looked good but this error has appeared this morning
## Environment
- OS: Linux Mint 20 Cinnamon
- fzf: 0.20.0
- fd: 7.4.0
- neovim: 0.4.3
## `.zshrc`
```
export ZSH="/home/leo/.oh-my-zsh"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias fd=fdfind

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
```
## Image
![image](https://user-images.githubusercontent.com/24852182/99779152-395cfd80-2b47-11eb-8085-d86efad04cde.png)

**Comment by lioaslan** [comment]
I have just updated step to procedure and result of commands
![image](https://user-images.githubusercontent.com/24852182/99779740-1252fb80-2b48-11eb-979c-176764c827dd.png)

**Comment by junegunn** [comment]
An alias is not exported to the subshell, try using the original `fdfind` instead of its alias.

**Comment by rayiik** [comment]
Hey, one question in that regard why wouldn't an alias be exported to the sub-shell i thought the sub-shell (unless explicitly set not to) inherited the property of the working environment im only wondering because for me using wsl kali and regular arch and Ubuntu-studio (both with bash and zsh) the aliases ran successfully  the only thing different was i want using oh-my-zsh and my aliases is sourced in my global rc file.  (thinking the latter might be why it works as i don't always require interactive shell for access to global rc files if they contain functions  i need in them, is it because then sub-shell executes it loads my rc then sources my aliases? just asking because it will change how i structure some of my scripts for compatibility).
