### ISSUE TITLE
C-w behavior in FZF window

### ISSUE THREAD

**Issue by maxless** [junegunn/fzf#2275]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

I've been using an old version of FZF on my Ubuntu virtualbox and got used to the C-w deleting everything I entered when I made a mistake. I've moved on to WSL2 and upgraded the FZF plugin and now pressing C-w results in "E994: Not allowed in a popup window". Is there any way for restoring the old behavior? Or, alternatively, what's the hotkey for clearing the entered text?  C-w works fine in insert mode as before.

**Comment by junegunn** [comment]
> upgraded the FZF plugin

Do you have the latest version of it? https://github.com/junegunn/fzf/commit/8b71fea5dc469b5f996fa2823f53f3b1d9b084ae already fixed the issue.

**Comment by maxless** [comment]
Ah, I see the problem. I only updated the fzf.vim repo in vundle dir, then got confused and created the issue in the wrong repo. Though that begs the question, why is the fzf.vim file in the main fzf repo instead of separate fzf.vim?

**Comment by junegunn** [comment]
Because not everyone needs all the commands in fzf.vim, and some may even prefer alternative implementations such as https://github.com/yuki-ycino/fzf-preview.vim.

The Vim plugin in this main repository provides [the basic functions](https://github.com/junegunn/fzf/blob/master/README-VIM.md) for building custom commands using fzf. Maybe it's easier to understand if you see the main fzf plugin as the "library" and fzf.vim as "a sample application" built using the library.

**Comment by maxless** [comment]
Okay, I see your point.
