### ISSUE TITLE
FZF very slow on mounted NTFS drives

### ISSUE THREAD

**Issue by medwatt** [junegunn/fzf#2330]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When running `:Files ~/`, it is considerably faster than when running `:Files /media/user/Local Disk D/` even though they have a comparable number of files. The D drive is formatted with NTFS, whereas the Linux OS is on ext4. I also tried this on another mounted NTFS drive and it was equally slow despite having even less files. I don't understand why there is such a difference in speed. On windows, FZF performance on the D drive is lightning fast.

I recording a [screencast](https://streamable.com/4k8dt0) to demonstrate the issue.

**Comment by junegunn** [comment]
Since fzf is merely a text filter, it delegates the file system scanning to an external problem.
By default, we use [find command](https://github.com/junegunn/fzf/blob/32c493e994288f63c2ceec1dbeaadc5de7399552/src/constants.go#L61) which should be available on most systems, but you can use any command by setting `$FZF_DEFAULT_COMMAND`.

* https://github.com/junegunn/fzf#environment-variables
* https://github.com/junegunn/fzf#respecting-gitignore

So it looks like find is not performing well with the drive? You might want to test if other programs (such as `fd`) give better results.

**Comment by medwatt** [comment]
@junegunn thanks for your reply. I just tried `fd`. It is indeed faster than before. But there's one issue that I don't seem to understand. For example, running `:Files ~/` for the first time actually takes some time. But on subsequent runs, it is instantaneous. It's as if some caching is done. However, running `Files` on the D drive always runs like it's the first time I am running it on the D drive. Any idea why this is the case ?

**Comment by junegunn** [comment]
fzf doesn't implement any caching mechanism that extends beyond the span of its lifetime. It's probably your OS or disk controller that is caching the stuff.
