### ISSUE TITLE
ripgrep preview window ignores `down` value of --preview-window parameter (still displayed as horizontal split)

### ISSUE THREAD

**Issue by evdoks** [junegunn/fzf#2378]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am using FZF as a vim plugin via fzf.vim and have the following inconsistencies in the layouts of preview windows for FZF and ripgrep that are displayed using the following config in .vimrc:

```
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
let $FZF_DEFAULT_OPTS="--ansi --preview-window 'down:75%' --layout reverse --margin=1,4 --preview 'bat --color=always --style=header,grid --line-range :300 {}'"
```

Here is horizontally split  preview window of FZF (the desired behavior configured via `down:75%` parameter for ` --preview-window`):
<img width="864" alt="Screenshot 2021-03-04 at 11 39 57" src="https://user-images.githubusercontent.com/1532773/109951763-63919000-7cde-11eb-9c00-d67fd1a68943.png">

Here is a vertically split preview window of ripgrep (in spite of `down:75%` parameter for ` --preview-window`):
<img width="863" alt="Screenshot 2021-03-04 at 11 44 02" src="https://user-images.githubusercontent.com/1532773/109952292-f6322f00-7cde-11eb-9d7f-6206f5154182.png">

**Expected behavior:** ripgrep preview is displayed as a horizontal split (similar to FZF).

**Comment by junegunn** [comment]
This is a conflict between [`g:fzf_preview_window`](https://github.com/junegunn/fzf.vim#preview-window) and `$FZF_DEFAULT_OPTS`.

It is documented that when `g:fzf_preview_window` is not defined, `--preview-window right:50%` will be the default option used for the commands in this project.

I can make them respect the value in `$FZF_DEFAULT_OPTS`, but it will affect the users who have `--preview-window hidden` in their `$FZF_DEFAULT_OPTS` but still expect the preview window to be visible inside Vim because they didn't have `g:fzf_preview_window` defined.

**Comment by junegunn** [comment]
FWIW, I don't recommend putting preview options in your `$FZF_DEFAULT_OPTS`.

See https://github.com/junegunn/fzf#preview-window

> Since fzf is a general-purpose text filter rather than a file finder, it is not a good idea to add --preview option to your $FZF_DEFAULT_OPTS.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim/commit/711fb41e39e2ad3abec1ec9720782acbac6fb6b4

**Comment by evdoks** [comment]
Thanks a lot! This resolves the issue.
