### ISSUE TITLE
custom history outputs instead of letting me re-run the command

### ISSUE THREAD

**Issue by gingerlime** [junegunn/fzf#2402]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

This is probably a noob thing, but I'm at a bit of a loss here...

I have this snippet in my .bashrc

```shell
# source: https://news.ycombinator.com/item?id=11806748
HISTFILE="${HOME}/.history/$(date -u +%Y-%m-%d)_${HOSTNAME}_$$"; export HISTFILE
__fzf_history__() {
  sift --no-color -e "^[^#]" --files "*_${HOSTNAME}_*" -N --no-filename $HOME/.history | sort | uniq -c | sort -n | $(__fzfcmd) +s --tac +m -n1..,.. --tiebreak=index --toggle-sort=ctrl-r | sed "s/ *[0-9]* *//"
}
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
```

This worked great with an older version of fzf (commit 5d16b288698ecec96080a5d576521d92550e78fd), but somehow breaks when I pull master.

When it used to work, I could hit CTRL+R, see a list of the history items, hit enter on one of them, and the command would appear ready for me to modify or execute it.

With master, it works the same, but instead of putting the command in the prompt, it outputs it, and I get an empty prompt.

I did a `git bisect` and it looks like [this commit](7c447bbdc7adb1fe0c848e171780f68cacf3e80e) breaks things for me.

The odd thing is that even with the older version that "works", if I manually run `__fzf_history__` then it behaves like CTRL+R works in master... So in a way, I'm not even sure how it worked in the first place?

Hope I was able to describe things clearly. It's probably some very basic bash thing that escapes me? would appreciate any pointers/help.

**Comment by junegunn** [comment]
Hi, the function wasn't really designed to be overridden, and your trick stopped working when we changed the implementation. For now, you can try something like this, modifying `READLINE_LINE` and `READLINE_POINT`:

```sh
__fzf_history__() {
  local selected
  selected=$(seq 10 | fzf --height 50% --reverse)
  READLINE_LINE=$selected
  READLINE_POINT=10000
}
```

But please keep in mind that there is no guarantee that this will still work in the future. You might want to learn how to define custom key bindings from scratch instead of hacking the fzf implementation.

**Comment by gingerlime** [comment]
Thanks @junegunn ! I will give it a try... I just borrowed this code from someone else. What's the "proper" way of achieving this though? or more generally, how can I use fzf so the output is made available on the prompt to then change or hit enter to run?

**Comment by junegunn** [comment]
>  how can I customize the fzf history without overriding it?

Well, you can't. You may configure fzf options via `$FZF_CTRL_R_OPTS` but that's about it, there is no option that allows you to customize the execution model of the current implementation.

> more generally, how can I use fzf so the output is made available on the prompt to then change or hit enter to run? 

You'll have to read the code in this repository and learn how it's done, and you'll be able to write your own stuff. It won't be hard.

**Comment by gingerlime** [comment]
> You'll have to read the code in this repository, learn how it's done, and you'll be able to write your own stuff. It won't be hard.

I wouldn't ask if it wasn't hard for me to figure it out... RTFM (or RTF Code) then. I appreciate you taking the time to look into this.

**Comment by junegunn** [comment]
This is the current code for CTRL-R:

```sh
__fzf_history__() {
  local output
  output=$(
    builtin fc -lnr -2147483648 |
      last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |
      FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort,ctrl-z:ignore $FZF_CTRL_R_OPTS +m --read0" $(__fzfcmd) --query "$READLINE_LINE"
  ) || return
  READLINE_LINE=${output#*$'\t'}
  if [ -z "$READLINE_POINT" ]; then
    echo "$READLINE_LINE"
  else
    READLINE_POINT=0x7fffffff
  fi
}

bind -m emacs-standard -x '"\C-r": __fzf_history__'
bind -m vi-comman`d -x '"\C-r": __fzf_history__'
bind -m vi-insert -x '"\C-r": __fzf_history__'
```

The function is pretty simple and short so I don't think it's really worth it to add more configuration variables.

**Comment by gingerlime** [comment]
Thank you @junegunn. Yeah, I was able to find it, but can't say that it's easy for me to digest. There are a bunch of things mixed-in that somehow are hard for me to unpack. The READLINE stuff in particular doesn't click for me, plus the various options, `builtin fc -lnr ...` the perl stuff etc ...

I understand the reasoning not to add too many configuration options. I'm wondering however if it's somehow possible to split the input and output aspects of history? i.e. some kind of "get_history" function (that can perhaps get overwritten), with a "handle_output" part that handles the fzf aspects of fuzzy-finding results, selecting them and making them available to the command line if it makes sense?

I apologize if this sounds too naive, or shows my lack of bash, fzf expertise, but just something that conceptually I hope can make things more composable and easier to customize? totally understand if you're not interested changing things there, and thanks again for your help.

**Comment by junegunn** [comment]
I gave you a simplified version of it in the above comment to help you understand the structure of the code.

https://github.com/junegunn/fzf/issues/2402#issuecomment-806296915

But let me repeat it here with a slight modification so that it works with an actual command history (rather than `seq 10`)

```sh
__fzf_history__() {
  local selected
  selected=$(history | fzf --height 50% --reverse --tac --query "$READLINE_LINE" | sed 's/^[0-9 ]*//')
  READLINE_LINE=$selected
  READLINE_POINT=10000
}
```

It's pretty simple, right? You may not be familiar with `READLINE` variables, but the names are pretty straightforward and you can easily look them up on Google. So that's basically it. Now you can build your own version starting from here, just by changing the `selected=$(...)` part.

If you want to learn how we ended up with a much more complicated command than `history | fzf ...`, I suggest that you `git blame` the line and see how it evolved through the time.

- 7c447bbdc7adb1fe0c848e171780f68cacf3e80e
- 5cae8ea733e8663eae96480b5e6d4c94afcdb3bd
- 18261fe31cf1270f9aa783f99bbdbca343f89479

The command has become quite complicated, but the code structure still remains the same.

So, let's say we are going to support an arbitrary command for getting the command history. Then with the current code, we have to document that the command should follow certain rules.
1. Entry delimiter must be `\0`, rather than `\n` to support multi-line commands
2. Each entry should follow the form `LINENO\tCOMMAND`

Inevitably, people will ignore the instruction and start asking here why their `FZF_CTRL_R_COMMAND`s are not working as expected. And I'm not sure if all the trouble is worth it. Few users actually want to customize the command (especially when the current implementation efficiently removes the duplicates and supports multi-line commands), I would just tell them to write their own version, rather than to rely on a configuration variable with certain limitations.

Adding a variable also increases the maintenance burden. I have to make sure that it works identically across three different shells (bash, zsh, and fish), and I also have to make sure that I don't break anything whenever I want to change or update the code. It's tiring and it sometimes makes me want to stop maintaining all these things 😄

**Comment by gingerlime** [comment]
> It's tiring and it sometimes makes me want to stop maintaining all these things 😄

Please don't give up! fzf is awesome 🥇 

I totally got how to use it from your `seq 10` example and it works perfectly. I was just commenting primarily about your point about `__fzf_history__` not meant to be overridden, when this is the only choice I had ... you also mention using more variables as an option to make it configurable. I just thought that rather than adding variables, breaking down into small functions, and letting users override a smaller portion might be a way to simplify... 

I totally understand your point though, and the problem with the various "rules" involved as you described. I can see where my thinking breaks.

In any case, thanks again for your patience and great effort going into explaining things. I sincerely appreciate it, and also hope that this conversation is useful in future, if anyone else bumps into it.
