### ISSUE TITLE
preview switching is slow when doing partial rendering

### ISSUE THREAD

**Issue by AskMeAgain** [junegunn/fzf#2417]
Hi,

- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

```
dl() {
  local cid
  cid=$(docker ps -a --format "table {{.ID}} \t{{.Image}}\t{{.Status}}\t{{.Ports}}" \
  | sed 1d | fzf --height='70%' --header="Select Container for logs" \
  --preview 'for i in $(seq 100000); do
                        printf "\033[2J"
                        docker logs $(echo {} | cut -d " " -f1) -n $FZF_PREVIEW_LINES
                        sleep 1
                      done' \
  --preview-window follow:50%:down:rounded:nowrap: -1 -q "$1" | awk '{print $1}')

  [ -n "$cid" ] && docker logs "$cid" -f
}
```

this shows all docker containers in a fzf context menu, and piping the docker logs to the preview window and refreshing the logs continuously. This is super handy, but unfortunately it is super slow when switching between containers:. There is a delay of 1 second (this is not influenced by the sleep command. I tried 100 and 0.01 seconds, but no difference). 

Just doing docker logs $id in the preview is super fast and instant, but using the loop it is super slow. Why is that? Can this be improved via bash magic?

**Comment by junegunn** [comment]
The delay comes from two places.

### The minor one: Delay of the initial rendering
https://github.com/junegunn/fzf/blob/764316a53d0eb60b315f0bbcd513de58ed57a876/src/constants.go#L27
https://github.com/junegunn/fzf/blob/764316a53d0eb60b315f0bbcd513de58ed57a876/src/terminal.go#L1974-L1975

Here we have an assumption that most preview programs finish within 100ms. So I have made the renderer wait 100ms before rendering the initial chunk of the output, hoping that the program finishes within that amount of time, so we don't have to render a partial result only to immediately replace it with the full result. So you'll see 100ms rendering delay if you're running long-running preview programs.

### The big one: Cancelling delay

https://github.com/junegunn/fzf/blob/764316a53d0eb60b315f0bbcd513de58ed57a876/src/constants.go#L26

When the focus has changed, we don't immediately kill the running preview process. Instead, we wait 500ms before killing it. 

[This comment](https://github.com/junegunn/fzf/issues/1383#issuecomment-424957654) explains why I decided to do that. (Note that it's an old comment so some technical details are inaccurate.)

```sh
# Hold down CTRL-N / CTRL-P; preview window will be updated every 500ms
fzf --preview 'sleep 0.3; bat {}'
```

If we remove the 500ms delay, the preview window will be always empty because every preview process fails to yield any result.

### Enhancement: Conditionally removing the big delay

I think we can improve the situation by removing the canceling delay if the preview process already yielded some output. Here is a PoC patch, and it seems to work well. The minor delay is still there, but I don't think we should remove that because 1. it's short, 2. it's desirable for normal short-lived preview processes, 3. and it prevents starting and killing numerous processes.

```diff
diff --git a/src/terminal.go b/src/terminal.go
index 59851a0..2edfff7 100644
--- a/src/terminal.go
+++ b/src/terminal.go
@@ -1968,6 +1968,7 @@ func (t *Terminal) Loop() {
 						}()
 
 						// Goroutine 2 periodically requests rendering
+						rendered := util.NewAtomicBool(false)
 						go func(version int64) {
 							lines := []string{}
 							spinner := makeSpinner(t.unicode)
@@ -1982,6 +1983,7 @@ func (t *Terminal) Loop() {
 										if spinnerIndex >= 0 {
 											spin := spinner[spinnerIndex%len(spinner)]
 											t.reqBox.Set(reqPreviewDisplay, previewResult{version, lines, offset, spin})
+											rendered.Set(true)
 											offset = -1
 										}
 										spinnerIndex++
@@ -2001,6 +2003,7 @@ func (t *Terminal) Loop() {
 									}
 									if err != nil {
 										t.reqBox.Set(reqPreviewDisplay, previewResult{version, lines, offset, ""})
+										rendered.Set(true)
 										break Loop
 									}
 								}
@@ -2022,7 +2025,11 @@ func (t *Terminal) Loop() {
 										util.KillCommand(cmd)
 										t.eventBox.Set(EvtQuit, code)
 									} else {
-										timer := time.NewTimer(previewCancelWait)
+										delay := previewCancelWait
+										if rendered.Get() {
+											delay = 0
+										}
+										timer := time.NewTimer(delay)
 										select {
 										case <-timer.C:
 											util.KillCommand(cmd)
```

**Comment by AskMeAgain** [comment]
Thanks for the answer!

When can we expect this change? 

PS: a handy preview flag which would also be nice would be something like: --preview-repeat, where the preview command will be executed continously via this flag. This way we dont need to write "ugly" while loops and can keep the bash foo pretty minimal.

But anyway thanks for this awesome tool

**Comment by junegunn** [comment]
Patch merged to master. I'll think about your suggestion. Thanks.
