### ISSUE TITLE
[Feature] execute preview function in scripting modes

### ISSUE THREAD

**Issue by PatrickF1** [junegunn/fzf#2442]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish
    
## Problem / Steps to reproduce
Hi, I am a fzf plugin developer (https://github.com/PatrickF1/fzf.fish). Thank you for making this binary that makes my plugin possible! 

One issue I'm running into as I develop my plugin is automating the tests. I've been able to automate most of my plugin through the scripting options. The current scripting options allow me to easily automate tests for what fzf will output given a certain query by automatically selecting something (or nothing) and quitting. However, my plugin makes extensive use of `--preview` and lately, I've been running into a few regressions where the preview actually doesn't work. I used to get by with a lot of manual tests but I'd really like to be able to just automate testing of the preview command.

The problem with testing the preview command is that the scripting modes don't cause the preview function to be executed if fzf automatically selects a match (e.g. for --filter, --select-1, and --exit-0). I verified this with the command `ls | fzf --preview="touch {}" --filter="Documents"` and checking the last updated timestamp on Documents. But if fzf doesn't automatically select a match, then the tests will hang.

So, I would like a new feature, potentially a flag such as `--always-execute-preview`, that can be paired with the scripting modes so I can run automated tests on preview commands. Thank you for considering it! I know it's a rare use case but it'd help out the fzf plugin ecosystem a ton!

**Comment by junegunn** [comment]
`--preview` is only for interactive mode and is implemented as such. Combining it with non-interactive options doesn't make much sense. You would instead do something like `ls | fzf --filter foo | xargs -n1 echo`. (FWIW, I never use `--filter` because it gives too many irrelevant false positives)

I understand that you're requesting this solely for testing purposes, but even if we have the option and your tests pass using it, you can't be 100% sure if the tested features in an interactive environment would properly work as expected. So I don't think changing the code structure (making preview available on non-interactive cases) to support this option is worth it.

I recommend that you consider writing proper UI tests by capturing the screen. The test code of fzf uses `tmux capture-pane` to achieve that. Maybe there are cleaner ways to do it, but I haven't checked.

https://github.com/junegunn/fzf/blob/master/test/test_go.rb#L1428-L1454

**Comment by PatrickF1** [comment]
Hi, thank you for the quick reply!

> --preview is only for interactive mode and is implemented as such.

Got it, I trust your judgement as fzf's creator and I understand the need to avoid adding product debt so I'm happy to find a work around myself. However, I do want to point out that the workarounds you provided won't work for me.

> You would instead do something like `ls | fzf --filter foo | xargs -n1 echo`

Unfortunately, this doesn't work because the my plugin passes in internal variables to `--preview` that aren't available to the shell outside of the plugin. [Here](https://github.com/PatrickF1/fzf.fish/blob/main/functions/__fzf_search_current_dir.fish#L19) is an example (the variable I am speaking of is `expanded_token`.

> The test code of fzf uses tmux capture-pane to achieve that.

This is a great idea! Unfortunately, it is a bit heavyweight for a plugin that is 100% shell code and would detract from potential open source authors who are already familiar with fish but not ruby. However, this is a very valid solution so I may go down this path if I become desperate. Thank you @junegunn! You are very wise and helpful and the state of fzf reflects it.

**Comment by junegunn** [comment]
> it is a bit heavyweight for a plugin that is 100% shell code and would detract from potential open source authors who are already familiar with fish but not ruby.

I agree that it's a bit of a hassle. Please note that you don't have to use Ruby here. You can use shell script to control tmux and capture its screens. I chose Ruby just because I'm familiar with it and I find it easier to write more complex test cases with it.

**Comment by PatrickF1** [comment]
Thanks Junegunn! That's a much easier investment to make then!
