### ISSUE TITLE
tail -f does not work properly in vim when used as source

### ISSUE THREAD

**Issue by yuki-yano** [junegunn/fzf#2481]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
- Editor
    - [x] Neovim
    
## Problem / Steps to reproduce

I'm trying to asynchronously generate a file behind the scenes to use as a source while running fzf in vim.
I want to use "tail -f" to read the files, but when I use tail -f with fzf on Vim, Sink doesn't work properly, probably because the process doesn't terminate.
Is there a workaround to get it to work correctly?

Shell
```
$ ls > ls.txt
```

(Neo)vim
```
:call fzf#run({ 'source':  'tail -f ls.txt', 'sink': "edit" })
```

**Comment by junegunn** [comment]
Well, that's before tail process doesn't terminate even when its stdout is broken. You can reproduce the problem in your shell like so

```sh
touch ls.txt
tail -f ls.txt | fzf
  # tail process doesn't finish
```

But according to https://unix.stackexchange.com/a/416162/62171, GNU version of tail, which you can install via `brew install coreutils`, properly handles the situation.

```sh
brew install coreutils
gtail -f ls.txt | fzf
```

I can confirm that it finishes shortly after fzf is closed.

---

Having said that, we can work around the problem by using process substitution instead of pipe.

```sh
fzf < <(tail -f ls.txt)
```

However, this only works on bash not on POSIX sh (`/bin/sh`), and the Vim plugin of fzf uses sh and pipe.

- https://github.com/junegunn/fzf/blob/4cd621e877cb3a8e44b12ba3a7ce58709862922f/plugin/fzf.vim#L442
- https://github.com/junegunn/fzf/blob/4cd621e877cb3a8e44b12ba3a7ce58709862922f/plugin/fzf.vim#L471

---

Similarly, to immediately kill the source process, `fzf#vim#grep` function of fzf.vim does this trick of temporarily changing `$FZF_DEFAULT_COMMAND`.

https://github.com/junegunn/fzf.vim/blob/a88311b222eb9f90fa9fa72292e61d15c6767866/autoload/fzf/vim.vim#L821-L827

But anyway, I'd love to see a better way of handling long-running input processes in Vim plugin so we don't have to do these things.

**Comment by junegunn** [comment]
🤔 

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index ee2ee90..39dd510 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -468,16 +468,17 @@ try
     let source = dict.source
     let type = type(source)
     if type == 1
-      let prefix = '( '.source.' )|'
+      let source_command = source
     elseif type == 3
       let temps.input = s:fzf_tempname()
       call writefile(source, temps.input)
-      let prefix = (s:is_win ? 'type ' : 'cat ').fzf#shellescape(temps.input).'|'
+      let source_command = (s:is_win ? 'type ' : 'cat ').fzf#shellescape(temps.input)
     else
       throw 'Invalid source type'
     endif
+    call remove(dict, 'source')
   else
-    let prefix = ''
+    let source_command = ''
   endif
 
   let prefer_tmux = get(g:, 'fzf_prefer_tmux', 0) || has_key(dict, 'tmux')
@@ -500,7 +501,11 @@ try
     let optstr .= ' --no-height'
   endif
   let optstr .= s:border_opt(get(dict, 'window', 0))
-  let command = prefix.(use_tmux ? s:fzf_tmux(dict) : fzf_exec).' '.optstr.' > '.temps.result
+  let prev_default_command = $FZF_DEFAULT_COMMAND
+  if len(source_command)
+    let $FZF_DEFAULT_COMMAND = source_command
+  endif
+  let command = (use_tmux ? s:fzf_tmux(dict) : fzf_exec).' '.optstr.' > '.temps.result
 
   if use_term
     return s:execute_term(dict, command, temps)
@@ -511,6 +516,9 @@ try
   call s:callback(dict, lines)
   return lines
 finally
+  if len(source_command) && len(prev_default_command)
+    let $FZF_DEFAULT_COMMAND = prev_default_command
+  endif
   let [&shell, &shellslash, &shellcmdflag, &shellxquote] = [shell, shellslash, shellcmdflag, shellxquote]
 endtry
 endfunction
```

**Comment by yuki-yano** [comment]
Thank you.
Is it possible to use the fzf vim plugin to support this in the near future?

**Comment by junegunn** [comment]
Can you help testing the patch in various environments and scenarios?

**Comment by yuki-yano** [comment]
I only have a Mac, but I think I can use Docker to try it on Ubuntu and other systems.

**Comment by junegunn** [comment]
Thanks. I'm not completely confident that the patch doesn't have any side effects (e.g. conflicts with other plugins) so I'm going to use this on my local machine for a few days and see if it's safe to merge to master.

**Comment by junegunn** [comment]
Turns out the above patch has a bug of keeping temporary FZF_DEFAULT_COMMAND if the variable was not defined.

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index ee2ee90..cbdceb5 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -465,19 +465,19 @@ try
   endif
 
   if has_key(dict, 'source')
-    let source = dict.source
+    let source = remove(dict, 'source')
     let type = type(source)
     if type == 1
-      let prefix = '( '.source.' )|'
+      let source_command = source
     elseif type == 3
       let temps.input = s:fzf_tempname()
       call writefile(source, temps.input)
-      let prefix = (s:is_win ? 'type ' : 'cat ').fzf#shellescape(temps.input).'|'
+      let source_command = (s:is_win ? 'type ' : 'cat ').fzf#shellescape(temps.input)
     else
       throw 'Invalid source type'
     endif
   else
-    let prefix = ''
+    let source_command = ''
   endif
 
   let prefer_tmux = get(g:, 'fzf_prefer_tmux', 0) || has_key(dict, 'tmux')
@@ -500,7 +500,11 @@ try
     let optstr .= ' --no-height'
   endif
   let optstr .= s:border_opt(get(dict, 'window', 0))
-  let command = prefix.(use_tmux ? s:fzf_tmux(dict) : fzf_exec).' '.optstr.' > '.temps.result
+  let prev_default_command = $FZF_DEFAULT_COMMAND
+  if len(source_command)
+    let $FZF_DEFAULT_COMMAND = source_command
+  endif
+  let command = (use_tmux ? s:fzf_tmux(dict) : fzf_exec).' '.optstr.' > '.temps.result
 
   if use_term
     return s:execute_term(dict, command, temps)
@@ -511,6 +515,13 @@ try
   call s:callback(dict, lines)
   return lines
 finally
+  if len(source_command)
+    if len(prev_default_command)
+      let $FZF_DEFAULT_COMMAND = prev_default_command
+    else
+      unlet $FZF_DEFAULT_COMMAND
+    endif
+  endif
   let [&shell, &shellslash, &shellcmdflag, &shellxquote] = [shell, shellslash, shellcmdflag, shellxquote]
 endtry
 endfunction
```

**Comment by WeixuanZ** [comment]
This seems to break [vimtex](https://github.com/lervag/vimtex)'s [`vimtex#fzf#run()`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/fzf.vim) with certain `fzf#run` options.

`vimtex#fzf#run()` uses the following
```vim
function! vimtex#fzf#run(...) abort
  let l:opts = extend({
      \ 'source': <sid>parse_toc(a:0 == 0 ? 'ctli' : a:1),
      \ 'sink': function('vimtex#fzf#open_selection'),
      \ 'options': "--ansi --with-nth 3.. --delimiter '\u2007'",
      \}, a:0 > 1 ? a:2 : {})

  call fzf#run(l:opts)
endfunction
```

E.g. `vimtex#fzf#run('ctli', {'left': '20%'})` now opens up an empty list. However, something like `vimtex#fzf#run('ctli', { 'window': { 'width': 0.9, 'height': 0.6 } })` works fine.

I don't know if this is a particular issue due to how vimtex implements the source function `parse_toc`, both of the above examples work before commit 7411da8 however. Could you provide some insights?
