### ISSUE TITLE
Add an option to select instantly when the search only finds one answer

### ISSUE THREAD

**Issue by lamdevhs** [junegunn/fzf#2494]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce
Hello, I wanted to ask if it were possible to add an option to enable the following behavior: when typing in the query field, if fzf encounters only one result (the filter returns only one entry), it gets selected immediately, and fzf exits, without needing the user to hit 'enter' to validate the selection. Dmenu for example has that option, in the shape of a patch, called 'instant' https://tools.suckless.org/dmenu/patches/instant/

To be clear this is different from the behavior of --select1, which solely checks if the *input* is comprised of a single entry/item. Here, even if the input were to be many items, when the user searches through those items, if the search results become depleted to the point when there is only one result left, that result would be immediately accepted and fzf would quit.

Originally when reading the man page, I actually thought that --select1 did what I am proposing it. I was overjoyed till I tested it and it ended up not working at all like I expected. On that front I feel like perhaps the man page should be reworded: "Automatically select the only match" to me sounds closer to the behavior I'm talking about here, though it depends on what the definition of 'match' is. Perhaps "Automatically select the only input item" might be more explicit, or something similar?

In some sense this option I'm proposing kind of subsumes --select1, I think, but also allows the behavior of 'automated acceptance' to be triggered during a search/filtering made by the user, and not just at the launch of the program.

I might consider trying to code that behavior myself and then ask for a pull, if you are not against the feature as an idea/concept but you would deem it low priority on the realization level.

**Comment by junegunn** [comment]
Looks like the documentation has room for improvement. Let me explain.

> "Automatically select the only match"

`--select-1` was designed to be used with `--query` (#27, #36) in the scripting context. If an initial `--query` is given, it behaves as such (when you don't pass a `--query`, that is same as passing an empty query (`--query ""`) which matches all items in the list, so the statement is still valid). We added the option not to start the UI in shell scripts, which would cause a quick flickering of the screen, when there's no need. Once the UI starts, the option is discarded. I put the option under "Scripting" section of the man page, but I guess that is not clear enough.

`--select-1` in interactive context was suggested in the past (see #459) but I rejected the idea because I think it doesn't go well with the idea of "fuzzy matching".

If you're looking for a terminal version of dmenu, you might want to take a look at https://github.com/p-gen/smenu. It may be a better choice than fzf for simple menus.
