### ISSUE TITLE
0.27.1 vim integration color & layout regression

### ISSUE THREAD

**Issue by joshingly** [junegunn/fzf#2501]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
The following FZF configuration results in different colors & layout in 0.27 and 0.27.1. 

0.27 (correct):
![0 27](https://user-images.githubusercontent.com/678570/119375223-2f47c300-bc80-11eb-9caf-33ddb5e5bedf.png)

0.27.1 (incorrect):
![0 27 1](https://user-images.githubusercontent.com/678570/119375249-366ed100-bc80-11eb-8abc-5033a2f57844.png)

Configuration:
```vim
set rtp+=/usr/local/opt/fzf
let g:fzf_layout = { 'down': '~20%' }
let g:fzf_action = {
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit'
\ }

let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Identifier'],
  \ 'fg+':     ['fg', 'White'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Constant'],
  \ 'info':    ['fg', 'White'],
  \ 'prompt':  ['fg', 'Constant'],
  \ 'pointer': ['fg', 'PreProc'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment']
\ }
```

**Comment by joshingly** [comment]
Disregard. Fixed by removing `let g:fzf_colors` and adding:

```vim
let g:terminal_ansi_colors = [
  \ '#073642', '#dc322f', '#859900', '#b58900',
  \ '#268bd2', '#d33682', '#2aa198', '#eee8d5',
  \ '#002b36', '#cb4b16', '#586e75', '#657b83',
  \ '#839496', '#6c71c4', '#93a1a1', '#fdf6e3'
\ ]
```

**Comment by junegunn** [comment]
Great to hear that you figured out how to configure the colors.

For those who run into the same problem: https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzf-inside-terminal-buffer

This is caused by https://github.com/junegunn/fzf/commit/85ae7459103c3aeef39383d8c8a4fbbdb9fb5f64, and I had to make this change for consistency. On regular Vim, you would see different colors depending on `g:fzf_layout`, because fzf would open with `--height` option if `down` layout is used, instead of using the built-in terminal emulator of Vim. Now fzf will always start in a terminal buffer inside Vim regardless of the layout setting.
