### ISSUE TITLE
Selectively disable `Ctrl-R` shell keybinding

### ISSUE THREAD

**Issue by bruno-** [junegunn/fzf#253]
Hi,
thanks for this great tool. I find the shell `ctrl-t` (recursive dir search) invaluable when working on a new project.

However, I'm finding the history search feature hard to get used to so I'd like to selectively disable that one for now. To do that I opened `/usr/local/Cellar/fzf/HEAD/shell/key-bindings.bash` and commented out the line that starts with `bind '"\C-r"`.

Is there a cleaner way to do this?
Thanks!

Here's the usage and configuration details:

- using fzf from shell only, bash 4.3
- OS X 10.10.3
- installed via `brew reinstall --HEAD fzf`

**Comment by junegunn** [comment]
How about rebinding the key to the original function after the script is sourced?

```sh
bind '"\C-r": reverse-search-history'
```

By the way, it's interesting to hear that you find ctrl-t more useful than ctrl-r, to me it's the opposite.

**Comment by bruno-** [comment]
Sorry for not responding to this earlier (while you were super quick to reply).

> How about rebinding the key to the original function after the script is sourced?

This seems a little bit dirty: overriding the override just to get the default back. But it's good to know I'm not missing something.

I guess this customization is a pretty rare request so I guess closing the issue is ok.

**Comment by OJFord** [comment]
@junegunn I just want to disable the 'cd to selection' binding because I hit it frequently accidentally, and never deliberately. I don't have an original function to override it to.

I agree that it's 'a little bit dirty' to override to an original just to stop the original being overwritten anyway.

**Comment by rayiik** [comment]
hey if you want to remove the keybinding on the ctrl r and keep the fzf ctrl skill but bound to a different key you could just modify the script for example mine is bound to ctrl-p
```bash
  bind -m emacs-standard -x '"\C-p": __fzf_history__'
  bind -m vi-command -x '"\C-p": __fzf_history__'
  bind -m vi-insert -x '"\C-p": __fzf_history__'
```
the file is called key-bindings.bash (on my system it's in /usr/share/fzf/) but take it copy it rename it at the bottom you'll find those 3 lines swap out the r with p or whatever you like  save and source from your bashrc/bash.bashrc/profile (make sure to rename it though so there's no chance of it being overwritten

**Comment by OJFord** [comment]
Thanks @rayiik, I realised some time between my comment and yours that the binding was coming from such a file (in my case for fish shell) - since I don't (deliberately) use any of the bindings, I simply removed it. Cheers.

**Comment by ds2606** [comment]
This does seem like dirty feature of an otherwise fantastic app. I'm manually removing the bindings in `keybindings.zsh`, but every time there's a new release homebrew re-inserts them, and I have to go in and remove them again. Seems like there should just some way to prevent making the bindings by default?

**Comment by rayiik** [comment]
@ds2606  yes when fzf installs it asks (depending on how you install it) if you want to enable bindings if you select yes it adds a line to your config .zshrc or global zsh file sourcing keybindings.sh remove that line and or source a custom fzf file i source ~/project/man-fzf-scripts/fzf/conf/.fzfrc which defines my default options my default command and sources my custom fzf bindings for custom fzf commands. on most systems these bindings are not enabled by default  if you look at the install script

```bash

version=0.30.0
auto_completion=
key_bindings=
update_config=2
shells="bash zsh fish"
prefix='~/.fzf'
prefix_expand=~/.fzf
fish_dir=${XDG_CONFIG_HOME:-$HOME/.config}/fish
```

lines 5-12 key_bindings is not set by default 
which can further be enforced (if your installer automatically enrolls you) with

```bash
    --[no-]key-bindings  # Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)
```

as you can see the fault is not with fzf but rather homebrew. if you are not given this option when installing i recommend downloading the source directly and building manually or using the install script provided.

**Comment by ds2606** [comment]
@rayiik The issue is more that the zsh widgets are bundled into the key-bindings.zsh file. 

This means that we can't source the widgets without sourcing the keybindings. If we want our own keybindings (e.g. I have `<C-f>` for he file finder, etc)  for those widgets, we need to deal with the shadowing issues discussed in this thread. The solution seems to be to refactor the widgets separately from the keybindings, and source them (the widgets, NOT the keybindings).

 I've done this refactoring manually, which is a pain since every time a new version is released the keybindings are re-mixed with the widget definitions.

**Comment by rayiik** [comment]
again as per my origonal replay take your keybinding.zsh rename it to ~/.fzf.zsh remove the bindings you dont want reconfigure fzf to not include bindings and source from zshrc, no overwrite no sourcing updated bindings left with your exclusive binding.

**Comment by neitsab** [comment]
To restore the default  `Ctrl+r` keybinding in **zsh**, I added the following after `source <(fzf --zsh)` in `~/.zshrc`:

    bindkey -M emacs '^R' history-search-backward

Here is an example demonstrating the conditional redefinition of ctrl+r to atuin-search widget when atuin is installed:

```zsh
## set up fzf key bindings and fuzzy completion if it is installed
if command -v fzf &>/dev/null; then
  source <(fzf --zsh)
  # set ctrl-r key binding to atuin search widget if it is installed
  if command -v atuin &>/dev/null; then
    bindkey -M emacs '^R' atuin-search
  fi
fi
```

This approach has the advantage to be stable across fzf updates.

**Comment by erik434** [comment]
Another option here for anyone interested in disabling the Ctrl-R keybind in bash (similar may work in other shells). Instead of running `eval "$(fzf --bash)"` in my .bashrc, I'm doing this:

```
fzf --bash | sed --regexp-extended 's|^([[:space:]]*)(bind .+\\C-r.+:.+)$|\1# REMOVED \2|' >~/.fzfrc
source ~/.fzfrc
```

That takes the latest official fzf setup script and just comments out any lines which bind Ctrl-R. I expect it should continue to work even as fzf makes updates, unless the bash mechanism to make keybinds changes, or fzf does something funky like split these across multiple lines, etc. (both unlikely?).

You could also just eval the modified script instead of saving it to a file first, but this way the sourced script is available to be examined in case something goes wrong.
