### ISSUE TITLE
Is there a way to change the style of the fuzzy completion?

### ISSUE THREAD

**Issue by m42e** [junegunn/fzf#254]
Hi,

is there something like a style file where I can change all the fuzzy completions to look the same.
I've setup a few shortcut commands, using fzf-tmux with a few options and I would like the fuzzy completion to behave just like them.

How can I do this?

Thanks a lot.

**Comment by junegunn** [comment]
`$FZF_DEFAULT_OPTS`. Does this answer your question?

**Comment by m42e** [comment]
theoretically yes, but somehow is seems not to work as expected.

I've set the following options:
```
FZF_DEFAULT_OPTS="-h 20% --multi --reverse"
```

but it still behaves as before

**Comment by m42e** [comment]
May this issue be related to the setup I use?
Cygwin with tmux on Windows.

**Comment by junegunn** [comment]
- This is a basic question, but did you `export` the variable?
- You may need to restart tmux session after adding the variable to your .bashrc or .zshrc
- Unfortunately, `-h 20%` is an option to `fzf-tmux` script and you can't put it in `$FZF_DEFAULT_OPTS`
    - I would simply define a custom shell function or alias which appends it to `fzf-tmux` like so
    ```sh
    alias fzf-tmux='\fzf-tmux -d 20%'
    ```
- (Alas, you're on Windows. Then you're running the old Ruby version instead of the new Go version.)

**Comment by m42e** [comment]
Ok, thanks a lot. It worked after restarting everything. Thanks for your patience and quick response.
