### ISSUE TITLE
Preview window: text spuriously sticks to the right margin

### ISSUE THREAD

**Issue by poetaman** [junegunn/fzf#2587]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce
At times while navigating the fzf items with preview window open makes some characters stick to the right margin of the preview window.

Steps:
1. Open Alacritty window or iTerm2 window.
2. Go to some directory with a lot of files to run fzf from
3. Open fzf with command ``fzf --preview='cat {}'``
4. Press and hold up/down arrow key to navigate till you see some characters sticking to the right margin.

Here's a video that shows the problem, keep an eye on the right margin of the preview window.

https://user-images.githubusercontent.com/71736629/129470894-ea588093-0457-4a8c-bc2e-aac56fed50a3.mp4

Tested on terminals: Alacritty, iTerm2.

**Comment by drewauff** [comment]
i think what your looking for is `--preview-window:right:55%`  the lower the % the closer to the file/dir list

**Comment by Delapouite** [comment]
I was able to reproduce the same artifacts on my Linux machine using Kitty as terminal.

As your video goes quite rapidly it was hard to identify what could be the source of this weird display issue.

So I `git clone` the Alacritty repository and went calmly over all candidates, starting from the root. It turns out that the culprit in this case is `alacritty/windows/alacritty.ico` which is the first binary file encountered with the default sorting. If you search for other binary files like with the query `png`, similar display bugs appear.

**Comment by junegunn** [comment]
This can happen when fzf incorrectly determines the width of a character. But I believe the problem is much less common since we updated the library for doing that.

Please leave a comment if you still have this problem.
