### ISSUE TITLE
optional buffering/stdin for change:reload commands (or using grep regex inside fzf)

### ISSUE THREAD

**Issue by jakobi** [junegunn/fzf#2628]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I think either I missed something (a cluebat please in this case),  or this is indeed a feature request to extend the rg-fzf and seq-fzf ideas to generic filtering shell commands.

I initially wondered about the 'failed command' I always got from e.g.
ls -l /etc/ho* | fzf --phony --bind 'change:reload:nl {q}' --query .
while your rg and seq examples would work perfectly.

I tracked this down to grep not seeing any input (and also not waiting for input). 

Workaround: 

I am currently using tempfiles as a workaround to teach the missing regex to fzf:

function fzfg { 
   typeset T rc;
   export T=$(mktemp /tmp/fzfgXXXXX); 
   cat > $T; 
   fzf --phony --bind 'change:reload:egrep {q} $T;:' --query ^ ${1:+"$@"} <$T; 
   rc=$?; 
   rm $T 2>/dev/null; 
   return $rc;
}

My feature request: 

As fzf already has a copy of stdin, could you add an option to pipe the already buffered copy to the executed command for say "change:reload"? This would avoid the need for another buffered copy in a tempfile and the usual issues with tempfiles.

Thx,
Peter

**Comment by jakobi** [comment]
Actually fzf is surprisingly usable (abusable) in a way I didn't expect:

The fzfg shell function also makes for really nice REPL for egrep, to interactively filter a fixed input until you've exactly obtained the REGEX against the input. When done, copy the REGEX to the script I'm writing; which made debugging the script (wrt edge cases) way faster.

Similarly, replace egrep by perl -lpe and speedup creating the perl expression for slightly-too-complex perl one-liners.

:).

**Comment by junegunn** [comment]
> Basically I wanted to just see the original input lines from stdin (e.g. -rw... /etc/hosts) prefixed with a number.

You would do

```sh
ls -l /etc/ho* | nl | fzf
```

> attempt to understand 'change:reload:COMMAND' and 'change:reloader:COMMAND {q}'.

I see. It seems to me that your confusion came from the term `reload`, it's actually more like `replace`; replace the input list with the output of a command.

> teach the missing regex to fzf

Interesting idea.

FWIW, fzf is very performant (you can use it with millions of items) because it caches the intermediate results while narrowing down the list. If the filtering is done by an external program, you lose the performance benefit of caching mechanism.

> That said: does it make sense for you to improve support of such uses of fzf: simplify this use case, so that tempfiles (and wrapping in a script or function) aren't required anymore?

fzf was designed to be an interactive filter with its own, simple yet effective, search syntax. I know many users (ab)use fzf to build interesting TUI applications, but even so, I want to keep it simple and avoid adding non-crucial features that go beyond the original purpose.
