### ISSUE TITLE
ENTER automatically selected the one where the pointer is when nothing toggled in `--multi`

### ISSUE THREAD

**Issue by cycool29** [junegunn/fzf#2667]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

My full fzf command:
```
echo "$app_list" | fzf  --height="50" --multi  --bind=space:toggle --bind=ctrl-a:toggle-all
```
### What I expected
I have a list of apps and I want user to choose at least one to continue. I set the keybind to let user toggle the app from the list using <kbd>SPACE</kbd>. If user didn't toggle anything using <kbd>SPACE</kbd> and pressed <kbd>ENTER</kbd>, just return nothing.

### What exactly happened
I have a list of apps and I want user to choose at least one to continue. I set the keybind to let user toggle the app from the list using <kbd>SPACE</kbd>. If user didn't toggle anything using <kbd>SPACE</kbd> and pressed <kbd>ENTER</kbd>, **fzf automatically selected the one where the pointer is**.

Does anyone knows any keybind action would do what I expected?

**Comment by junegunn** [comment]
That's how `--multi` was designed to work. Because in many cases, you don't want to hit two keys just to select a single item. You also don't want to know if you **have to** press two keys or a single enter key would suffice. And if you don't want to select any item, you can always press ESC or CTRL-C to terminate the program.

fzf may not be the best tool for simple "menu"s. There are alternatives you might want to check out.

* https://github.com/terkelg/prompts#multiselectmessage-choices-initial-max-hint-warn
* https://github.com/p-gen/smenu

**Comment by cycool29** [comment]
> fzf may not be the best tool for simple "menu"s. There are alternatives you might want to check out.
> 
> * https://github.com/terkelg/prompts#multiselectmessage-choices-initial-max-hint-warn
> * https://github.com/p-gen/smenu

Thanks for your suggestions. 
However, both of them seem not to work as I want. I found a [pure bash script](https://unix.stackexchange.com/a/673436) which did the trick. Anyway thanks for your help!
