### ISSUE TITLE
Use case: fuzzy bookmarks for your shell

### ISSUE THREAD

**Issue by dimonomid** [junegunn/fzf#267]
Hi Junegunn,
thanks again for this great tool.

I just want to share use case that I find extremely useful for me: I use fzf for shell bookmarks. I was looking for shell bookmarking tool for long time and I wasn't satisfied by all of the existing solutions I've found, so after I've came across your fzf, I've got simple yet useful idea: why not just to keep bookmark paths in single file, feed that file to fzf and cd to directory that has been selected. It looks like this:

![cdg demo](http://dmitryfrank.com/_media/articles/cdg_recorded.gif)

If you probably like to put some use cases on readme, here is a short article: [Fuzzy bookmarks for your shell](http://dmitryfrank.com/articles/shell_shortcuts). Maybe it's even worth to add special section to readme, like "use cases", and fill it with links to some articles? At least, I have another use case, which I plan to write about as well: I use fzf for GUI applications via xterm, I love that. Fzf is such a flexible tool! Thanks.

**Comment by balta2ar** [comment]
You might want to look at [z](https://github.com/rupa/z). After I followed advice from [wiki](https://github.com/junegunn/fzf/wiki/Examples) and integrated z with fzf, I can jump into directories almost immediately, plus I don't have to do manual bookkeeping, all the visited paths are saved and are easily filtered out if necessary.

**Comment by dimonomid** [comment]
Thanks, I will look into it. As to auto-saved visited paths, it sounds useful but it is separate feature, and it's not mutually exclusive with bookmarks. Personally I'd like to keep my manually-maintained bookmarks list anyway, to make it clear and concise.

**Comment by uvaes** [comment]
I had exactly the same idea! :) Fzf is great to navigate bookmarks! See https://github.com/uvaes/fzf-marks if interested.

**Comment by junegunn** [comment]
@dimonomid Thanks, I'm glad to hear that you find fzf useful :)
You're welcome to add the link to the article to the wiki page. And like @balta2ar suggested, I also recommend z. I use it all the time, it's especially awesome when integrated with fzf. Haha.

@uvaes That looks pretty handy, thanks for sharing. As for the release of the new version, I'm trying to take some time to test the new features since I've grown tired of finding out obvious bugs just after releasing a new version :tada: :frowning: :weary: You can download prerelease binaries from [here](https://github.com/junegunn/fzf-bin/releases) if you feel like trying out new features in advance.

**Comment by uvaes** [comment]
Thanks for the link! I'll try the new feature and let you know if I find any bug. :-)
