### ISSUE TITLE
neovim, macos, fzf list all files of my computer

### ISSUE THREAD

**Issue by wangjiatao** [junegunn/fzf#2738]
- [x] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I install the latest version neovim, then install fzf and coc.nvim
there are two issues in my nvim
1. if I paste the config of coc.nvim in the "init.vim", then open a new nvim tab, then input : FZF,  there is a window included all files of my computer.
2. if I install pdf preview plug with the plugin or coc.nvim, the same issuer will occur again. if I delete former two plugs or the coc.vim' s config, this issue will be corrected.

**Comment by junegunn** [comment]
> : FZF, there is a window included all files of my computer.

It's not clear what you mean by this sentence? Any screenshot?

**Comment by wangjiatao** [comment]
sorry, I am a newbie of neovim.

the problem screen pic is ![issue1](https://i.imgur.com/qBTxLB9.png)

I open the nvim in my user file, there are only few files ,but fzf list all files in my computer. 


the init.vim pic is ![init](https://i.imgur.com/MPhMgcO.png)

the Plugin pic is ![plugin](https://i.imgur.com/o561qKe.png)

thank you .

**Comment by DevAtDawn** [comment]
@wangjiatao

for the **:FZF & :Files** command in neovim, it will use the **FZF_DEFAULT_COMMAND** you have set in your **.bashrc / config.fish / .zshrc**

for example, if I always want fzf to start/search for files in the $HOME dir like yours I can do:
`export FZF_DEFAULT_COMMAND='fd --hidden --exclude .git . $HOME'`

but if I want it to only search from the current working dir: (similar to the FZF_CTRL_T_COMMAND)
`export FZF_DEFAULT_COMMAND='fd --color=always --hidden --exclude .git'
`
alternatively, you can pass in a path arg like ~/Documents when you run the :FZF command to specify the dir to search:
```
:FZF ~/Documents
:FZF .
```
then make a custom command/function or remap your FZF one:
`command FZFcwd :FZF .`
you can also try `:Files` which now uses fzf
`command! -bang ProjectFiles call fzf#vim#files('~/Documents', <bang>0)`

my nvim remaps:
```
nnoremap <silent> <Leader>fz :Files<CR> #search from pwd
nnoremap <silent> <Leader><Leader>fz :FZF ~<CR> #search from ~

```

so to fix this; in your init.vim you can add the below to override the :Files function:
`command! -bang Files call fzf#vim#files('.', <bang>0)
`
now when you call :Files it will only show/search the current directory for files, instead of using the FZF_DEFAULT_COMMAND/showing all files

**Comment by wangjiatao** [comment]
thank u!!! i will try it in your way.

**Comment by sayeefm0** [comment]
While reading issues I noticed this one - seems like this can be closed
