### ISSUE TITLE
toggle-sort does not seem to do anything

### ISSUE THREAD

**Issue by salmankhilji** [junegunn/fzf#2741]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I am not sure if the `toggle-sort` action is broken.  I am launching `fzf` like this, and CTRL-R does not sort the finder:

```
FZF_DEFAULT_COMMAND="echo -e 'c\na\nb'" fzf --height=5 --bind=ctrl-r:toggle-sort
```

```
$ fzf --version
0.29.0 (dc975e8)
```

**Comment by junegunn** [comment]
It's working as expected, try this:

```sh
seq 1000 | fzf --height=5 --bind=ctrl-r:toggle-sort --query 5
```

**Comment by salmankhilji** [comment]
I had completely misunderstood this option.  I thought this option sorted the entries in the finder, whereas, in reality, it sorts the filtered list.

Thank you for clarifying.

**Comment by Guang1234567** [comment]
Yes,  `toggle-sort` only works under the condition `query string is not empty and match some item`

**Comment by kbd** [comment]
> Yes, toggle-sort only works [if the] query string is not empty

Is there a way to sort the original list with a keybind? Wouldn't it make sense for `toggle-sort` to live-sort the currently shown list in all circumstances?

**Comment by LangLangBart** [comment]
> Is there a way to sort the original list with a keybind?

One idea would be using the `{+f}` placeholder, which is a temporary filename of the currently selected lines. These lines are then sorted, and the entire list is reloaded.

```bash
fzf --multi --bind 'ctrl-t:select-all+reload:sort --ignore-case {+f}'
```

---

If you want this sorting to occur every time you start fzf, consider using a `start` `EVENT` instead of a `KEYBINDING`. The `fzf` manpage explains it well.

```bash
man fzf | less --pattern 'AVAILABLE EVENTS'
# AVAILABLE EVENTS:
#       start
#             Triggered only once when fzf finder starts. Since  fzf  consumes
#             the input stream asynchronously, the input list is not available
#             unless you use --sync.
```

```bash
fzf  --multi --sync --bind 'start:select-all+reload:sort --ignore-case {+f}'
```

---

But if you do use an event, you could simply assign your `FZF_DEFAULT_COMMAND` to find your items
and sort them before they are ever seen by `fzf`. However, this might slow you down on large lists.

```bash
export FZF_DEFAULT_COMMAND='fd -tf -HL | sort --ignore-case'
```
