### ISSUE TITLE
Is it possible to change  input background color?

### ISSUE THREAD

**Issue by siduck** [junegunn/fzf#2757]
![image](https://user-images.githubusercontent.com/59060246/158508316-5910df73-85d6-4eea-a48a-4c732acd84a1.png)

Hi there! this fzf theme as prompt bg color, how was that achieved? I tried the theme and i didnt get the same

**Comment by rayiik** [comment]
ok so couple questions (as i do not believe that this is either a feature of bash or fzf) but what terminal emulator are you using, are you in gui or tui? are you on windows or on linux, is the fzf at the command line or in vim/neovim or tumux or other? says it requires dracula them but doing a quick search on arch there are themes for 12 differeint items from kde gtk ant alacritty cursors grub icons obenbox xresources konsole materia vim-amora and vim. i can change the color of the prompt (before the query line) in a hackish sort of way but i dont think this is possible using just bash and fzf and a tui.
```bash
bcol[0]="$(tput setab 0)"
bcol[1]="$(tput setab 1)"
bcol[1]="$(tput setab 1)"

**Comment by siduck** [comment]
I use st terminal on void linux 

![image](https://user-images.githubusercontent.com/59060246/159148064-0fb7e43a-c1c3-4fb8-9f3c-2910916b1bcc.png)

**Comment by siduck** [comment]
I meant this whole input area 

![image](https://user-images.githubusercontent.com/59060246/159148073-8f61b08e-50e1-420b-873b-7fce7466b08f.png)

**Comment by rayiik** [comment]
oh i get that you mean the whole imput (query field) but im saying its not a feature of fzf or bash (on the command line) i asked because im trying to figure out where that image is from that you see that is it inside vim the shell? the internet because the first picture you showed me says it requires Dracula theme what is the theme for? also will depend on what input command your using to feed fzf (fd forces color over fzf if fzf enables ascii color and might need to be stripped and recoloured).

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/159150005-3a0dd32c-deb5-42ec-8f7c-4f5b8c635990.png)

**Comment by junegunn** [comment]
There's no such option in fzf. I didn't post the screenshot, so I'm not 100% sure, but it looks to be "Show Cursor Guide" option of iTerm2.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/700826/159206601-23dec5cc-9f08-4c62-8a68-ab6d473cd532.png">

**Comment by siduck** [comment]
oh   ;(
