### ISSUE TITLE
Example using --ellipsis fails to match 

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#2785]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info
- OS
    - [ ] Linux
- Shell
    - [ ] bash

## Problem / Steps to reproduce

using command: nl /usr/share/dict/words | awk '{printf "%s%1000s\n", $2, $1}' | fzf --nth=-1 --no-hscroll --ellipsis='' | awk '{print $2}'

from https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0300

The list of entries is displayed but typing any character to search in the list returns 0 match

![screenshot_2022-04-07_12-14-30](https://user-images.githubusercontent.com/45409/162177004-ac5bf761-4424-4ac8-a4e9-11ecd2622177.png)

**Comment by junegunn** [comment]
Working as expected. Try typing in a number.
The words will not match because we limit the search scope to the last column (`--nth=-1`), the hidden line numbers

So what's the point? I don't know, it's just a silly example. You might want to read https://github.com/junegunn/fzf/issues/2432 to see why people want this.
