### ISSUE TITLE
[bug] if {1} contains number but not a true number (e.g. a20), --preview-window='+{1}' will also ignore the leading alphabet

### ISSUE THREAD

**Issue by Freed-Wu** [junegunn/fzf#2822]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

```
cd /dev/shm
cp /path/of/testfile a20
rg --files|fzf -d: --preview-window='+{1}' --preview='less {1}'
```

for `a20`, it will be expanded to `fzf -d: --preview-window='+a20' --preview='less a20'`. `a20` is not a number. It should be ignored. However, it be treated as `fzf -d: --preview-window='+20' --preview='less a20'`.

Thanks.

**Comment by junegunn** [comment]
Thanks for the report. The behavior is actually intentional. We strip out non-numeric characters from the field before using it as the scroll offset,

https://github.com/junegunn/fzf/blob/6dcf5c3d7d6c321b17e6a5673f1533d6e8350462/src/terminal.go#L59

in order to allow more flexibility. For example, it will recognize not only `123`, but also `[123]` or `123:`, the patterns commonly found with line numbers. If you do want fzf to ignore the field, do not leave any number in the field.

```sh
# foo10 is recognized as 10
(echo foo10; seq 30) | fzf --preview 'seq 100' --preview-window '+{1}'

# No number in ::, thus ignored
(echo ::; seq 30) | fzf --preview 'seq 100' --preview-window '+{1}'
```

**Comment by Freed-Wu** [comment]
Thanks. Is there any command option to disable this behaviour?

**Comment by junegunn** [comment]
No, just make sure that the input is well-formatted.

**Comment by Freed-Wu** [comment]
It looks all characters match `[^0-9/+-]` will be trimed. `foo5_1` will be recognized as 51?

> any command option to disable this behaviour

Or a option to configure how to process input string (e.g., `foo10`) to number (`10`)?
