### ISSUE TITLE
Enter key on numeric keypad acts like a down key

### ISSUE THREAD

**Issue by BellaCoola** [junegunn/fzf#2823]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

When I want to confirm my selection in `fzf` by pressing the Enter key on numeric keypad, instead of the expected behavior (the same as when pressing the "standard" Enter key) the selection moves one step downwards (as if I pressed a down key).

In all other software the Enter key on numeric keypad works as expected and I use no special configuration for `fzf`, which could somehow influence the key's behavior.

When I run `ruby -e 'c = gets; p [c, c.ord]'`, in both cases I get `["\n", 10]`.

However when I run `showkey --ascii`, pressing the "standard" Enter key yields `^M`, while pressing the Enter key on numeric keypad yields `^J`. 

[Man page for console codes](https://man7.org/linux/man-pages/man4/console_codes.4.html) states that:

- LF (`0x0A`, `^J`), VT (`0x0B`, `^K`), and FF (`0x0C`, `^L`) all give a linefeed, and if LF/NL (new-line mode) is set also a carriage return;

- CR (`0x0D`, `^M`) gives a carriage return;

---

Similar to: https://github.com/junegunn/fzf/issues/1828

**Comment by junegunn** [comment]
Looks like If your small Enter key produces `CTRL-J` while the larger one give `CTRL-M`.

fzf binds CTRL-J to down and CTRL-k to up to mimic Vim key bindings. It has been so [since the beginning](https://github.com/junegunn/fzf/blob/03b204ec403b150fce8b78fd65938157b5c2f03c/fzf#L333-L334), and people like the bindings, so we are not going to change that. But you can customize the keys by using appropriate `--bind` options or putting them to your `$FZF_DEFAULT_OPTS`.

```sh
export FZF_DEFAULT_OPTS='--bind ctrl-j:accept'
```

**Comment by BellaCoola** [comment]
Works great, thank you very much!
