### ISSUE TITLE
Cannot access ~/Documents and ~/Downloads from $HOME

### ISSUE THREAD

**Issue by MaralWa** [junegunn/fzf#2842]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

fzf does not list any files or directories in ~/Documentt or ~/Downloads, when I am in my home directory:
```
▶ ls -d D*
Datenbanken Desktop     Documents   Downloads   Dropbox
~
▶ cd **<TAB>
> Docu
⠼ 7650/165503
> Library/TeXShop/Documents
  Library/TeXShop/Documents/Latexmk
  Library/TeXShop/Documents/Tips&Tricks
  Library/TeXShop/Documents/CommandCompletion
  Library/TeXShop/Documents/Latexmk/Document Source
  Library/TeXShop/Documents/Michael Sharpe Contributions
  Library/TeXShop/Documents/Latexmk/Quick Start Guide for latexmk
  ..ary/Application Support/org.sjeng.leela_148745634220163/dosdevices/z:/usr/share
```
Although the `Documents` folder would be the most obvious suggestion it or any of its content is never shown in the list. The same holds for the `Downloads` folder. To see suggestions for these folders I have to enter`cd Documents/**<TAB>`  and `cd Downloads/**<TAB>`

**Comment by junegunn** [comment]
> never shown in the list

It's probably not `never`, it will come up eventually.

`cd **`-completion by default uses `find` command to list the directories

https://github.com/junegunn/fzf/blob/6dcf5c3d7d6c321b17e6a5673f1533d6e8350462/shell/completion.zsh#L89-L95

And because `find` scans the file system in depth-first manner, you may not see the nearest directories for a very long time.

You might want to set up a breadth-first scanner program instead of `find` such as [bfs](https://github.com/tavianator/bfs) or [blsd](https://github.com/junegunn/blsd) (which is my project, it works, but it's not actively maintained).

https://github.com/junegunn/dotfiles/blob/41d5b28159b47a41e56c6b8f6a4cee0944342769/bashrc#L427-L437
