### ISSUE TITLE
Easier shell keybinding customization

### ISSUE THREAD

**Issue by alecbenzer** [junegunn/fzf#287]
Customizing shell keybindings should be easier/better documented. The fzf-based histroy search in zsh is quite nice, but sometimes I'd prefer to just have zsh's less obtrusive history search. It'd be nice if I could rebind the fzf-based history search to `^E` or something, have leave `^R` as-is (I'm sure this is possible if I fiddle with the `.fzf.zsh` file, but I'm not sure how).

**Comment by junegunn** [comment]
Adding something like this to your .zshrc will do:

```sh
bindkey '^E' history-incremental-search-backward
bindkey '^R' fzf-history-widget
```

Now if you look at [shell/key-bindings.zsh](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh), you'll notice that it's pretty short and straightforward. (And it can be even shorter if we didn't allow customizing the behavior with env variables.) So I would tell the users to write their own based on the "example implementation", instead of me adding a bunch of env variables trying to make every aspect configurable.

**Comment by alecbenzer** [comment]
Thanks, that's helpful. I think just adding a line like that to the wiki showing the relevant shell function names and examples of remapping them would be nice.

**Comment by junegunn** [comment]
Good point, I'll think about it.
