### ISSUE TITLE
Escape shouldn't exit if field is not empty

### ISSUE THREAD

**Issue by JikkuJose** [junegunn/fzf#289]
Be default `fzf` exits on pressing escape. But I think it may be better if we can clear the input field on escape and exit only if the field is empty. So in general pressing escape twice will close fzf no matter what and pressing once will clear the field.

**Comment by junegunn** [comment]
> But I think it may be better if we can clear the input field on escape and exit only if the field is empty.

Thanks for the suggestion. I don't think there can be a general consensus on how it should behave. Some people will find the suggested behavior more confusing. I could add a `--bind`able action for that (e.g. something like `abort-if-empty`) so one can customize the behavior of `ESC`, but since I personally prefer `CTRL-C` over `ESC` and very accustomed to using `CTRL-U`, I'm not sure if I'm going to do it.

**Comment by JikkuJose** [comment]
Understandable; its okay if you can't. I have been using CTRL-U so far, but was feeling weird ever since I enabled Vi mode everywhere. Anyways, thanks for your time.

**Comment by junegunn** [comment]
I see, I'll think about adding the action.

**Comment by JikkuJose** [comment]
Its okay, if there isn't anyone else who feels that way. I somehow felt
this may get enough interest.

**Comment by edi9999** [comment]
Using ctrl-c to too quit fzf so I agree with junegun

**Comment by junegunn** [comment]
Added `eof` action for `--bind`. You can bind `esc` to `eof` as follows.

```vim
export FZF_DEFAULT_OPTS="--bind esc:eof"
```

Incidentally, there's an open issue with the original EOF key, CTRL-D. It's currently bound to `delete-char` action which was named after `bind -p` output of bash. On bash, CTRL-D is bound to `delete-char` but it acts as EOF when the prompt line is empty. `delete-char` action of fzf was implemented to imitate the behavior so it's effectively `delete-char` **or** `eof`. The problem is that `del` key is also bound to the action, so pressing `del` key on an empty fzf prompt will cause fzf to close. And we need a need way to differentiate the two.

**Comment by JikkuJose** [comment]
This is not there in release yet right? I can't be using `brew upgrade` to get this but have to pull the repo manually?

**Comment by junegunn** [comment]
@JikkuJose Yes, it's not yet released. If you use homebrew, you can pass `--HEAD` option to build fzf the latest source.

```sh
brew reinstall --HEAD fzf
```

**Comment by JikkuJose** [comment]
Oh cool, thanks! I didn't know about this.

**Comment by JikkuJose** [comment]
Oh cool, thanks! I didn't know about this.

Just to confirm: You haven't added the functionality to clear if Esc is pressed when the field isn't empty right?

**Comment by junegunn** [comment]
> if we can clear the input field on escape and exit only if the field is empty.

Oh, I completely missed the first part of your request. Then we'll have to rename the `action`, but I can't seem to think of a good, orthodox name for it, hmm.

**Comment by junegunn** [comment]
As far as I know, there's no equivalent action in bash, and I just decided to name it `cancel` which seems to make sense in the context as it "cancels" the input then "cancels" the finder.

Please rebuild fzf and try this one instead:

```vim
export FZF_DEFAULT_OPTS="--bind esc:cancel"
```
