### ISSUE TITLE
Request: Separate completion *for* fzf from completion *with* fzf

### ISSUE THREAD

**Issue by jdevera** [junegunn/fzf#291]
As a user, I'd like to have completion for the fzf options, but it seems currently bundled with the options where fzf taps into the shell completion.

Would it be possible to separate them?

**Comment by junegunn** [comment]
So what you suggest is that we split the file into two, like `completion.bash` and `fzf-completion.bash`? There's absolutely no technical problem with doing that, but:
- For the change to be complete, we'll have to change the install script so that the users can selectively opt-in during installation. But I don't want to do it since it can annoy users who have something like this in their init scripts: `(echo n; echo y) | ~/.fzf/install`
- Honestly, I haven't really paid too much attention to "fzf option" completion. Firstly because I don't think fzf has too many number of options which necessitates interactive help. Compare the number of options of fzf with those of `ag`, `find`, `rsync`, etc. And we, or at least me, do not use fzf directly that often, but instead use a script, function, or some vim script that encompasses it. Considering that, I don't see much benefit to it, rather I think introducing another file can be confusing to the ordinary users who never are interested in reading the code. And also, we don't have option completion for zsh and fish.

**Comment by jdevera** [comment]
Sorry I did not answer before. I meant to say that I'm okay then with not adding this. After all, I can always extract it from what is already published. Luckily, I use bash, so concerns about fish and zsh.
