### ISSUE TITLE
execute() action on empty input

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#293]
Hi, me again...

I have noticed that the `execute()` action in `--bind` behaves differently than the other actions:

```sh
printf '%s.' | fzf --bind='esc:EXECUTE(echo {})' --expect=esc
printf '%s' | fzf --bind='esc:EXECUTE(echo {})' --expect=esc

printf '%s.' | fzf --bind='esc:abort' --expect=esc
printf '%s' | fzf --bind='esc:abort' --expect=esc
```

`execute()` will only be applied if there is some input. Can we bring them into line?

**Comment by junegunn** [comment]
> execute() will only be applied if there is some input

It's intentional. It doesn't make sense to execute something "for nothing". If we allow that, we'll have to check if `{}` is empty or not, more precisely, we'll even need a way to know if it's an empty string, or if the cursor isn't pointing to any. Simple things like `fzf --bind 'enter:execute(vim {})'` will become more complicated, and the benefit is not clear to me.

**Comment by D630** [comment]
Ok, no problem.

This question came into my mind, because I had been trying to use keybinds without parsing `--expect` output. Something like this:

```sh

__build ()
case X in
Y)
        ...
;;
...
esac

__fzf ()
case FOO in
BAR)
        1>/dev/null command fzf \
                --expect=KEYn \
                --bind='KEYn:execute(script {} "SUBCOMMAND|ARG")'
;;
...
esac

while :
do
        source FILE
        __build | __fzf
done
```

```sh
# script

... > FILE

```

**Comment by junegunn** [comment]
Yeah, I also replaced some uses of `--expect` with it, but it's clearly not for everything.

https://github.com/junegunn/dotfiles/blob/c4b53bbc1749217ba42ba46a419ffd462aca9368/bashrc#L291-L298
