### ISSUE TITLE
remove dependency on bash

### ISSUE THREAD

**Issue by bsdmp** [junegunn/fzf#3011]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

man says:

       FZF_DEFAULT_COMMAND
              Default command to use when input is tty. On *nix systems, fzf
              runs the command with $SHELL -c if SHELL is set, otherwise with
              sh -c, so in this case make sure that the command is POSIX-
              compliant.

but code uses 'bash' as shell, it requires extra dependencies on non-linux systems

this patch makes code even with the doc:

```
diff --git a/src/reader.go b/src/reader.go
index 06e9b73..eac0027 100644
--- a/src/reader.go
+++ b/src/reader.go
@@ -98,8 +98,7 @@ func (r *Reader) ReadSource() {
        r.startEventPoller()
        var success bool
        if util.IsTty() {
-               // The default command for *nix requires bash
-               shell := "bash"
+               shell := "sh"
                cmd := os.Getenv("FZF_DEFAULT_COMMAND")
                if len(cmd) == 0 {
                        if defaultCommand != "" {


```

**Comment by junegunn** [comment]
The documentation is correct. `bash` is only used when `$FZF_DEFAULT_COMMAND` is not defined. Because the original default command we use is not guaranteed to run on `sh` (e.g. `dash`)
* https://github.com/junegunn/fzf/blob/d56fe74e247dc3c5e70a3f6482ff1ece8b5f638a/src/constants.go#L61

When` $FZF_DEFAULT_COMMAND` is defined, fzf will use `$SHELL` to run the command.
* https://github.com/junegunn/fzf/blob/d56fe74e247dc3c5e70a3f6482ff1ece8b5f638a/src/reader.go#L110-L112
* https://github.com/junegunn/fzf/blob/d56fe74e247dc3c5e70a3f6482ff1ece8b5f638a/src/util/util_unix.go#L13-L16
