### ISSUE TITLE
[Feature request] preview shell

### ISSUE THREAD

**Issue by TheTrveAnthony** [junegunn/fzf#3016]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Hi,

I wanna use fzf with nvim because I find telescope does too much and it seems overcomplicated to change the window size while it's super simple with fzf.vim.
The only problem is, since I use fish as a shell, fzf uses it to preview files and my fish config outputs a colorscript when it's launched, so running `fzf --preview 'bat {}'` looks like this for me : 
![fzfpreview](https://user-images.githubusercontent.com/40374762/196792139-3699e254-787d-4721-9bb9-d7da71298625.png)

As you can see, over half the of the preview window is useless because of this.
From the man page I saw that fzf uses the `$SHELL` variable to preview files, so would it be possible to create a new environment variable that tells fzf which shell to use ? (`$FZF_SHELL` or `FZF_PREVIEW_SHELL`)
To reproduce the issue, just add 
```bash
echo "zfqzd"
```
To `/.config/fish/config.fish`.

  Thank you

**Comment by junegunn** [comment]
There are programs that use `$SHELL` to execute external programs, so if you don't want to break them, you should restructure your fish config file so that user-facing interactive stuff such as printing those spaceships (tie fighters?) only in interactive sessions like so

```sh
if status is-interactive
  # Spaceships!
end
```

See
* https://github.com/fish-shell/fish-shell/issues/5246#issuecomment-439375636
* https://github.com/fish-shell/fish-shell/issues/4432#issuecomment-332537729
* https://github.com/fish-shell/fish-shell/issues/5394

**Comment by junegunn** [comment]
FWIW, you can override environment variables for Vim (or Neovim) in your Vim configuration file.

```vim
let $SHELL = '/bin/bash'
```

**Comment by TheTrveAnthony** [comment]
That did the trick thank you.
