### ISSUE TITLE
Chunk matching still not ideal

### ISSUE THREAD

**Issue by xeruf** [junegunn/fzf#3086]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

![image](https://user-images.githubusercontent.com/13354331/207377625-43851d1d-106b-417d-9a6a-58324ec91b6b.png)

As you can see here, the full "knolle" is not matched even with tiebreak=chunk.
Removing the space fixes the match, but that shouldn't be needed.

**Comment by junegunn** [comment]
The algorithm is working as expected. If you remove the first term from your query, you'll notice that the matched substring starts from the beginning of the item. That's because fzf puts a big bonus score on a character at the place.

```sh
echo $'Knoblauchknolle\nKnoblauchpille' | fzf -q knolle
```

<img width="826" alt="image" src="https://user-images.githubusercontent.com/700826/207505856-687ceb2d-e6f9-49ec-b218-fe8c96bc92fc.png">


And because the length of the matched substring is shorter for `Knoblauchpille`, it is ranked higher. `tiebreak` is not used because the score is already different. And even if it's used, `chunk` tiebreak will prefer the shorter encompassing chunk, which is `Knoblauchpille`. (`chunk` is equivalent to `length` for items without whitespaces.)

On the other hand in this case,

```sh
echo $'Knoblauch-----knolle\nKnoblauch-----pille' | fzf -q knolle
```

<img width="825" alt="image" src="https://user-images.githubusercontent.com/700826/207505973-f8c71c1d-245c-434e-8259-2838a3688aa2.png">

The ranking is different. In this case, `Kno` at the start and `lle` at the end are too far away, and the bonus point is not great enough to compensate for the distance ("gap penalty"), so fzf matches `knolle` at the end.

You can read more about it here. https://github.com/junegunn/fzf/blob/master/src/algo/algo.go#L39

If you do want to match exact substring, put `'` prefix to a term. i.e. `'knolle`.

**Comment by xeruf** [comment]
don't you think it makes sense to adjust the algorithm so it prefers the longer consecutive match?

**Comment by junegunn** [comment]
No. From my experience, it doesn't yield better results. For example, most users prefer `OutOfMemory` over `bloom` on `oom`. If you're curious, you can adjust the algorithm and build fzf from the source.
