### ISSUE TITLE
The line added to ~/.bashrc is wrong

### ISSUE THREAD

**Issue by paul-alkhimov** [junegunn/fzf#311]
The line which is added to the ~/.bashrc needs a newline before it.

Otherwise (in my case) the last line of my ~/.bashrc file looked as follows:
`esac[ -f ~/.fzf.bash ] && source ~/.fzf.bash`

And as a result, fzf did not work at all.
(tested on elementary os)

**Comment by junegunn** [comment]
Hi, thanks for the report. Looks like your .bashrc didn't have the new line character at the end, which is quite unconventional for the OSs that fzf supports. Excerpt from a [stackoverflow thread](http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline):

> Because that’s how the POSIX standard defines a line:
>
> 3.206 Line
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

And therefore, your text editor will automatically add a new line to a text file unless you explicitly tell it not to do so. For example, in Vim we can say `set binary noeol` to remove the new line at the end, but I don't quite see the point of saying that .bashrc is a binary file.

Maybe the lack of the ending new line of your ~/.bashrc has something with elementary OS, but I'm not at all familiar with it, so I'm not sure.

Having said that, I updated the installer to add an extra new line, so that it doesn't corrupt the file even when it does not end with a new line like in your case. Thanks.
