### ISSUE TITLE
fzf should take positional arguments: the paths to be searched

### ISSUE THREAD

**Issue by hindman** [junegunn/fzf#3126]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I was surprised to find that fzf does not take positional arguments -- namely the paths to be searched.
At least under the default definition of `FZF_DEFAULT_COMMAND`, those positional arguments would
be parameters replacing the `*`.

    # This.
    fzf foo bar [other-options]

    # Would become this behind the scenes.
    find foo bar -type f | fzf [other-options]

If that approach won't work because it might not play nicely with customized variants of `FZF_DEFAULT_COMMAND`,
fzf could add a new option allowing users to supply those paths. For example, something roughly like this:

    fzf --paths foo bar [other-options]

Thanks for considering this idea.

**Comment by junegunn** [comment]
Because fzf is more like `grep` rather than `find`. It's a text filter, it's good at providing an interactive text filtering interface, but it doesn't try at all to be a good directory traversal program. You are advised to use a modern directory traversal program such as [fd](https://github.com/sharkdp/fd) along with fzf.

https://github.com/junegunn/fzf#respecting-gitignore
