### ISSUE TITLE
Sample implementation of FZFTags makes working with identical tags in different files difficult.

### ISSUE THREAD

**Issue by rahulkmr** [junegunn/fzf#315]
command! -bar FZFTags call fzf#run({
    \   'source': "sed '/^\\!/d;s/\t.*//' " . join(tagfiles()) . ' | uniq',
    \   'sink':   'tag',
    \ })

This ignores a very common occurrence where an identical tag is defined in multiple files. 

It will be better to allow narrowing down the raw tags input viz. "search model account" to find the search tag in account model, and execute the ex command in the tag file once the user has narrowed down the selection.

    function! s:tag_open(selection)
      let parts = split(a:selection, '\t')
      execute "edit"  parts[1]
      execute substitute(parts[2], ';"$', '', 'g')
    endfunction

    command! -nargs=? -bar FZFTag call fzf#run({
    \   'source': "awk -F'\t' '$1 ~ /<args>/{print}' " . join(tagfiles()),
    \   'sink': function('<sid>tag_open'),
    \ })
    nnoremap <Space>t :FZFTags  

This ignores the vim tag features(tag stack, jumping back and forth...). I tried using `ts /pattern` as source and `[count]tag /pattern` as sink where count is extracted from `ts /pattern` but [count] was different between `ts` and `tag`.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion. I added a more [advanced version of the command](https://github.com/junegunn/fzf/wiki/Examples-(vim)#jump-to-tags). (Also take a look at `BTags`) I didn't remove the original one since the purpose of the page is to suggest simple and concise examples rather than to provide sophisticated implementations.

**Comment by rahulkmr** [comment]
Thanks for including the alternate implementation and fixing my sink implementation.

```
call fzf#run({
  \ 'source':  'cat '.join(map(tagfiles(), 'fnamemodify(v:val, ":S")')).
  \            '| grep -v ^!',
  \ 'options': '+m -d "\t" --with-nth 1,4.. -n 1 --tiebreak=index',
  \ 'down':    '40%',
  \ 'sink':    function('s:tags_sink')})
endfunction
```

awk seems to run noticeably faster than this on large tags files(about 200k tags). I thought it's probably because yours is forking a extra process(grep), but removing that didn't give me a significant speed-up. That's weird because awk is doing extra things and cat is just catting. I didn't delve more into it.


```
command! -nargs=? -bar FZFTag call fzf#run({
\   'source': "awk -F'\t' '($0 \\!~ /^\\!/) && $1 ~ /<args>/{print}' " . join(tagfiles()),
\   'sink': function('<sid>tags_sink'),
\ })
nnoremap <Space>t :FZFTag
```


Also, I have to double escape ! or it kept getting replaced with `clear 2> /dev/null`. I am not sure if it's me or something in your code.

```
  \ 'options': '+m -d "\t" --with-nth 1,4.. -n 1 --tiebreak=index',
```

While this presents a cleaner selection interface, this takes away filtering on filename which I personally use a lot - "search model account"(`def search` in `app/models/account.rb`)

```
call system('ctags -R --excmd=number')
```

I personally don't use `excmd=number`. I regenerate my tags from commit hooks and my tags are out of date a lot of times. Search patterns work better than numbers for me(except for same tag repeated in a file).

The BTags implementation is nice. Most of the times for the same buffer, I simply search or do a ctrl-], but the tag selection interface is nice to have for large files with a lot of common base words.

**Comment by junegunn** [comment]
Thanks for the feedback.

I realized that what is slow is not `grep` or `cat`, but `--with-nth` option of fzf. It relies on the regex engine of Go, which is darn slow. I'll address the issue in the next version. (We should use regex engine only when needed. We clearly don't need it when `--delimiter` is  `\t`)

> this takes away filtering on filename which I personally use a lot

Fair enough. Since the code there is just an example, I believe the users will adjust the snippet to match their preferences.

> Search patterns work better than numbers for me

Good point. I liked `--excmd` because it makes the code simpler, no special handling of tab characters, no `nomagic` switch, but I agree that `--excmd=pattern` is a better choice when creating permanent tag files. I updated the snippet.

> Most of the times for the same buffer, I simply search or do a ctrl-]

Me neither. To be honest, I don't really use either `Tags` or `BTags` and I prefer cscope.
