### ISSUE TITLE
How to preserve the input order?

### ISSUE THREAD

**Issue by gpakosz** [junegunn/fzf#3157]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

How to preserve input order?
I looked at #1189 but for me

```
$ printf '%s\n' 'xxxaaa' 'aaa' 'a' | fzf --no-sort
```
gives me
```
a
aaa
xxxaaa
```

How can I get the same order as in input?

**Comment by Delapouite** [comment]
With the `--tac` flag:

```
$ printf '%s\n' 'xxxaaa' 'aaa' 'a' | fzf --no-sort --tac
```

**Comment by gpakosz** [comment]
Hmm the `--tac` flag is documented as
```
--tac  Reverse the order of the input
```

Does it work by luck? I mean I don't want the order of the input to be reversed, I want it to be untouched 🙃

**Comment by jlebon** [comment]
Here's my understanding: the first item in the list is the one closest to the prompt. So the order you see is correct: `xxxaaa` is first since it's closest to the prompt (which means it's the easiest to access). You can see this property is retained if you flip the layout with `--reverse` so that the prompt is at the top: `xxxaaa` will still be the closest. `--no-sort` prevents reordering of the items once a query is entered into the prompt.
