### ISSUE TITLE
Should --tiebreak=begin --tac +s move the caret?

### ISSUE THREAD

**Issue by gpakosz** [junegunn/fzf#3161]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When using
```
$ printf 'foo 123\nbar foo\n' | fzf --tac --tiebreak=begin +s
```
Should typing `foo`, move the caret?

I get this
<img width="83" alt="image" src="https://user-images.githubusercontent.com/553208/217948515-3a4a91cc-78aa-46a2-940a-48abecfbbac4.png">

While I expected this
<img width="83" alt="image" src="https://user-images.githubusercontent.com/553208/217948616-370bc3dd-1f56-4731-96fd-fdcc7c60fc82.png">

**Comment by junegunn** [comment]
> Should typing `foo`, move the caret?

No. There's no involuntary movement of the cursor. fzf was primarily designed for this workflow.

* Type in the query, narrow down the result
* The most relevant match comes to the top position **because sort is enabled by default**
* Press enter
   * Sometimes you have to move your cursor upwards, but only a few positions.
