### ISSUE TITLE
[Feature request] Option to expand ~ to "$HOME" in paths

### ISSUE THREAD

**Issue by rieje** [junegunn/fzf#3172]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux

- Shell
    - [x] zsh

## Problem

I generated list of files and prefer `~` to `/home/rieje` because it's visually simpler to read and reduces potentially lengthy paths that make it inconvenient to read.

However, `{}` expands to the literal string of the item and previewers and other applications don't expand this so they won't work in fzf at all.

I have a wrapper bash script that converts paths that uses `/home/rieje` to `~`, then on selection converts it back to `/home/rieje` so applications can parse it:

    # Generate list of files and store in $files
    # ...

    # Substitute $HOME for ~
    files=$(awk -v home="$HOME" '$0 ~ /^\./ { print "~/" $0; next } { sub("^" home, "~"); print }' <<< "$files")

    file=$(fzf --prompt="edit file: " "$@" <<< "$files") || exit

    # Substitute ~ back to $HOME for selected item
    file="${file/#"~"/"$HOME"}"

    # Open selection with application
    "$EDITOR" "$file"

If fzf can handle this, then previewers and applications would work as expected. I imagine the implementation can be something like `{~}` as placeholder.

----

Unrelated question since this is a feature request, but is it possible to highlight (color) the basename of a file in the results? Also aids in lengthy paths. It would need to be a different color than the color used to highlight the matching part of the regex, of course.

**Comment by junegunn** [comment]
Please note that fzf is a general-purpose text filter rather than a filter specialized only for file paths, so I'm not inclined to add features specific to a specific type of input. The requested features should be handled by the source command (i.e. specific coloring of the file), and by the preview command; you can do the same substitution in the preview command as you did in the script shown above.

> but is it possible to highlight (color) the basename of a file in the results?

I believe you can do it in your source command, and maybe there are programs that do that for you.

```sh
ls | lolcat -f | fzf --ansi
```
