### ISSUE TITLE
fzf and gvim: opens an xterm and does nothing else

### ISSUE THREAD

**Issue by v76591wC** [junegunn/fzf#318]
I have installed fzf for my gvim. Wenn I try ":FZF" a terminal window is opened in my home directory, but nothing else happens.

I am sure I am doing something wrong or that I have a strange configuration, but I probably need some help figuring out what's wrong.

**Comment by junegunn** [comment]
Hi, I need more info.
1. OS
2. Shell
3. Vim version
4. `fzf --version`
5. Does `:call fzf#run({'source': 'seq 100'})` work? If not, does it work on terminal vim?

**Comment by v76591wC** [comment]
1. Debian oldstable
2. This is, where it gets interesting. Company policy prohibits me changing shell directly, so I have "zsh && exit" in my bashrc. So I would say: zsh within bash
3. VIM - Vi IMproved 7.3 (Included patches: 1-547)
4. 0.10.0
5. It does not. In terminal vim everything works as expected.

I just tried something that is quite interesting:
When I use :FZF in gvim and it opens xterm, I can get to fzf by pressing ctrl+c and ctrl+d. ctrl+d directly won't work.

**Comment by junegunn** [comment]
Alright, the default launcher function for GVim currently [sets `-i` flag](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L200) when starting xterm with bash which causes .bashrc to be loaded, and that line you have in there obviously is causing the problem.  (I believe `bash -ci vim` doesn't work as well due to the same issue, right?)

I tried removing `-i` flag, but it causes rendering issue in xterm window, so I'll have to keep it. Consider writing your own launcher function if you have to keep that line.
