### ISSUE TITLE
Option for Ctrl-T to use current command-line content as a search pattern

### ISSUE THREAD

**Issue by githorse** [junegunn/fzf#3195]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I use `CTRL-T` a hundred times a day, but my brain still thinks that it is going to respect an initial query:

```
$ cat something<CTRL-T>
```

But that doesn't happen -- `something` has no effect here. In the same spirit as [Option for Ctrl-R to use current command-line content as a search pattern](https://github.com/junegunn/fzf/issues/144) -- is it possible to populate the initial query with `something` here? 

There are a few challenges here that are a beyond me: 

1. Once I select the file name with `fzf`, how do I overwrite the value (`something`) on the command line?
2. How do I make it work with a custom `CTRL-T` command, e.g. `FZF_CTRL_T_COMMAND='fd'`?

**Comment by junegunn** [comment]
> is it possible to populate the initial query with `something` here?

The functionality is provided by "fuzzy completion", which is by default triggered when you append a trigger sequence (default: `**`) then press <kbd>TAB</kbd> key.

```sh
# Triggering fuzzy completion
cat something**<TAB>
```

The added benefit is that it also can extract the directory part of the prefix and start the search from that directory.

```sh
# Start search from /tmp
# Initial query is set to "something"
cat /tmp/something**<TAB>
```

So in case you need this functionality, you can reach for the fuzzy completion instead of the simple CTRL-T.

---

However, if you find it cumbersome to type the trigger sequence (`**`), then you can use the configuration shown in the link below so that CTRL-T will trigger fuzzy completion even without `**` (zsh only).

* https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#dedicated-completion-key

---

[Configuring fuzzy completion](https://github.com/junegunn/fzf#settings) is a bit more complicated than CTRL-T, because

* It should show different entries depending on the context
    * e.g. You want a list of processes instead of a list of file paths when you type `kill -9 **<tab>`
* It should be able to pass the search root to the command populating the list
    * e.g. `cat /tmp/something**<TAB>`

---

To sum up, here's a full example of configuration options you might want to try.

```sh
# Setting CTRL-T as a dedicated completion key that doesn't require prefix (**)
#   https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion
export FZF_COMPLETION_TRIGGER=''
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion

# Configuring fuzzy completion
# https://github.com/junegunn/fzf#settings
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Common fzf options to use in fuzzy completion
# export FZF_COMPLETION_OPTS=...

# fzf options for each command
_fzf_comprun() {
  local command=$1
  shift
  case "$command" in
    cd)           fzf --preview 'tree -C {} | head -200'   "$@" ;;
    export|unset) fzf --preview "eval 'echo \$'{}"         "$@" ;;
    ssh)          fzf --preview 'dig {}'                   "$@" ;;
    *)            fzf --preview 'bat -n --color=always {}' "$@" ;;
  esac
}
```

---

Please let me know if you need further assistance. Thanks.

**Comment by githorse** [comment]
Brilliant! This is exactly what I was looking for. Works like a charm.

I made two small tweaks:

1. Changed the `fd` command so that it only respects uses `.gitignore` in the repository root. 98% of the time that's where I search from, and that's what I want; but if I first `cd` into a sub-directory (e.g. `node_modules`), I want to see whatever's in that directory, regardless of `.gitignore`.
```
_fzf_compgen_path() {
	[[ ! -d "$1"/.git ]] && fd_flags="-I"
	fd --hidden --follow --exclude ".git" "$fd_flags" . "$1"
}
```

2. I was getting an error with the default preview command (`*)`) when the match is a directory. Added a conditional to change the preview when the match is a directory:

```
DEFAULT_PREVIEW='[[ -d {} ]] && exa -lF --group-directories-first --color=always {} || batcat -n --color=always {}'

...
    *)  fzf --preview $DEFAULT_PREVIEW "$@" ;;
```

(Obviously that command will differ depending on what `ls` and `cat` utilities you use.)

**Comment by kaddkaka** [comment]
I believe I have a usecase where invoking `ctrl-T` and using the current WORD as a starting point would be useful. 

**Opening png files with firefox**

The issue is that firefox tries to be helpful and among the completions doesn't include files it *thinks* you don't want to open. 

Example:
```
mkdir pictures
touch pictures/potato.png
firefox pictures/<TAB>
```
Result: potato.png does not get completed.

Firefox does support opening png:s so this is arguably an issue with firefox, but it would be nice to circumvent it by invoking ctrl-t as described here.
