### ISSUE TITLE
Open file in new tab by `Ctrl-t` when searching in buffer.

### ISSUE THREAD

**Issue by ycavatars** [junegunn/fzf#320]
hi, I add the `list of buffer` example (https://github.com/junegunn/fzf/blob/master/README.md#examples-1) to my `nvimrc`. I found that when I can't use `ctrl-t` to open the selected file in a new tab. Do I miss something? I use `neovim` on mac yosemite. Thanks.

**Comment by junegunn** [comment]
No, you're not missing anything. As you can see the code does not say anything about `ctrl-t`. Since fzf is a general-purpose filter, such key bindings should be handled by the outer script. The following example shows how you can make fzf **expect** custom key bindings with `--expect` option.

https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim

I'm considering releasing a set of commands based on fzf as an external plugin for those who are not familiar with vimscript. I'll leave a comment here when it's done, you might want to take a look.

**Comment by ycavatars** [comment]
Really thanks! The examples will be very useful, especially for vim beginners. I have only use vim for two days :) Thanks for your help

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim is now on github. It provides `:Buffers` command that supports `ctrl-t` key binding you were looking for.
