### ISSUE TITLE
Write an example of using mdfind piped to fzf?

### ISSUE THREAD

**Issue by stevenqzhang** [junegunn/fzf#321]
(apologies if this isn't issue worthy- wasn't sure where to put this suggestion)

A lot of mac users out there might not know about being able to pipe ```mdfind``` into fzf.

It's the cmdline version of spotlight search, and is much faster than `find`, more up to date than `locate`.

maybe it would be good to add a blurb into the main README.md file mentioning this?

Here's an example of how I use it in my bashrc file for finding arbitrary folders.

```bash
md() {
  DIR=`mdfind "kind:folder" -name  2> /dev/null | fzf -e` && cd "${DIR}"
}
```
https://github.com/stevenqzhang/dotfiles/blob/master/.bashrc#L1

**Comment by junegunn** [comment]
Hi, thanks for the suggestion.

> A lot of mac users out there might not know about being able to pipe mdfind into fzf.

Yeah, I didn't know about it either :) I'm not getting any result from `mdfind` though, probably because I disabled spotlight search altogether. You're welcome to add the example to [the wiki page](https://github.com/junegunn/fzf/wiki/Examples). It's open to anyone to edit.

Minor nitpicks:
- `local DIR`
- `$(...)` instead of backticks
