### ISSUE TITLE
Integration with kitty's icat for previewing images?

### ISSUE THREAD

**Issue by arisolt** [junegunn/fzf#3228]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

The kitty terminal emulator implements its own protocol for rendering graphics, called `icat`. It is possible to render images using the command `kitty +kitten icat $image.png`.

However, when running the follwing it does not work:

`fzf -q .png --preview="kitty +kitten icat {}"`

It results in the Preview pane just displaying "Loading.." .

Alongside the fact that neither iTerm's `imgcat` is supported (https://github.com/junegunn/fzf/issues/1102) or the sixel format (https://github.com/junegunn/fzf/issues/2544), there doesn't seem to be any way to preview images in fzf on MacOS, except the low fidelity (ASCII) `catimg`/`chafa`/etc.

**Comment by simonwjackson** [comment]
FWIW, I'm on linux (NixOS) & zsh

**Comment by archelaus** [comment]
Facing the same issue on Ubuntu 22.04.2 LTS with fish shell. `icat` works fine on its own, and even with lf.

**Comment by sweetbbak** [comment]
It used to work with kitty's icat a while ago but it broke after the last update to the icat function. Its much faster now but now it cant figure out Fzf. I wrote a few scripts with it but you had to be more pedantic with the command for it to work properly ie "kitty +kitten icat --clear && kitty +kitten icat --scale-up --place $WIDTHx$HEIGHT@0x0 --transfer-mode file {}"" I wrote a ton of scripts that used this functionality and it really sucked that it stopped working. I've been looking for a solution for over a month now.

Currently Fzf mangles the escape codes for drawing sixel and icat has an issue with IO (I think it cant determine that the little fzf window is something supported by icat)

The only solution that I've been using in the intermediate is using Ueberzug, or sending the command to a different Kitty window via fzf using the remote control functionality. I'd love to hear if anyone finds anything better or maybe knows a way to get it to work with Fzf. I tried to do it with version 0.1.0 and 0.7.1 hoping it would be easier to understand but I'm not skilled enough lol

**Comment by sweetbbak** [comment]
This repo is also relevant, this guy forked kitty to work with fzf and he highlights a couple of the reasons why. I havent tried it out yet though https://github.com/sergei-grechanik/tupimage

**Comment by jstkdng** [comment]
Might I interest you in this project of mine?. https://github.com/jstkdng/ueberzugpp

It is a drop-in replacement for ueberzug but with sixel and kitty support. I have made a basic fzf integration script and so far it works fine on my end. https://github.com/jstkdng/ueberzugpp/blob/master/scripts/fzfub
It is pretty barebones right now and only takes into account a vanilla preview window so... PRs are welcome :)

**Comment by yrammos** [comment]
The `timg` image (and video) previewer does work quite well with `fzf`, albeit producing blurry images (block graphics).

Based on a discussion with the timg developer ([here](https://github.com/hzeller/timg/issues/102)), fzf is probably failing to decode the scape codes that kitty uses for images.

**Comment by sweetbbak** [comment]
I feel it, thats great and all but why even go through all this work to iron out a Terminal Graphics Protocol, just to use ASCII blocks? Kitty plays videos and images really fast and with really high quality, Sixel is more widely supported but lower quality and easier to implement but they all basically do the same things.

It would be great if we could turn off processing in fzf so that we could render images using the various image protocols that use escape sequences. I made a very simple mock  up interface that uses kitty in bash and another in Python https://github.com/sweetbbak/catnip that sort of gives off the general idea but its clearly far behind what fzf is and Im far less skilled.

I really like the idea of a CLI image picker for TUI's and tools so you can easily make programs that select books, manga, music, youtube videos, movies etc... and it seems kinda nuts to still be using ascii blocks when we have a wealth of tools that have since been created to handle images.

**Comment by yrammos** [comment]
@sweetbbak thanks for this interesting prototype.

For the record, I am not enthusiastic about Sixel: its technical deficiencies aside, it is practically unsupported on the Mac (Kitty, Alacritty, or Term.app).

**Comment by KeqiZeng** [comment]
Facing the same issue on MacOS & zsh, fzf version is 0.42.0

**Comment by sweetbbak** [comment]
I tried to edit Fzf to allow for it to just not process the preview but it's a little too abstract for me.

**Comment by etpng** [comment]
I have same question

**Comment by kovidgoyal** [comment]
With this commit, I can get icat working with fzf
https://github.com/kovidgoyal/kitty/commit/fc1331cfdc673c89eee711acd958ea09c0db8600

```sh
fzf -q .png --preview='kitten icat --clear --transfer-mode=memory --stdin=no --place=20x20@20x1 {} > /dev/tty'
```

You of course need to adjust --place for your preview window though ideally FZF should set some env vars specifying the geometry of the preview window. Also there is a little display corruption, the cursor seems to end up on the wrong line in fzf, no idea whats going on with that, the icat kitten will leave the cursor at the top left of the image, maybe fzf is making some other assumptions about the cursor position. If so the command above could be modified to add some cursor movement escape codes after icat to position the cursor where fzf would like.

**Comment by sweetbbak** [comment]
Just built it and tested it from that commit and it worked wonderfully! Thanks, that's so awesome.

**Comment by yrammos** [comment]
> Also there is a little display corruption, the cursor seems to end up on the wrong line in fzf, no idea whats going on with that, the icat kitten will leave the cursor at the top left of the image, maybe fzf is making some other assumptions about the cursor position. If so the command above could be modified to add some cursor movement escape codes after icat to position the cursor where fzf would like.

I can reproduce something like this and it makes the solution unworkable (fzf lines are duplicated and line selection becomes unreliable).

**Comment by kovidgoyal** [comment]
You are welcome. Yes, as I said this needs to be addressed by someone familiar with fzf codebase. It would take me too long to figure out the root cause. My guess is, fzf is relying on some invariant about the cursor position after the preview process runs, which is no longer true.

**Comment by sweetbbak** [comment]
> Many thanks, @kovidgoyal, for addressing this on the kitty end.
> 
> > Also there is a little display corruption, the cursor seems to end up on the wrong line in , no idea whats going on with that, the icat kitten will leave the cursor at the top left of the image, maybe  is making some other assumptions about the cursor position. If so the command above could be modified to add some cursor movement escape codes after icat to position the cursor where  would like.
> 
> I can reproduce something like this and it makes the solution unworkable (lines in the fzf output are duplicated, and line selection becomes unreliable).

I also wrote this in Go, you could give it a try.
https://github.com/sweetbbak/fzf-img

My next step is to import or emulate the Go code that icat uses to directly process images (instead of calling "kitten icat" using os/exec and printing to stdout over the fzf). I tested it on my Arch desktop with the latest Kitty. It's a dead simple proof of concept but it could be a good stop-gap for now as I was unable to do anything with the fzf code base. It doesn't actually use Fzf, but a portable re-make of fzf that you can import in Go.

**Comment by junegunn** [comment]
@kovidgoyal 

Thanks, I like the approach in that fzf doesn't have to implement a custom protocol.

> ideally FZF should set some env vars specifying the geometry of the preview window

I can help you with that. I should built kitty from source to test this, right?

**Comment by kovidgoyal** [comment]
On Sun, Sep 24, 2023 at 06:50:22PM -0700, Junegunn Choi wrote:
> @kovidgoyal 
> 
> Thanks, I like the approach in that fzf doesn't have to implement a custom protocol.
> 
> > ideally FZF should set some env vars specifying the geometry of the preview window
> 
> I can help you with that. I should built kitty from source to test this, right?

No, you can use a nightly build
https://github.com/kovidgoyal/kitty/releases/tag/nightly 

If you do want to build from source, it's very easy https://sw.kovidgoyal.net/kitty/build/

**Comment by junegunn** [comment]
Okay, the problem with the approach is that fzf runs the preview command in the background asynchronously and it is possible that kitty and fzf are both printing to `/dev/tty` at the same time causing unexpected rendering issues. So it looks like we do need a special mechanism from fzf's side anyway.

1. A special preview mode that redirects the output from the preview command to `/dev/tty`
    * `fzf --preview-raw 'kitty ... '`
    * `--preview-destination /dev/tty`
    * ...
    * This is the easiest option, but there will be few other use cases for it other than this
2. Make fzf understand kitty protocol and redirect the image part to `/dev/tty`
    * `\e_G` to `\e\\`
    * This would allow a preview command that prints both image and text. But it would be hard for fzf to properly support such commands because the preview window of fzf is scrollable.
3. Or ... ?

**Comment by kovidgoyal** [comment]
If you want the most robust asynchronous preview option, I would suggest
the following:

1) Pass a temp dir to the preview script, possibly as an env var
2) If the preview script wants to output images it should write them as
PNG files in the that dir with names like 1.png, 2.png, ...
3) The preview script should output some simple escape code or
unicode placeholder char in its output text
4) When fzf sees that char/escape code it should read the next PNG image from the
dir and output it on the current line
5) Probably pass the preview window size in cells and pixels as env vars
so that the preview script can output correctly sized PNGs to avoid fzf
having to resize them.
6) When the preview area is cleared pass the escape code to clear any
images to the terminal.

This will require fzf to support basic image output but it preserves the
properties of asynchronicity and robustness.

Outputting a PNG image using the kitty protocol is dead simple, there
are 10 line bash and python scripts that do this here:
https://sw.kovidgoyal.net/kitty/graphics-protocol/#a-minimal-example
Or you can just use the icat kitten to do it for you since it is no
longer asynchronous.

You will need to be a little more sophisticated to place the image in
the preview window area, but that will just be a couple of lines more of
code.

There are further complications that I suggest you dont need to worry
about for a MVP. Namely tmux, which if you want to support you will need
to use the unicode placeholders method of the kitty graphics protocol
(which icat supports) and also there are a few terminals that support only 
sixels but not kitty.

On Sun, Sep 24, 2023 at 11:00:38PM -0700, Junegunn Choi wrote:
> Okay, the problem with the approach is that fzf runs the preview command in the background asynchronously and it is possible that kitty and fzf are both printing to `/dev/tty` at the same time causing unexpected rendering issues. So it looks like we do need a special mechanism from fzf's side anyway.
> 
> 1. A special preview mode that redirects the output from the preview command to `/dev/tty`
>     * `fzf --preview-raw 'kitty ... '`
>     * `--preview-destination /dev/tty`
>     * ...
>     * This is the easiest option, but there will be few other use cases for it other than this
> 2. Make fzf understand kitty protocol and redirect the image part to `/dev/tty`
>     * `\e_G` to `\e\\`
>     * This would allow a preview command that prints both image and text. But it would be hard for fzf to properly support such commands because the preview window of fzf is scrollable.
> 3. Or ... ?
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/junegunn/fzf/issues/3228#issuecomment-1732972484
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by kovidgoyal** [comment]
Also there is the issue of animated image previews like GIF files or video thumbnails. icat transparently handles GIF but for video thumbnails life will be a bit harder, maybe just use the cover image.

**Comment by kovidgoyal** [comment]
Oh and given fzf is in Go I should mention there are existing go libraries to output kitty graphics, a quick google should them, for instance https://github.com/dolmen-go/kittyimg

**Comment by junegunn** [comment]
Thanks for the detailed comment. The thing is, I'm not sure if I want to incorporate a non-standard protocol into fzf, even if it's easy and simple. For now, something like `--preview-destination /dev/tty` appears to be the most versatile solution, supporting not only Kitty but also Imgcat of iTerm2 and Sixel. I need to do more research though.

**Comment by kovidgoyal** [comment]
Well the major downside of that is you lose both asynchronicity (you have to block fzf while the preview script is running) and you cant scroll the preview window any more. And it wont work inside tmux. 

Another option which gives you all of asynchronicity, scrolling and tmux support without fzf having to understand the kitty protocol is use

icat --unicode-placeholder

this will cause icat to output a bunch of PUA unicode characters in the image area (i.e. normal text) that will be replaced by the image. All fzf then needs to do is passthrough any graphics escape code to the tty which is easily done with a simple regex. Scrolling works just as with normal text since that is all there is.

Now fzf doesnt understand anything about the graphics protocol other than the start and end chars of the escape code. It just deals with plain text which it can scroll and have the image scroll normally. Even deleting the image is unnecessary as deleting the text will take care of it automatically.

**Comment by kovidgoyal** [comment]
Anyway, its your project I just got involved to fix the icat not working at all issue. Hope you find a good solution, all the best.

**Comment by junegunn** [comment]
> you lose both asynchronicity

No, the preview of fzf is asynchronous by nature. fzf doesn't block on long preview process.

```sh
# Displaying streaming data
fzf --preview 'while true; do sleep 0.01; date; done' --preview-window follow
```

The idea is to run the preview command in the background,  take the output, and print it to `/dev/tty` instead of displaying it inside the preview window of fzf.

> icat --unicode-placeholder

I'll take a look at that, thanks.

I'm not sure though how it would enable scrolling *inside* the preview window of fzf which is a small region of the screen that is separately scrollable.

<img width="862" alt="image" src="https://github.com/junegunn/fzf/assets/700826/5465039b-3c2d-459d-8a92-b28267f9d1ef">

**Comment by kovidgoyal** [comment]
On Mon, Sep 25, 2023 at 01:37:05AM -0700, Junegunn Choi wrote:
> > you lose both asynchronicity
> 
> No, the preview of fzf is asynchronous by nature. fzf doesn't block on long preview process.

If the preview script is writing to /dev/tty then fzf has to not write
to it which means it has to block at least is UI rendering thread.

> 
> ```sh
> # Displaying streaming data
> fzf --preview 'while true; do sleep 0.01; date; done' --preview-window follow
> ```
> 
> The idea is to run the preview command in the background,  take the output, and print it to `/dev/tty` instead of displaying it inside the preview window of fzf.
> 
> > icat --unicode-placeholder
> 
> I'll take a look at that, thanks.
> 
> I'm not sure though how it would enable scrolling *inside* the preview window of fzf which is a small region of the screen that is separately scrollable.

The same way the fzf scrolls text in the preview window, as far as fzf
is concerned the image placeholder is just normal text.

**Comment by junegunn** [comment]
> If the preview script is writing to /dev/tty

No, we are going to remove `> /dev/tty` from the preview command and let fzf capture the output and redirect it to `/dev/tty` later in a safe way.

> the image placeholder is just normal text.

I see. I wonder if fzf can see how many lines the image will take so that it can properly cut off the lines that are beyond the visible area. I'll have to find out.

**Comment by FusionX9000** [comment]
Image preview now works with the latest update kitty update (`0.30.1`). The following script can dynamically update the window size but changing fzf's `preview-window` direction will need changes in icat's `--place` value.

Using fish:
```fish
EXTERNAL_COLUMNS=$COLUMNS \
fzf \
--preview='kitten icat --clear --transfer-mode=memory --place="$COLUMNS"x"$LINES"@(math $EXTERNAL_COLUMNS-$COLUMNS)x0 --align center --stdin=no {} > /dev/tty' \
--preview-window "right,50%,border-left"
```

Using bash:
```bash
EXTERNAL_COLUMNS=$COLUMNS \
fzf --preview='kitten icat --clear --transfer-mode=memory --place="$COLUMNS"x"$LINES"@"$(($EXTERNAL_COLUMNS-$COLUMNS))"x0 --align center --stdin=no {} > /dev/tty' \
--preview-window "right,50%,border-left"
```

zsh doesn't update `$COLUMNS` env var, but it works with hard-coded `--place` values.

**Comment by junegunn** [comment]
Please see the commit message of d8188fce7b7bea982e7f9050c35e488e49fb8fd0.

It works for me, but more tests are welcome.

**Comment by sweetbbak** [comment]
Thank you so much! It's working really well. I've been testing all the image formats kitty can usually do and they all work. There is also no corruption of the lines and rows that fzf is made up of. I'll keep testing it out but its been great from what I've tested.

**Comment by jannis-baum** [comment]
> Also there is a little display corruption, the cursor seems to end up on the wrong line in fzf, no idea whats going on with that, the icat kitten will leave the cursor at the top left of the image, maybe fzf is making some other assumptions about the cursor position. If so the command above could be modified to add some cursor movement escape codes after icat to position the cursor where fzf would like.

Has anyone found a solution for this problem?

I have been playing around with it for a while and got pretty close to getting the image to display properly wherever the preview window is without breaking fzf's layout, but there is still an issue I can't solve.

```zsh
data=$(kitty icat \
    --clear \
    --transfer-mode=memory \
    --align center \
    --stdin=no \
    --unicode-placeholder \
    --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 \
    {})
printf "$(sed "s/\x1b7.*$//" <<< $data)"
printf "\x1b7$(sed "s/^.*\x1b7//" <<< $data)" 1> /dev/tty
```

The idea is to use icat's `--unicode-placeholder` and print the placeholder characters (everything from `\x1b7`) to the preview window and the graphics data (everything before) directly to `/dev/tty`.

With this the image is well-aligned in the preview window and fzf doesn't get messed up. The only issue that's left now is that the area of the terminal where the image would appear normally (i.e. at `0x0`) is blacked out. We can slightly mitigate this by placing the image at `((${COLUMNS} - ${FZF_PREVIEW_COLUMNS}))x0` for a `position=right` preview window instead so that it often ends up unnoticeable but this is not a proper solution, just a bad hack.

**Comment by sweetbbak** [comment]
@jannis-baum

Try something like this instead:
```sh
fd . ~/ssd/gallery-dl -e png | fzf --preview='kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {}'
```
`--align center` and `--place` are incompatible options if I remember correctly. The new PR that was merged detects the escape sequence for images and lets it pass through to the preview window unchanged. If you are dead set on using unicode placeholders for some reason then maybe check out `tupimage` but idk you would do that now.

**Comment by prurph** [comment]
Does anyone else have the issue where once displayed the kitty image preview doesn't disappear, either when a different non-image file is selected, or when fzf is exited? It looks like you can clear the image with `kitty icat --clear`, but I couldn't find a clean way to do this; trying to bind it to the `focus` event or even just adding `kitty icat --clear > /dev/null && bat -n --color=always {}` to the non-image part of the preview command appeared to cause strange behavior like non-image previews never loading. I'm using the [preview command suggested in the docs](https://github.com/junegunn/fzf#previewing-an-image).

**Comment by jannis-baum** [comment]
> Try something like this instead:

Ah, thank you so much! I guess I must have never tried without deleting the last line with `sed` like the docs suggest; doing this leaves me with no image at all so I figured the solution doesn't work. Like this it's perfect!

---

> Does anyone else have the issue where once displayed the kitty image preview doesn't disappear, both when a different non-image file is selected, or when fzf is exited? It looks like you can clear the image with kitty icat --clear, but I couldn't find a clean way to do this; trying to bind it to the focus event or even just adding kitty icat --clear > /dev/null && bat -n --color=always {} to the non-image part of the preview command appeared to cause strange behavior like non-image previews never loading.

@prurph I also had this issue but was able to fix it: I checked what `icat` prints to remove the image on `--clear`, which is `"\x1b_Ga=d,d=A\x1b\\"`. So if you just add the line

```sh
printf "\x1b_Ga=d,d=A\x1b\\"
```

to the unconditional section of your preview command instead of `kitty icat --clear` you will be good :)

**Comment by prurph** [comment]
Thanks @jannis-baum that worked! How'd you figure that out? `echo $(kitty icat --clear) | cat -v`?

Note that if you exit FZF with the preview up, it will still show. That could be avoided by binding the appropriate FZF keys and actions to print the appropriate characters as well as do what they're supposed to.

**Comment by jannis-baum** [comment]
> Thanks @jannis-baum that worked! How'd you figure that out? echo $(kitty icat --clear) | cat -v?

I used Python: `kitty icat --clear | python3 -c 'import sys; print(repr(sys.stdin.read()))'` but your way is nicer; you can also drop the echo and just use `kitty icat --clear | cat -v` :)

---

> Note that if you exit FZF with the preview up, it will still show. That could be avoided by binding the appropriate FZF keys and actions to print the appropriate characters as well as do what they're supposed to.

I open my fzf-finder with a keybinding and just always print the characters to clear images after running `fzf`. It's in [my fzf-dotfiles](https://github.com/jannis-baum/fzf-dotfiles) in case you're interested :)

**Comment by petobens** [comment]
Hi! I'm trying this feature. The following works:
```bash
fd --type f --hidden --follow --exclude .git --color=always | fzf --ansi --multi --preview='
if file --mime-type {} | grep -qF image/; then
    kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {} | sed \$d
else
    bat --color always --style numbers --theme TwoDark --line-range :200 {}
fi'
```
but if I write it like
```bash
fd --type f --hidden --follow --exclude .git --color=always | FZF_DEFAULT_OPTS="--ansi --multi --preview='
if file --mime-type {} | grep -qF image/; then
    kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {} | sed \$d
else
    bat --color always --style numbers --theme TwoDark --line-range :200 {}
fi'" fzf
```
it doesn't work due to a `sed` error. Any pointers? Thanks in advance

**Comment by sweetbbak** [comment]
this is old but I just wanted to say that in all of my testing, "sed \$d" or sed '$d' isnt needed. At least on Linux, I was unable to test this on Mac.

**Comment by petobens** [comment]
Hi @sweetbbak, without the sed bit I get the following error: `Error: strconv.Atoi: parsing "": invalid syntax`

**Comment by junegunn** [comment]
See the current discussion in #3567
