### ISSUE TITLE
[Bug] '--track' Option Does Not Work Correctly With '--tac' Option

### ISSUE THREAD

**Issue by alpiccioni** [junegunn/fzf#3234]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Steps:

1. Generate some random text which is diverse and sufficiently large:
```
base64 /dev/urandom | head -c 100000 > /tmp/test_file.txt  
```
2. Run 
```
FZF_DEFAULT_COMMAND="cat /tmp/test_file.txt" fzf --track --tac
```
5. Type in some random letters and select an item.
6. Clear the query.

Expected Result: Similar to '--layout=reverse-list', the track option should track the selection, such that when the query is clear, the item is still selected.

Actual Result: The item is not tracked correctly.

The option works with --layout=reverse-list and no list option fine, it appears to just be a --tac problem.

I also notice that when I start a sufficiently large, active stream with fzf --tac --track, the stream scrolls by for a little bit before stopping, but it doesn't keep the selected item , or stop at the start or end of the stream, usually stopping close to the middle. I'm unsure of what the issue there is.

Steps:
1. Run `FZF_DEFAULT_COMMAND="base64 /dev/urandom" fzf --track --tac`.
2. Observe the scroll bar and scrolling behaviour.

**Comment by junegunn** [comment]
I've tried to fix the bug, then I realized it can be extremely confusing to use `--track` with `--tac`.

```sh
seq 1000000 | fzf --tac --track
```

#### Scenario 1

Because of `--tac`, you would expect fzf to point to `1` at the beginning, the cursor is at the top of the screen. (See the scrollbar at the top-right corner)

<img width="461" alt="image" src="https://user-images.githubusercontent.com/700826/231069140-8ae5c26c-cd4b-4b04-a666-eadf9b94c93b.png">

Then you press `1`, suddenly 1 becomes the match with the highest score, it is now at the bottom of the screen. (Scrollbar at the bottom-right corner)

<img width="461" alt="image" src="https://user-images.githubusercontent.com/700826/231069161-12e5df8d-3922-4b41-86d9-b95c328fcff6.png">

Delete `1`, and the cursor is not at the top of the list.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/700826/231069182-1372d3d3-3069-4c5a-ac50-1ab306fce62a.png">

#### Scenario 2

The cursor is pointing to 1 as before.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/700826/231069140-8ae5c26c-cd4b-4b04-a666-eadf9b94c93b.png">

Then you type `2`, now there is no `1` in the list, then which item fzf should be pointing to now? Because fzf was previously pointing to the item with the lowest score, it is now pointing to the nearest match, which is the least significant match in the result.

<img width="461" alt="image" src="https://user-images.githubusercontent.com/700826/231069616-0371e91b-efd4-4d7e-b743-96513f6d7c2f.png">

#### Even with `--no-sort`?

Things are already too confusing and non-intuitive, then you add `--no-sort`, it's really hard to predict how fzf will perform.

#### So now what?

I'm thinking of disallowing `--track` with `--tac` because I don't think users will appreciate the mix.

**Comment by alpiccioni** [comment]
I think disabling `--track` and `--tac` when together would make sense to me from a UX standpoint. I think the examples you've provided would indeed be confusing. 

My user story here is that I'd like to be able to use track to scroll-lock and move to queries that I've found in a live input stream, but I'd also like to use tac to see the live feed scrolling by when not tracking. In furtherance of my usecase, would it be possible to have a lower-priority feature request to be able to switch between `--tac` and `--track` modes as a bind? 

My expected behaviour here (and I'm not sure how realistic this is) is that when `--tac` is enabled, the list will act as normal, scrolling from the bottom and keeping up with the input stream. When the binding for `--track` is pressed, items retain their position (similar to using `--layout=reverse-list --track`), but tracking begin. When `--tac` is pressed again, the list stops tracking and begins scrolling again.

Thanks for looking into this!

**Comment by junegunn** [comment]
I see, I'd rather not jump to a conclusion. I'll take some time and think about it.

**Comment by alpiccioni** [comment]
Thanks a lot for the fix! `track+clear-query` works a charm for jumping around logs!
