### ISSUE TITLE
Feature request: allow the command in `--bind` to open the original stdin

### ISSUE THREAD

**Issue by ericbn** [junegunn/fzf#3241]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

Hi 👋 

Following up on #1723 for using fzf as a visualization tool rather than a filter, I'm trying to use fzf to turn jq into an interactive tool.

I'd like to be able to make the command in `--bind` receive the original stdin that fzf received. So instead of:
```
FZF_DEFAULT_COMMAND='jq . myfile.json' \
    fzf --disabled --layout=reverse --no-info --bind=enter:print-query \
    --bind='change:reload:jq {q} myfile.json'
```
I would instead be able to do something like:
```
cat myfile.json  | \
    fzf --disabled --layout=reverse --no-info --bind=enter:print-query \
    --bind='change:reload-sync:jq {q} <&0'
```
The latter would allow piping the output of other commands directly to fzf without needing to write the output to a file first.

Not sure if this is stretching the purpose of fzf too far...

EDIT: I'm aware of the [tools](https://github.com/fiatjaf/awesome-jq#tools) that make jq interactive, or other tools like [fx](https://github.com/antonmedv/fx), [jless](https://jless.io/), [jellex](https://github.com/kellyjonbrazil/jellex), etc. that are also interactive JSON viewers, but using fzf has the benefit of both:
1. being generic and being able to turn virtually any other tool interactive, and
2. being powerful and allowing a lot of customization, for example we could [switch between the interactive tool filter and fzf's filter](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode).

**Comment by junegunn** [comment]
The standard input is a stream; we can't restart a stream. What fzf can do, is hold the raw input in memory and feed it to its child processes. But of course, that is not equivalent to rerunning the original command, so it may confuse the users. 

```sh
(date; echo $RANDOM) | fzf
```

And I don't think fzf having to hold the original raw input in memory just in case the child process may use it can be justified.

Since the suggested feature doesn't solve a problem that can't be circumvented, I'm going to pass on this one, but thanks for the suggestion.
