### ISSUE TITLE
Question About delimiter regex

### ISSUE THREAD

**Issue by cposture** [junegunn/fzf#3242]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

https://github.com/junegunn/fzf/blob/f1a96296525975ea7d4c45aebc4fed5117cecb72/src/tokenizer.go#L162

When the delimiter string is a regular expression, the line of code `text[begin:loc[1]]` takes `loc[1]` as the ending index, which includes the delimiter string in the slicing result. I feel this is not quite as expected.

for example: 
```
// @=@ is delimiter
text = "go@=@repo_name@=@path"
splited = [go@=@ repo_name@=@ path]
```
There is a solution, which is to take `loc[0]` instead, to exclude the delimiter string in the slicing result. Do you think this approach is feasible?

Solution:
```
	for _, loc := range locs {
		tokens = append(tokens, text[begin:loc[0]]) // <= change from loc[1]
		begin = loc[1]
	}
```

Expected result: 
```
text = "go@=@repo_name@=@path@=@"
splited = [go repo_name path]
```

thanks!

**Comment by junegunn** [comment]
I know this can be unintuitive, but this was the intended behavior.

* See https://github.com/junegunn/fzf/issues/1792#issuecomment-566931835 for why.
* Also see #2154

I would suggest pre-processing the input to have whitespace delimiters (such as tab, non-breaking spaces, etc.) since fzf will trim any trailing whitespaces.
