### ISSUE TITLE
Toggle preview combined with change-preview-window action broken

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3280]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh

## Problem / Steps to reproduce
- set a hotkey to `toggle-preview` combined with `change-preview-window`
- the hotkey toggles the preview window once and then never again

```sh
# the preview is visible, the hotkey hides it, but never shows it again when the hotkey is pressed again
fzf --bind '?:toggle-preview+change-preview-window:up' --preview 'cat {}' --preview-window nohidden

# the preview is hidden, the hotkey shows it, but doesn't hide it when the hotkey is pressed again
fzf --bind '?:toggle-preview+change-preview-window:up' --preview 'cat {}' --preview-window hidden
```

### bisect
- 23d8b78c

### expected behavior
- the preview window is toggled correctly as prior to 23d8b78c

### related ticket
- #3149 ticket has the same bisect commit
- #3113 ticket that was closed by the bisect commit

**Comment by junegunn** [comment]
The behavior does look strange, I'll look into it. But when I think about it, it's not so clear how it should behave.

Should `change-preview-window:up` always show the preview window regardless of the prior action because it's not `up:hidden`? What would be the intention of the user in this scenario?

Anyway, it is probably better idea to multiple expressions with a single change-preview-window binding.

```sh
fzf --bind '?:change-preview-window:hidden|up|hidden|right' --preview 'cat {}'
```

* https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0290

But then again, this is also confusing 🤔

```sh
# This doesn't seem to work. Oh, so we're inheriting hidden property?
fzf --bind '?:change-preview-window:up' --preview 'cat {}' --preview-window hidden

fzf --bind '?:change-preview-window:up,nohidden||right,nohidden|' --preview 'cat {}' --preview-window hidden
```

**Comment by LangLangBart** [comment]
> Should change-preview-window:up always show the preview window regardless of the prior action because it's not up:hidden?

no.

- the action before `change-preview-window:up` is `toggle-preview` and it should have the highest priority
  - if the preview is visible then hide it
  - if the preview is hidden then show it and only then consider settings from `change-preview-window`

> What would be the intention of the user in this scenario?

I have two preview pages, one shows information about a notification the other preview lists helpful infos, e.g. hotkeys.

I wanted the help preview to not `wrap` their lines in the preview. I thought it could be done with `change-preview-window(nowrap)`.

```sh
# Ref: related PullRequest https://github.com/meiji163/gh-notify/pull/37
# "wrap" lines in the notification preview
--bind "tab:toggle-preview+change-preview-window(wrap)+change-preview:$preview_notification"
# don't "wrap" lines in the help preview
--bind "?:toggle-preview+change-preview-window(nowrap)+change-preview:echo -e '$HELP_TEXT'"
```

Thanks for the workaround to use only `change-preview-window(...|...)` with different options separated by `|`. It solves the problem why I opened this ticket, even though I would have rather used `toggle-preview`, as it reads more cleanly.

```sh
# "wrap" lines in the notification preview
--bind "tab:change-preview-window(wrap:nohidden|hidden)+change-preview:$preview_notification"
# don't "wrap" lines in the help preview
--bind "?:change-preview-window(wrap:nohidden|hidden)+change-preview:echo -e '$HELP_TEXT'"
```

---

> But then again, this is also confusing 🤔

the behavior prior to 23d8b78 was the most intuitive.

**Comment by junegunn** [comment]
I think the confusion comes from the fact that `hidden` is a property of the preview window just like the other properties like size, position, or border shape, but you think the `hidden` is a state that is managed separately.

```sh
struct PreviewWindowProperties = {
  position
  size
  border
  hidden: boolean
}
```

The current implementation doesn't treat it any differently from other properties. I decided to do it this way because with the alternative layout, I felt it was really hard to reason about the state transition.

On `change-query action`, fzf restores the initial set of "properties" and applies the specified "properties", so when we run `fzf --bind '?:change-preview-window:up' --preview 'cat {}' --preview-window hidden`, this is what fzf is doing.

```
initialProperties = { right, 50%, hidden = true }

newProperties = initialProperties + { up } => { up, 50%, hidden = true }
```

And that's why, contrary to the common expectation, `nohidden` was required.

```
newProperties = initialProperties + { up, hidden = false } => { up, 50%, hidden = false }
```

The following example relies on the behavior, and I think it makes sense.

```sh
# Implementing toggle-preview behavior with change-window
fzf --bind '?:change-preview-window:nohidden|' --preview 'cat {}' --preview-window hidden
```

However, I do think it can be confusing and non-intuitive in many other cases.

```sh
# An ordinary user would expect "hidden -> right -> hidden -> up -> hidden",
# but it's actually "hidden -> right -> hidden -> hidden -> hidden",
fzf --bind '?:change-preview-window:nohidden||up|' --preview 'cat {}' --preview-window hidden
```

So we're going to have to treat `hidden` property differently so that it's less confusing and doesn't break scripts that rely on the current behavior.

`change-preview-window` will still inherit the initial set of properties, but we're going to override `hidden` to true, if the specification is not empty. (i.e. why would you change-preview-window to "up:50%" when you don't want to see it? It doesn't make sense.)

```sh
# hidden -> up -> hidden -> up ...
fzf --bind '?:change-preview-window:up|' --preview 'cat {}' --preview-window hidden

# hidden -> right -> hidden -> up ...
fzf --bind '?:change-preview-window:nohidden||up|' --preview 'cat {}' --preview-window hidden
```

But, this means `toggle-preview+change-preview-window:up` will always show the preview window on `up` position and the `toggle-preview` becomes a no-op.

> * the action before `change-preview-window:up` is `toggle-preview` and it should have the highest priority

Combined actions are run in the specified order so that the last one has the highest priority.

**Comment by junegunn** [comment]
And `fzf --bind '?:toggle-preview+change-preview-window:up'` not showing anything is indeed a bug that is unrelated to the discussion. Caused by the reorganization of the actions.

https://github.com/junegunn/fzf/blob/e619b7c4f4e0da09b87a239b8f52ad909bb5f1e0/src/options.go#L1983-L1986
