### ISSUE TITLE
binds which launch child instances of fzf hang the terminal

### ISSUE THREAD

**Issue by 0ion9** [junegunn/fzf#3291]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Nested invocation simply hangs the terminal. I've tested in both fish (my main shell) and bash, both inside tmux and outside tmux.

Toy example of what I mean, req. `fd`:
`fd -tf -d1 . | fzf -m --bind 'alt-space:transform-query(printf "%s\n" 1 foo bar | fzf -m)'`

Interaction works as normal, until pressing alt-space. Pressing alt-space makes the terminal unresponsive, until Ctrl+C is pressed (presumably terminating the child fzf process). Hence it's impossible to interact with the child process.

It is notable that other programs which display an interactive TUI, such as smenu, **do** work as a child process, ie 
`fd -tf -d1 . | fzf -m --bind 'alt-space:transform-query(printf "%s\n" 1 foo bar | smenu -T)'`
-- you can select item(s) or navigate between items successfully. So it's *specifically fzf* that doesn't seem to be able to cope with being launched inside an instance of fzf.

**Actual use case:**

FWIW, my actual use case is simple: 
Let the user choose words from the currently selected line (`{}`), and append them to the query string.

In my implementation, I define a function `fzf-words` which is, via binding, passed the query string and current selection, and itself internally invokes fzf.  This doesn't appear to make any difference to interactive behaviour vs the toy example above. FWIW, debugging does show that the terminal hangs at exactly the point when fzf is launched. This function also behaves in the expected way when used outside of fzf (ie. one can select words extracted from $2, and the returned output is these words appended to the value of $1)

**Comment by junegunn** [comment]
This is by design. Except for `execute` action, any action that runs an external command cannot be used with an interactive program. Because in most use cases, the external process should complete immediately with a result and users don't want to see the screen flickering at the moment (it's the very reason we have separate `execute-silent`). The documentation is lacking this detail, so patches on clarifying the limitation are welcome.

So no, you can't use `transform-query` this way. The only option would be to use `execute` to start an interactive program and make it send `change-query` action to the `--listen`inig port of the original fzf process.

FWIW, if you're always on tmux like me, fzf-tmux will work, because it will open in another pane (or in a popup window).

```sh
fzf --bind 'space:transform-query(seq 10 | fzf-tmux -p)'
```
