### ISSUE TITLE
Allow the current line placeholder to be evaluated in the preview when no line is selected

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3353]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh

## Problem / Steps to reproduce

- since d649f5d8265b6c94ad5f2898d0c8851f9505e538 one can check if the `{q}` (query) placeholder is empty in the preview

```sh
: | fzf --preview-window nohidden \
    --preview "set -x; [[ -z {q} ]] && echo empty"
```

<img src="https://github.com/junegunn/fzf/assets/92653266/1ffdf159-e91f-4c49-a26f-f0893b888dc7" width="800">

- could this behavior also be added to this placeholder `{}` (current line) ?

```sh
: | fzf --preview-window nohidden \
    --preview "set -x; [[ -z {} ]] && echo empty"
```

- interestingly, when using `{}` in combination with `{q}` it does get evaluated

```sh
: | fzf --preview-window nohidden \
    --preview "set -x; [[ -z {q} && -z {} ]] && echo empty"
```

<img src="https://github.com/junegunn/fzf/assets/92653266/f9ee0bb1-6ba5-4f45-a7a3-9641e2d7d12c" width="800">

### related 
- #2759
  -  d649f5d8265b6c94ad5f2898d0c8851f9505e538

**Comment by junegunn** [comment]
> * interestingly, when using `{}` in combination with `{q}` it does get evaluated

This is by design.

https://github.com/junegunn/fzf/blob/a7c41f3fcd6c6db4ff25828218bea281439dd1ba/src/terminal.go#L2447-L2449

So, putting `{q}` in your command even (if you don't need it) is one workaround you can use to unconditionally trigger a preview update, though it may feel a bit hacky.

"Preview" feature was designed for "previewing" the current selection, so not showing a preview when there is no match was a sensible decision, I think. But I can imagine a user wants to show some message in the preview window even in that case, but then again, the message will likely contain the current query (`[[ -z {} ]] && echo "No match found for {q}" || cat {}`), and the aforementioned workaround kicks in.

**Comment by LangLangBart** [comment]
Your reasoning is sound. It was just counterintuitive that one would be evaluated but not the other, thus making a report.

In the beginning, I simply evaluated `{}` in the preview for an empty list to see if my idea would actually work. And it never did.

After some time, I just added `{q}`, and it worked. Knowing that, it was fine.
