### ISSUE TITLE
Question: Including hidden files in search

### ISSUE THREAD

**Issue by wavded** [junegunn/fzf#337]
Haven't found an option for it.  Maybe I'm missing something?

**Comment by junegunn** [comment]
```sh
find . | fzf

export FZF_DEFAULT_OPTS='find .'
fzf
```
makes sense?

**Comment by wavded** [comment]
Thanks for the quick response, I am currently using:

```
let $FZF_DEFAULT_COMMAND = 'ag -l -g ""'
```

In my `.nvimrc`, how would I also incorporate that?

**Comment by junegunn** [comment]
No idea, `man ag` :)

**Comment by wavded** [comment]
Got it.  Needed to add the `--hidden` flag.

**Comment by wavded** [comment]
That allowed searching on .git as well.  So this was the final command I ended up using for future reference:

```
let $FZF_DEFAULT_COMMAND = 'ag --hidden --ignore .git -l -g ""'
```

**Comment by netei** [comment]
My 2 cents : you don't need `-l` if you already have `-g`

**Comment by wavded** [comment]
@netei that works, thanks for the tip.

**Comment by Aster89** [comment]
What if one wants to search including **only** one hidden directory? (I want to include `.vim`, but including all hidden files seems to slow this tool down.)

**Comment by john9631** [comment]
Just in case anyone's using ripgrep the command line equivalent is:

`rg --hidden -l "" | fzf`

and the zshrc line is:

`export FZF_DEFAULT_COMMAND='rg --hidden -l ""'`

**Comment by marcelpaulo** [comment]
My 2 cents. With:

`ag --hidden --ignore .git -g ""`

you don't get directory names, only file names. I decided to use:

`find . -printf "%P\\n"`

for both `FZF_DEFAULT_COMMAND` and `FZF_CTRL_T_COMMAND`

**Comment by piersy** [comment]
Not sure why you would use ag or rg to find files instead of find. Running the three options on my local machine i can see that find is the fastest, and is massively faster than rg.
```
$ sudo time find . -type f -not -path '*/\.git/*' | wc -l
2.40user 3.21system 0:05.67elapsed 99%CPU (0avgtext+0avgdata 7464maxresident)k
0inputs+0outputs (0major+11502minor)pagefaults 0swaps
1401803
```

```
$ sudo time rg --hidden -l "" | wc -l
13.25user 47.54system 0:33.70elapsed 180%CPU (0avgtext+0avgdata 316396maxresident)k
17791040inputs+0outputs (0major+95227minor)pagefaults 0swaps
697078
```

```
$ sudo time ag --hidden --ignore .git -l -g "" | wc -l
2.86user 3.20system 0:06.27elapsed 96%CPU (0avgtext+0avgdata 3664maxresident)k
9112inputs+0outputs (1major+1193minor)pagefaults 0swaps
990647

```

**Comment by marcelpaulo** [comment]
> Not sure why you would use ag or rg to find files instead of find

For common usage, it's quicker to write, just that.

**Comment by junegunn** [comment]
Because they respect `.gitignore`.

**Comment by jimafisk** [comment]
Using [fishshell](https://fishshell.com/) I had to put the following in ~/.config/nvim/init.vim: `let $FZF_DEFAULT_COMMAND = "find -L"` 

Taken from [alx741 on reddit](https://www.reddit.com/r/neovim/comments/48ymsn/fzf_how_to_show_hidden_files/d0nrhft/).

**Comment by elquimista** [comment]
To my understanding, `fzf` is a generic fuzzy finder. It's up to user to provide pool to `fzf` (via STDIN, find, fd, ag, ripgrep, ps, ls etc). It's just that `fzf` uses ubiquitous `find` internally by default. My point is that option to include hidden files in search result is relevant to those provider utils like `find`, thus this is not a right place to open issue here.

**Comment by jswny** [comment]
Can anyone explain why you would use `rg --hidden -l ""` for FZF instead of `rg --hidden --files`? Using the latter seems to make `rg` about as fast as `find` I've found:
```sh
$ time rg --hidden --files | wc -l
0.12user 8.76system 0:01.30elapsed 682%CPU (0avgtext+0avgdata 10372maxresident)k
0inputs+0outputs (0major+2695minor)pagefaults 0swaps
14877
$ time rg --hidden -l "" | wc -l
0.40user 27.75system 0:10.81elapsed 260%CPU (0avgtext+0avgdata 15220maxresident)k
0inputs+0outputs (0major+4232minor)pagefaults 0swaps
11442
$ time find . | wc -l
0.15user 2.85system 0:03.02elapsed 99%CPU (0avgtext+0avgdata 1564maxresident)k
0inputs+
```

**Comment by imadjamil** [comment]
> My 2 cents : you don't need `-l` if you already have `-g`

I even had a  [$FZF_DEFAULT_COMMAND failed] when `-g` was present. Using it in .zshrc

**Comment by piharpi** [comment]
Me: Looking for the best answer 👀️

**Comment by gfsd3v** [comment]
For anyone looking for ripgrep solution that show hidden files but ignore .git folder here's the code:

`export FZF_DEFAULT_COMMAND='rg --files --hidden -g "!.git" ' `

**Comment by Odnes** [comment]
>  It's just that `fzf` uses ubiquitous `find` internally by default. My point is that option to include hidden files in search result is relevant to those provider utils like find, thus this is not a right place to open issue here.

This doesn't sound true to me. It could only be true if fzf invoked it with some option to ignore hidden files, which isn't documented in the man page, and would anyway shift responsibility for this behavior to fzf.

**Comment by Roy-Orbison** [comment]
For a more efficient version of `find` you should prune directories, then (optionally) filter out specific files, e.g.:

for `fzf`
```sh
export FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name '\''*.tags'\'' -printf '\''%P\n'\'
```
and for `fzf.vim`
```viml
let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name ''*.tags'' -printf ''%P\n'''
```

Pruning prevents the command from ever traversing excluded directories, which can significantly improve performance.

**Comment by vovcacik** [comment]
Might be of interest:
https://github.com/junegunn/fzf/blob/764316a53d0eb60b315f0bbcd513de58ed57a876/src/constants.go#L60-L61

**Comment by wiskani** [comment]
> For a more efficient version of `find` you should prune directories, then (optionally) filter out specific files, e.g.:
> 
> for `fzf`
> 
> ```shell
> export FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name '\''*.tags'\'' -printf '\''%P\n'\'
> ```
> 
> and for `fzf.vim`
> 
> ```viml
> let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name ''*.tags'' -printf ''%P\n'''
> ```
> 
> Pruning prevents the command from ever traversing excluded directories, which can significantly improve performance.

Where are put this commands???

**Comment by Roy-Orbison** [comment]
@wiskani `fzf` is a shell command, so you would put the `export` in your `.bashrc`. The `let` would go in your `.vimrc`.

**Comment by hungpham3112** [comment]
> For a more efficient version of `find` you should prune directories, then (optionally) filter out specific files, e.g.:
> 
> for `fzf`
> 
> ```shell
> export FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name '\''*.tags'\'' -printf '\''%P\n'\'
> ```
> 
> and for `fzf.vim`
> 
> ```viml
> let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name ''*.tags'' -printf ''%P\n'''
> ```
> 
> Pruning prevents the command from ever traversing excluded directories, which can significantly improve performance.
How can I show hidden directory in Windows using fzf.vim? The command above doesn't seem to work for me.

**Comment by Roy-Orbison** [comment]
@hungpham3112 First check that the command lists the desired folders, if it doesn't, it's not FZF's fault. Test with this in your shell (I assume you're using msys shell because you're on Windows):
```sh
find . \! \( -type d -path ./.git -prune \) \! -type d \! -name '*.tags' -printf '%P\n' | sort | less
```

**Comment by dave-kennedy** [comment]
@Roy-Orbison's tip can be simplified and improved in a few ways:

> ```
> \! \( -type d -path ./.git -prune \)
> ```

`\!` is redundant here. Also, this ignores .git directories that aren't a direct descendant of the current directory. If you want to exclude those, `-path '*/.git/*' -prune` should work better.

> ```
> \! -type d \! -name '*.tags'
> ```

This might just be a personal preference but I'd prefer to keep directories in the results. I don't do much C programming these days so don't really care about tags either.

> ```
> | sort | less
> ```

If you want alphabetical sorting, fzf has an option for that. I prefer the default sort by relevance so I would leave this part off too.

Altogether, this is what I use:

```
export FZF_DEFAULT_COMMAND="find . -path '*/.git/*' -prune -o -printf '%P\n'"
```

**Comment by Roy-Orbison** [comment]
@dave-kennedy Whilst the `\!` may be redundant in your particular invocation, using the form **with** it is preferable. If you modify the command in any way, including relying on `-print` being default, you can get bad results, e.g.:
```sh
find . \( -type d -path ./.git -prune \)
```
That finds *only* the git dir, which I doubt is what anyone wants. You didn't actually explain why you used the OR (`-o`), which is what's preventing that failure for you.

Tags files [are not just for programming in C](https://github.com/universal-ctags/ctags/tree/master/parsers), and it's mainly to demonstrate how to exclude file types, a common requirement.

The `| sort | less` was never part of the normal command, that's purely for inspecting the tree that your command would pass to fzf.

The `-printf '%P\n'` is only to produce neater output. There's little benefit to the `./` prefix on every line.

Keeping dirs in results and ignoring all git dirs are both good ideas. You'd be better off pruning the git dirs themselves by changing `-path '*/.git/*'` to `-path '*/.git'`.

**Comment by hungpham3112** [comment]
> @hungpham3112 First check that the command lists the desired folders, if it doesn't, it's not FZF's fault. Test with this in your shell (I assume you're using msys shell because you're on Windows):
> 
> ```shell
> find . \! \( -type d -path ./.git -prune \) \! -type d \! -name '*.tags' -printf '%P\n' | sort | less
> ```

I tested it with git-bash and it didn't seem work for me.

I also add 
```
let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d \! -name ''*.tags'' -printf ''%P\n'''
```
to my vimrc but nothing happen.

**Comment by dave-kennedy** [comment]
Thanks for the explanation @Roy-Orbison. With our powers combined I think this is even better:

```
export FZF_DEFAULT_COMMAND="find \! \( -path '*/.git' -prune \) -printf '%P\n'"
```

**Comment by Roy-Orbison** [comment]
@hungpham3112
> I tested it with git-bash and it didn't seem work for me.

I think running Vim under git-bash might be different that running it directly from Windows' interface, different environments. Have you [installed FZF properly](https://www.reddit.com/r/vim/comments/96fp3x/windows_fzf_and_gvim/)? Is [FZF available to git-bash](https://stackoverflow.com/questions/61943778/is-it-possible-to-use-fzf-command-line-fuzzy-finder-with-windows-10-git-bash)?

**Comment by kertkukk** [comment]
While **fzf** is getting results and you are getting `don't have required permission errors` you might want to redirect stderr to` /dev/null`. 

To do that add `2> /dev/null` to the end of search.

I.e: export `FZF_DEFAULT_COMMAND='rg --hidden -l "" 2> /dev/null'`

**Comment by mentalisttraceur** [comment]
I feel like a lot of these issues, including repeats such as #3150, wouldn't have happened if consistency+simplicity wasn't compromised for usability.

If I never expected `fzf` to do something useful by default if stdin is a terminal, I wouldn't have spent any amount of time asking "how do I get `fzf` to show hidden files?", because it would be very clear in my head that the question doesn't apply, because `fzf` is a fancy interactive *pipe* rather than a file finder.

But since `fzf`'s out-of-the-box experience is to pretend to be a file finder, users like me spend time looking through `fzf --help` and `man fzf` for "hidden", then turn to web search, and then end up here, instead of just jumping directly and intuitively from `fd ... | fzf` to a more relevant "how do I get `fd` to show hidden files?"

Not saying you made the wrong design choice, but I think it's useful to explicitly call out the link between the choice of having `fzf` default to a fancy `find ... | fzf` and users expecting that `fzf` would be the place to control which files are found/selected.

**Comment by junegunn** [comment]
I would expect the users to read the README page to understand what this program is.

The first paragraph of the README page says:

> fzf is a general-purpose command-line fuzzy finder.
>
> It's an **interactive Unix filter** for command-line that can be used with any list; files, command history, processes, hostnames, bookmarks, git commits, etc.

There is no mention of fzf being a "file finder". And the very first example shown on the page is using fzf as a filter.

https://github.com/junegunn/fzf#usage

> fzf will launch interactive finder, read the list from STDIN, and write the selected item to STDOUT.
>
> `find * -type f | fzf > selected`

I've realized many users just don't read. They end up spending hours digging through the internet and creating duplicate issues on the issue tracker rather than spending just 5 minutes reading the official documentation.

Having said that, it may help to add some more explanation also to the man page, but I don't understand why one would install a program before understanding what it is by reading the project page first.

**Comment by mentalisttraceur** [comment]
@junegunn I totally relate to everything you say,

Unfortunately, one of the biggest ways users discover programs is word-of-mouth and seeing usage in the wild.

So if a program "makes it big", it doesn't matter what we write in our READMEs, because that'll be like a fourth or fifth source of information that a user sees. By then they've already come to feel like they basically do understand what a program is, from context+usage.

Think of it as a *user education* corollary to [Hyrum's Law](https://www.hyrumslaw.com/):

given enough users of a tool,
it doesn't matter how you explain the tool,
any idea consistent with at least one usage,
will be naturally reached by somebody.

But more importantly: the more common or accessible a way of using the tool is, the more it will "guide" user expectations. Users see that the most default, uncomplicated `fzf` call starts by *recursively finding all files*. If their brain is familiar with stuff like `find`, they are likely to associate the two, and we can say they're wrong, but we must not miss how this learning/thinking strategy works pretty well in many situations, and is often reinforced by life experience.

To generalize Hyrum's law a bit:

*At scale, empirically observable behavior tends to beat documentation.*

**Comment by mentalisttraceur** [comment]
> it may help to add some more explanation also to the man page

Yes! exactly! Now to narrow that down a bit:

It *will* help *a lot* if searching for "hidden | file" in `fzf` manpage or help text leads finds a minimal example and explanation. For example:

> Despite the file-oriented default behavior, `fzf` does not have special handling for files. So if you want to do things like finding hidden files, you control that in the program that feeds `fzf`, not in `fzf` itself. For example:
>
>     find . -type f | fzf

**Comment by mentalisttraceur** [comment]
<details><summary>

Also, not a suggestion, but just a concept I found useful to think about here: [click to expand]

</summary>

Instead of pruning `-path */.*` in `defaultCommand`, we *could* default `--query` to `!^. !/. ` if all of these are true:

1. stdin is a terminal,
2. `FZF_DEFAULT_COMMAND` is not set, and
3. `--query` is not given.

This achieves the same useful out-of-the-box default behavior, with interesting UX tradeoffs.

The downsides are:

* two cryptic negated patterns are already pre-enter but gains some flexibilityed in the query,
* sometimes a novice user will backspace those pre-entered patterns and be confused or frustrated about the result or how to undo it,
* the count shows `(n-hidden_files)/n` instead of `n/n`, which is less obvious, and
* there is a hit to performance.

The upsides are:

* anyone who thinks to ask "how do I include hidden files? (within `fzf` or just as the smallest change to `fzf` default behavior)" has an answer readily discoverable by hands-on experimentation right there,
* those two pre-entered patterns are an organic opportunity for experimentation and discovery,
* the user can infer
* the `x/n` count is still pretty easy to infer - it still goes down as you type in things and down as you delete patterns, and
* there is a net win for accessible flexibility, because a piece of `defaultCommand` (which can only be used or replaced *in full* without modifying `fzf` itself) moves into the much more mutable query line.

To me personally, this way of decomposing/decoupling the pieces of logic involved, and not having this special case of filtering done outside of `fzf`'s own filtering, is more appealing.

But I suspect the choices you made make more intuitive first-contact sense to more people, and have a more accessible learning curve, so I'm not suggesting you change it.

I just think it's useful to see how this alternative achieves many of the same UX benefits while gaining a few significant and relevant other benefits at relatively small cost. 

</details>

**Comment by themightyoarfish** [comment]
I am using the `:Files` command of the vim integration, which says it runs `FZF_DEFAULT_COMMAND` if it is defined. I am not defining it, but it still runs, so what do I do here to stop it from ignoring hidden files?

**Comment by Roy-Orbison** [comment]
@themightyoarfish https://github.com/junegunn/fzf/issues/337#issuecomment-977592444

**Comment by hungpham3112** [comment]
> @hungpham3112
> 
> > I tested it with git-bash and it didn't seem work for me.
> 
> I think running Vim under git-bash might be different that running it directly from Windows' interface, different environments. Have you [installed FZF properly](https://www.reddit.com/r/vim/comments/96fp3x/windows_fzf_and_gvim/)? Is [FZF available to git-bash](https://stackoverflow.com/questions/61943778/is-it-possible-to-use-fzf-command-line-fuzzy-finder-with-windows-10-git-bash)?

Sorry for late reply. My problem is that I need the universal command for both Windows and Linux. The `find` command only work for Linux, not for Windows. I'm not a big fan of MSYS2 environment, I use vim with fzf in the default Windows environment like Powershell and cmd.exe so I wonder if there is alternative for `find . \! \( -type d -path ./.git -prune \) \! -type d \! -name '*.tags' -printf '%P\n' | sort | less` in Windows.

**Comment by Roy-Orbison** [comment]
@hungpham3112 There is no universal command for finding files across platforms, but you don't need one, and again don't put the `| sort | less` in the fzf command.
``` vim
if has('unix')
    let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d -printf ''%P\n'''
else
    let $FZF_DEFAULT_COMMAND='Get-ChildItem -Recurse -Exclude .git -File -Name' "untested
endif
```

**Comment by hungpham3112** [comment]
>     let $FZF_DEFAULT_COMMAND='Get-ChildItem -Recurse -Exclude .git -File -Name' "untested

The command doesn't work. I'm not sure if fzf.vim can use pwsh inside it?

**Comment by Roy-Orbison** [comment]
@hungpham3112 Mate, you need to google stuff before you spam issue threads with support requests. I wrote `untested`, because I didn't test that command but it was more than enough to get you started. See also `:h 'shell'` in Vim.

**Comment by hungpham3112** [comment]
> @hungpham3112 Mate, you need to google stuff before you spam issue threads with support requests. I wrote `untested`, because I didn't test that command but it was more than enough to get you started. See also `:h 'shell'` in Vim.

For anyone want to run fzf to search for hidden file which can work in Windows termimal or inside vim.

```
if has('unix')
    let $FZF_DEFAULT_COMMAND='find . \! \( -type d -path ./.git -prune \) \! -type d -printf ''%P\n'''
else
    let $FZF_DEFAULT_COMMAND='dir /b /s /a-d | findstr /vi "\\scoop\\"'
    # I exclude scoop home because it's big and doesn't contain useful file for me
endif
```

The problem with this command is `dir` really slow.
