### ISSUE TITLE
scoring scheme documentation confusing

### ISSUE THREAD

**Issue by PatrickF1** [junegunn/fzf#3387]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

## Problem / Steps to reproduce

The man page for scheme says this
```
      --scheme=SCHEME
              Choose scoring scheme tailored for different types of input.

              default  Generic scoring scheme designed to work well with any type of input
              path     Scoring scheme for paths (additional bonus point only after path separator)
              history  Scoring scheme for command history (no additional bonus points).
                       Sets --tiebreak=index as well.
```
It is confusing for someone who hasn't read fzf source code. It leaves me with these questions
- what are "additional bonus points"? There are no further mentions of it in the manpage
- if history has no additional bonus points, then how is that different from "default" which has no mention of bonus points so presumably doesn't use them?
- when it says "bonus point only after path separator", is it only the last path separator or all path separators?
- why is giving bonus points after path separator good for dealing with paths?
- why is the history scheme good for searching command history?

I've already read https://github.com/junegunn/fzf/issues/2909 and https://github.com/junegunn/fzf/issues/2930 and am still not confident I know the answers...

If I may ask a second question, would you recommend using `--scheme=history` for searching command history and git log? I'm guessing yes for command history and no for git log? Context: https://github.com/PatrickF1/fzf.fish/pull/302

Btw, once I understand it, I'm happy to PR in the documentation updates if you'd like. Being an OSS author myself, I know how time consuming and difficult writing documentation is.

**Comment by junegunn** [comment]
I agree that the current documentation is incomplete, but yet at the same time, I'd like to hide implementation details that few will (want to) understand by not mentioning stuff like 'bonus point'.

If you want to know more about the algorithm, the best resource is the top comment section of https://github.com/junegunn/fzf/blob/master/src/algo/algo.go

A matching character at a special position, such as at a word boundary or after a non-alphanumeric character, etc, is given a bonus point. The bonus point was the same regardless of the type of the special position, but 0.32.0 changed that.

https://github.com/junegunn/fzf/releases/0.32.0

> Different bonus points to different categories of word boundaries

It seemed like a good idea, but soon after the version was released, I and some other users realized the new algorithm didn't work great for the command history. When you search for a command, you're likely looking for a more recent command.

```
...
100 git log gradle
...
1000 ./gradle test
```

The query `gr` will match both items. Prior to 0.32.0, `./gradle test` will be the result with the highest score, okay that's great, but the new algorithm of 0.32.0 prefers `git log gradle` because `gr` after space gets a higher bonus point than `gr` after `/`, which is usually not desirable.

That's why I had to add `--scheme`.

> If I may ask a second question, would you recommend using --scheme=history for searching command history and git log? I'm guessing yes for command history and no for git log?

You'll have to experiment with the options to see which gives better results, but I think `--scheme=history` makes sense in that case because the chronological ordering is more important and you don't want old and new commits to be mixed in the list.

**Comment by PatrickF1** [comment]
Thanks for your response!

> I agree that the current documentation is incomplete, but yet at the same time, I'd like to hide implementation details that few will (want to) understand by not mentioning stuff like 'bonus point'.

You make a great point and I agree. In that case, maybe just provide the same level of detail that you just did in your response. Both too little detail and too much detail is bad in man pages, and I think what you just wrote was the wrote amount of detail.

> You'll have to experiment with the options to see which gives better results, but I think --scheme=history makes sense in that case because the chronological ordering is more important and you don't want old and new commits to be mixed in the list.

Thanks I'll test both. But to clarify, you are saying that you think `--scheme=history` might be good if I want to avoid mixing old and new commits?

**Comment by PatrickF1** [comment]
Nvm, I re-read your comment and I see that you were saying that `--scheme=history` is probably a good idea for git log. I read the source code and it makes sense to me as well. Anyway, when I was reading https://github.com/junegunn/fzf/commit/6fb41a202a97ad3f2437f6e5aee8890268560412, I was surprised that this line has since been removed:

```
No additional bonus points are given so that we give more weight to the chronological ordering.
```

 IMO, it's valuable. I would advice adding it back.

**Comment by junegunn** [comment]
> Anyway, when I was reading [6fb41a2](https://github.com/junegunn/fzf/commit/6fb41a202a97ad3f2437f6e5aee8890268560412), I was surprised that this line has since been removed:

The line is still there, in [CHANGELOG](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0330).

Anyway, what do you think about this?

```diff
diff --git a/man/man1/fzf.1 b/man/man1/fzf.1
index dc21832..5e93f50 100644
--- a/man/man1/fzf.1
+++ b/man/man1/fzf.1
@@ -57,9 +57,9 @@ Choose scoring scheme tailored for different types of input.
 .br
 .BR default "  Generic scoring scheme designed to work well with any type of input"
 .br
-.BR path "     Scoring scheme for paths (additional bonus point only after path separator)
+.BR path "     Scoring scheme for file paths
 .br
-.BR history "  Scoring scheme for command history (no additional bonus points).
+.BR history "  Scoring scheme for command history (or any list where chronological ordering is important).
          Sets \fB--tiebreak=index\fR as well.
 .br
 .TP
```

**Comment by PatrickF1** [comment]
That's much better! If I may offer an even better doc, I'd do
```
Scoring scheme well suited for file paths
```
and
```
Scoring scheme well suited for command history or any input where chronological ordering is important
```

**Comment by junegunn** [comment]
Thanks! Pushed to master.
