### ISSUE TITLE
Ctrl-c to exit jump and fzf?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3412]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have this ` <..> | fzf --bind '::jump-accept' ` --> after press `:`, to exit fzf I have to press `ctrl-c` to `abort` two times to exit fzf --> I want press one `ctrl-c`.

Is there a way to do that?

**Comment by tmpm697** [comment]
Maybe press `:` again to dimiss jump but keep `ctrl-c` to dismiss all at one?

**Comment by junegunn** [comment]
There's no such option at the moment. Other bindings are simply ignored in jump mode. You have to first exit the mode before using other bindings.

**Comment by tmpm697** [comment]
any chance for this to be `fixed`? i wouldn't consider this as a bug or feature but a bit annoy when using.

**Comment by junegunn** [comment]
It's not clear that the suggested approach can be universally agreed upon. If I'm not mistaken, you discovered the jump feature pretty recently, but the option was initially introduced 7 years ago and there has been no complaints regarding the current behavior. Granted, I don't know how many users are using the feature. I personally never use it because I think it's easier and more natural to type in a few more characters to pinpoint the match than to vertically move the cursor.

**Comment by tmpm697** [comment]
> It's not clear that the suggested behavior can be universally agreed upon. If I'm not mistaken, you discovered the jump feature pretty recently, but the option was initially introduced 7 years ago and there have been no complaints regarding the current behavior. Granted, I don't know how many users are using the feature. I personally never use it because I think it's easier and more natural to type in a few more characters to pinpoint the match than to vertically move the cursor.

Unfortunately I adopted it heavily to my workflow, I think most ppl will simply ignore it or did not find a way to use it.

Here how I do:
```
cmd pattern<trigger fzf>
```
--> pattern will be insert to fzf and boostrap the search right a way with it, then I also have `jump:accept` active ready to choose the correct one.

Probably you're in a case that you need to narrow the search first but here I already type the search from shell, so `jump:accept` is essential to use.

But then I will in a case that I need to exit it quickly.

**Comment by mrcnski** [comment]
FWIW, I just found out about jump and it would be nice to add this feature!

> It's not clear that the suggested behavior can be universally agreed upon. 

Instead of changing the default, you could just add some new function like `fzf-quit-all` that a user can bind to Ctrl-C or escape.

> If I'm not mistaken, you discovered the jump feature pretty recently, but the option was initially introduced 7 years ago and there have been no complaints regarding the current behavior.

But how many people even know this is there? There are no instances of `jump` in the readme or in `ADVANCED.md`, and when I searched on ~Google~ Kagi this issue was the only relevant result. Unless you're one of the 0.01% of users who read the manpage in detail, I struggle to see how one would even find out about this. It could be mentioned in the docs (with an example of how to bind it) because it's a cool feature!

**Comment by junegunn** [comment]
The reason I'm not advertising `jump` feature is that I don't personally use it and I don't think it's the most natural way to use the finder. You have to hit a custom key to go into the jump mode, find the position of the desired match in the list, peek to the left to learn which key to press, press that key, and hit enter to complete the process. But I would instead just append more characters to the query to further narrow down the list, ideally bringing the desired one to the top position of the result, so that there is little or no need for vertical movement. I feel this is more streamlined because there is no context/mode switching involved. So I wanted the users to internalize this simple workflow first before looking for a separate mode.

Having said that, it is possible to implement such an action that can be bound to a key. But as I mentioned above, the bindings don't work in the jump mode, so we have to make an exception for it in the code.

**Comment by tmpm697** [comment]
> The reason I'm not advertising `jump` feature is that I don't personally use it and I don't think it's the most natural way to use the finder. You have to hit a custom key to go into the jump mode, find the position of the desired match in the list, peek to the left to learn which key to press, press that key, and hit enter to complete the process. But I would instead just append more characters to the query to further narrow down the list, ideally bringing the desired one to the top position of the result, so that there is little or no need for vertical movement. I feel this is more streamlined because there is no context/mode switching involved. So I wanted the users to internalize this simple workflow first before looking for a separate mode.
> 
> Having said that, it is possible to implement such an action that can be bound to a key. But as I mentioned above, the bindings don't work in the jump mode, so we have to make an exception for it in the code. But I think only allowing that `abort-all` action in the jump mode can be confusing.

Still please add this, as I still need an exit way to *redeem* to shell prompt state immediately.

**Comment by tmpm697** [comment]
> FWIW, I just found out about jump and it would be nice to add this feature!
> 
> > It's not clear that the suggested behavior can be universally agreed upon.
> 
> Instead of changing the default, you could just add some new function like `fzf-quit-all` that a user can bind to Ctrl-C or escape.
> 
> > If I'm not mistaken, you discovered the jump feature pretty recently, but the option was initially introduced 7 years ago and there have been no complaints regarding the current behavior.
> 
> How many people know this is there? There are no instances of `jump` in the readme or in `ADVANCED.md`, and when I searched on ~Google~ Kagi this issue was the only relevant result. Unless you're one of the 0.01% of users who read the manpage in detail, I struggle to see how one would even find out about this. It could be mentioned in the docs (with an example of how to bind it) because it's a cool feature!
> 
> Edit: this wasn't intended to sound rude, I appreciate all the work and thoughtful design behind fzf!

Really like this idea, `fzf-quit-all` or smth similar that
able to map to `ctrl-c/escape` or other keybindings.

I used `'load:+jump-accept'` in all of my fzf functions,
mostly I do patterns first then if I can able to direct jump,
give it a go. But if not, I can have option to dismiss it and
be back to shell instantly.

**Comment by junegunn** [comment]
A more flexible approach would be to add events, namely `jump` and `jump-cancel`, so you can get the desired behavior and replace `jump-accept` action.

```sh
fzf --bind space:jump,jump:accept,jump-cancel:abort

**Comment by tmpm697** [comment]
> A more flexible approach would be to add events, namely `jump` and `jump-cancel`, so you can get the desired behavior and replace `jump-accept` action.
> 
> ```shell
> fzf --bind space:jump,jump:accept,jump-cancel:abort
> ```

I think it's ok, more clarification than `quit-all`, or can just be `jump:cancel` that internally mapped to `:abort`

**Comment by junegunn** [comment]
I'm not going to change the default behavior. The additional events will allow users to fine-tune the behavior.

```sh
# Default behavior
fzf --bind space:jump

# Same as jump-accept action
fzf --bind space:jump,jump:accept

# Accept on jump, abort on cancel
fzf --bind space:jump,jump:accept,jump-cancel:abort

# Change header on jump-cancel
fzf --bind 'space:change-header(Type jump label)+jump,jump-cancel:change-header:Jump cancelled'
```

**Comment by tmpm697** [comment]
I have this:
```
zsh -df
echo "1\n2" | fzf --bind 'load:+jump-accept' --bind 'ctrl-y:abort,jump-cancel:abort'
```

When i try to use `ctrl+n/p` to *not* abort jump but trying to dismiss the accept and navigate the list, it does not work, it will just `abort`

**Comment by junegunn** [comment]
In the current implementation, any key that is not one of the jump labels simply cancels the jump mode. So there's no difference between pressing CTRL-P and pressing ESC or pressing `!`. CTRL-P will only cancel the jump mode and it will not trigger any action that is bound to the key. So, looks like you're out of luck.

One possibility is to export the name of the last key pressed  (a la `$FZF_ACTION`) so you can conditionally trigger a different set of actions using `transform`. I'll think about it.

**Comment by tmpm697** [comment]
> In the current implementation, any key that is not one of the jump labels simply cancels the jump mode. So there's no difference between pressing CTRL-P and pressing ESC or pressing `!`. CTRL-P will only cancel the jump mode and it will not trigger any action that is bound to the key. So, looks like you're out of luck.
> 
> One possibility is to export the name of the last key pressed (a la `$FZF_ACTION`) so you can conditionally trigger a different set of actions using `transform`. I'll think about it.

yeah, but it's kinda useless if any key just abort fzf --> this will probably affect any user that currently use jump.

**Comment by junegunn** [comment]
This will do.

```sh
fzf --bind 'space:jump,jump:accept,jump-cancel:transform:[[ $FZF_KEY =~ ctrl-c ]] && echo abort'
```
