### ISSUE TITLE
`--help`-output and manpages are both out of sync with the actual code

### ISSUE THREAD

**Issue by calestyo** [junegunn/fzf#3470]
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Problem / Steps to reproduce

While preparing a commit to update `fzf`’s own bash completion, I've noted that the `--help`-output and manpages are also outdated.

It seems that both, "fixed" values (like e.g. `no` for `--color`), and options (like e.g. `--algo` in the `--help`-output and `--no-black` in the manpage).

Whoever takes this work up … when being lazy and trying to "automate" this a bit:
```
$ cat ./fzf.1 | tr -d "\"'" | xargs -n 1 | sort -u | grep '^--'
```
may e.g. be used to find out all options that **are** in the manpage.

Cheers,
Chris.

**Comment by junegunn** [comment]
Some of the differences are intentional. I have intentionally left out some obscure options that we may deprecate in the future in the `--help` output, which is probably more accessible for an average user than the man page.

A few examples:

* `--black` (and `--no-black`) is a legacy option that was added to work around an issue of ncurses in the old days. But  1. fzf has moved away from ncurses, 2. and the identical effect can now be achieved with `--color bg:black`. So it's no longer recommended to use this option and we only kept it for backward compatibility. To phase it out over time, we don't mention it in `--help` output. I think it's about time we should remove it from the man page as well.
* The omission of `--algo` is also intentional. It's an advanced option that few users will actually need, and I think it's better for an average user to not know/worry about it at all. We may also phase this out in the future. But that's TBD.

**Comment by calestyo** [comment]
Hmm well, okay if you like it that way, then it's of course up to you.

I though it would have been easier to main if everything were always in. And also easier for users, especially also with respect to deprecation or "expert/obscure" option, if such options are clearly marked as such.

Just close if you feel so.
