### ISSUE TITLE
Ctrl+t Alt+c not sorting by default?

### ISSUE THREAD

**Issue by gotbletu** [junegunn/fzf#3497]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

Not sure if this is the desire result for `Ctrl+t` / `Alt+c` but it not sorting the list from a-z.
Ctrl+r sorts it by history number so was expecting Ctrl+t/Alt+c sort by a-z?
https://imgur.com/PEOt4V9.png

**Comment by junegunn** [comment]
No sorting. By default, the bindings simply use "find" command to list the candidates.

### ALT-C
https://github.com/junegunn/fzf/blob/278dce9ba6f383930654b9a591f1143b0c422907/shell/key-bindings.bash#L46-L47

### CTRL-T
https://github.com/junegunn/fzf/blob/278dce9ba6f383930654b9a591f1143b0c422907/shell/key-bindings.bash#L21-L24

---

But you can use any command by setting environment variables.

https://github.com/junegunn/fzf#key-bindings-for-command-line

For example,

```sh
if command -v fd > /dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --strip-cwd-prefix'
  export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git --strip-cwd-prefix'
  export FZF_CTRL_T_COMMAND='fd --type f --type d --hidden --follow --exclude .git --strip-cwd-prefix'
fi
```

So you can sort the list if you want, but you probably don't want to, because if you do, fzf will get nothing until the traversal is complete and the list is sorted.

**Comment by gotbletu** [comment]
Ok that make sense, ill keep it as it when it need to use it.
Thanks for the examples, i'll just make another hotkey for limited find maxdepth and sorting instead =)
