### ISSUE TITLE
Feature request: Add option to change key bindings for multi-select that override --bind bindings

### ISSUE THREAD

**Issue by jacklanoie** [junegunn/fzf#3523]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Feature Request
Add an option that takes arguments and behaves exactly like `--bind` but takes priority over `--bind` key bindings when multi-select is enabled.

The intended use of this would be in the default options for users that have a set of key bindings that they prefer when multi-select is enabled that differ from the bindings that they prefer when multi-select is disabled.

Example usage (where `--multi-bind` is the proposed option):

`export FZF_DEFAULT_OPTS="--bind tab:down,shift-tab:up,enter:accept --multi-bind enter:toggle,alt-enter:accept"`

In this example, with `--multi` disabled this `--multi-bind` option would be ignored entirely. With `--multi` enabled the `tab` and `shift-tab` navigation bindings would still be bound, the `enter` binding would be overridden to be `toggle`, and `alt-enter` would behave as `accept`.

**Comment by junegunn** [comment]
So if I understand you correctly, you're looking for a dynamic version of `$FZF_DEFAULT_OPTS` that changes depending on some condition. e.g. existence of `--multi` argument.

Adding `--multi-bind` isn't enough, because someone might want different options (not just bindings) depending on different conditions. Say, `--color light` during the day, `--color dark` during the night.

If I really had to, I would write a wrapper script or a function that implements the dynamic injection of default options.

```sh
# Just a silly example
fzf() {
  if [[ $* =~ --multi ]]; then
    command fzf --color light "$@"
  else
    command fzf "$@"
  fi
}
```

**Comment by jacklanoie** [comment]
You understood me correctly. This solution works well enough for my purposes. Thank you for suggesting an alternative.
