### ISSUE TITLE
go install command does not work because of replace directive

### ISSUE THREAD

**Issue by bokunodev** [junegunn/fzf#3577]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues (i tried)

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

I couldn't install `fzf` by using `go install` command with latest go version.
```
~$ go install github.com/junegunn/fzf@latest

go: github.com/junegunn/fzf@latest (in github.com/junegunn/fzf@v0.0.0-20240109033114-e4d0f7acd516):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

related issue: https://github.com/golang/go/issues/40276#issue-659471259

**Comment by raviqqe** [comment]
It might be a bit out of scope. But if `fzf` can keep supporting `go install` officially probably with install its instructions in `README.md`, it's helpful for me.

The use case is that I install `fzf` via `go install` in an environment initialization script used in different environments (e.g. Linux distros and macOS.) The reason to use `go install` instead of platform-specific package managers (e.g. `apt`) or "portable" ones (e.g. Homebrew) is that package managers built into languages are the most portable and reliable in my experience.

**Comment by junegunn** [comment]
Removed the `replace` directive in the go.mod file and changed the name of the forked module. Not sure if this is the best way to do it, but now `go install github.com/junegunn/fzf@master` works.
