### ISSUE TITLE
[Feature Request] Add flag for including hidden files

### ISSUE THREAD

**Issue by mcp292** [junegunn/fzf#3617]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

This is a feature request to add a flag for including hidden files. This way it can be aliased and easily tracked and maintained. Environment variable definitions get lost and are less flexible. A flag can be used at will. I understand the `export` can be put in my `.bashrc`.

I would prefer this
```sh
alias fzf='fzf --hidden'
```

over this
```sh
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
```

in my `.bashrc`.

This issue has come up multiple times  (#337, #634, #3150).

**Comment by junegunn** [comment]
My stance hasn't changed a bit. fzf is a text filter, not a file system traversal program, and I'm against adding any options for that. 

* `--hidden` doesn't make sense for any other types of input.
* I recommend using fd or rg over using find instead because they respect .gitignore files and they are said to be more performant.
