### ISSUE TITLE
Abbreviation search

### ISSUE THREAD

**Issue by sergei-dyshel** [junegunn/fzf#366]
I'd like to implement slightly modified fuzzy search which matches only beginning of words and not anywhere inside the word. For example: `ab` would match `alpha_beta` but won't match `alpha_andbeta` (because `b` doesn't start the word). This feature is usually not implemented in today's "fuzzy" searches but is, IMHO, very useful because it filters results much better.

How hard would be to add this to FZF? Where should I start looking?

**Comment by sergei-dyshel** [comment]
Strange, after changing `FuzzyMatch` in `src/algo/algo.go` to behave as I proposed, the console utility still matches anywhere in the string. How could that be?

**Comment by junegunn** [comment]
`FuzzyMatch` is the right function. Given that your implementation is correct, it should work.

**Comment by sergei-dyshel** [comment]
The problem was that you use absolute `github.com/junegunn/...` paths in import directives. I had to change these to my repo so that correct `algo.go` is picked.

**Comment by junegunn** [comment]
Yes, it's a well known problem in go import paths, google it and you'll find what people are doing to deal with the issue.

Anyway, I'm going to close the issue since I'm not planning to add it to fzf. It's an interesting idea that has some potential, but most of the time, I do want to match letters that are not at the beginning of a word. For example, for `sergei-dyshel`, it's more natural and straightforward for me to just start typing `serg` than to think about the exact initials beforehand. And when I need more precise matching, extended-search mode (`-x`) works extremely well for me. Also, there are more details to consider if we want to properly support the feature. e.g. unicode characters, how to define word boundaries, what about uppercase letters, what if someone wants to customize it, how to toggle between the mode and the ordinary matcher, etc.

**Comment by sergei-dyshel** [comment]
That's is the point! `sergdy` is abbreviation for `sergei-dyshel` ( `-` is considered word separator) as well as `sd` and `s-d`. That's how most of the people most of the time search files, identifiers - they see them as sequence of short words so they start to type first letters of words and expect to see words starting with these letters.

Personally, I'm using *fzf* exclusively for history matching in *zsh*, since I'm working 9 hours a day in Linux terminal and I use multi-line commands frequently (thanks to your tool, it made a revolution in my workflow :smile: ). So, if I want to repeat `sudo pkill qemu` command, I'd type `spq` but "traditional" fuzzy matcher will suggest me half of my 10,000 lines of history which contain these letters *anywhere* in the line. With abbreviation search, I can get to this command much faster.

Anyway,  I do realize that there is much more work to do in order make this feature properly and integrate with *fzf*. But if people will demand it, I'd like to contribute!

**Comment by junegunn** [comment]
I see. Reverse history search is an exceptional case since sorting is disabled by default (ctrl-r needed to enable). Considering sorting, the reason we type in `ser` instead of just `s` is that it gives higher priority to the "better" matches. We don't always know the exact initials of the words. Let's assume that we do know that the entry we want starts with `sergei` but we do not remember the initials of the words that follow. So we need to see what are the options. Simply typing in `s` is unlikely to bring the entries of our interest to the front. So we type in additional letters, `serg`, then we'll likely to see `serg-c`, `sergei-dyshel`, `sergei-e...`, etc. Aha, `dyshel` is what we want! So we type in `d` to further narrow down the candidates.

So my point is that even though the idea makes sense in some cases, it is definitely not a panacea, and we need a way to use the original matcher as well. One idea might be to add a special syntax to the extended-search mode, but we have to be careful not to make things complex.

**Comment by sergei-dyshel** [comment]
We'll work it out! :smile:

In the meantime, I've just released my first [VIM plugin](https://github.com/sergei-dyshel/vim-abbrev-matcher) which implements my idea for CtrlP and Unite - two popular fuzzy finders.  There, in GVim world where FZF is unfortunately not available,  all irrelevant candidates just make things so slow, so I had to propose something. Let's see what people think of it!
