### ISSUE TITLE
FZF_COMPLETION_OPTS to not follow symbolic link on **<TAB> completion being ignored

### ISSUE THREAD

**Issue by SadBoiLlama** [junegunn/fzf#3778]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.51.0 (260a65b0)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

trying to use the **<TAB> completion for nvim while in my home dir and steam is installed and has a symbolic link to root
i have --walker=file,dir,hidden set in both my default opts and the completion ops and for everything else it works fine but trying to use ls **<TAB> or nvim **<TAB> is annoying

**Comment by junegunn** [comment]
We currently override `--walker` option because it should be different depending on the command.

https://github.com/junegunn/fzf/blob/4bedd33c593ab0cb750e17c42750048904fdf7fb/shell/completion.bash#L300

If we universally apply `--walker=file,dir,hidden`, then `cd **` will also list files and `cat **` will also list directories, and that is not what we want.

The only option at the moment is to [define `_fzf_compgen_path` and `_fzf_compgen_dir`](https://github.com/junegunn/fzf?tab=readme-ov-file#settings) but that is not ideal because we can't use the built-in walker in that case.

**Comment by SadBoiLlama** [comment]
is there a way i can have a general case that uses what i want it to use and then only override it for the specific cases already implemented?
or if i just change that line can i get the functionality i want?

**Comment by junegunn** [comment]
One way is to define `_fzf_comprun` function as shown in the README page. But then you'll have to list all the commands in the function.

 We probably need to add `$FZF_COMPLETION_PATH_OPTS` and `$FZF_COMPLETION_DIR_OPTS`.

**Comment by junegunn** [comment]
With cd8d736a9f4074de3aafdf3c10fff75cfb6c5ed0 you can,

```sh
FZF_COMPLETION_PATH_OPTS="--walker=file,dir,hidden"
FZF_COMPLETION_DIR_OPTS="--walker=dir,hidden"
```
