### ISSUE TITLE
Action to clear selections if there are any else exit fzf. (Feature request)

### ISSUE THREAD

**Issue by smashgen** [junegunn/fzf#3805]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.50 (devel)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I checked the man page and I don't think there is an action that already does this. I think it would be useful to have an action that clears selections if there are any else exit fzf, similar to the cancel action.

**Comment by LangLangBart** [comment]
The `transform`[^1] action enables the user to execute an action conditionally.

---

#### Example

The fzf tool sets the environment variable `FZF_SELECT_COUNT`[^2]. If no selections are present, the operation is aborted. Otherwise, it deselects the matches upon pressing <kbd>⌃ Control</kbd> + <kbd>A</kbd>.


```bind
look foo | fzf \
  --bind 'load:select-all' \
  --bind 'ctrl-a:transform:((FZF_SELECT_COUNT)) &&
    echo "deselect-all" ||
    echo "abort"'
```

[^1]: [changelog 0.45.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0450)
[^2]: [changelog 0.46.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0460)
