### ISSUE TITLE
Tiebreak parameter of length or end does not produce the expected results

### ISSUE THREAD

**Issue by mattie20** [junegunn/fzf#3837]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.46.1

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

The command
```
fzf --tiebreak=end
```
produces with a search term of "engine"
```
Documents/c++code/pascal.wiki/engine.md
.
.
.
Documents/Archive/College/ME4201/AIAA EOP/Gas Turbine Engine Pictures/J79.JPG
> Documents/Archive/College/ME4201/AIAA EOP/Gas Turbine Engine Pictures/CFM56 High Bypass Turbofan Engine.jpg
```
I have omitted the hundred or so files in-between. The one which I would imagine should be below the second file is at the top. I'm not sure why the first file is prioritized and most of the others with "engine" at the very end are so far away, or if this is the expected behavior.

When used with "tiebreak=length" the following similar result happens:
```
Documents/c++code/pascal.wiki/engine.md
.
.
.
Documents/Archive/College/ME4201/AIAA EOP/Gas Turbine Engine Pictures/J79.JPG
> Documents/Archive/Financial/Bills/Mastering engineering payment.pdf
```

**Comment by junegunn** [comment]
Does `--scheme=path` help?

```sh
fzf --tiebreak end --scheme path --query engine << EOF
Documents/c++code/pascal.wiki/engine.md
Documents/Archive/College/ME4201/AIAA EOP/Gas Turbine Engine Pictures/J79.JPG
Documents/Archive/College/ME4201/AIAA EOP/Gas Turbine Engine Pictures/CFM56 High Bypass Turbofan Engine.jpg
EOF
```

It's because in the default scheme, `Engine` after a space gets a higher bonus score than `engine` after `/`.

https://github.com/junegunn/fzf/blob/3ee1fc203406debab432dbf3cb67f37ea7cb3d30/src/algo/algo.go#L178-L189

`--scheme=path` makes fzf use the same bonus point for both cases.

---

Come to think of it, it's a little strange that we don't use `--scheme=path` as the default when using fzf for files (i.e. using its default walker), let me see what I can do.

**Comment by junegunn** [comment]
Hopefully, 64faaf61f3030c006392bce7e370200b912ad001 will help users better understand the options.
