### ISSUE TITLE
Vim keybinds / modal input

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [junegunn/fzf#384]
So, I figure this is a long-shot, reading through a few other issues from this project; but I *also* saw that nobody (as far as I could find) had opened an issue asking for this, specifically.

So: as a feature-request, I'd *really* like to see a ‘vim-mode’; with some of vim's most basic line-editing keybinds set, and implemented such that `esc` kicks the user into a pared-down version of command-mode. This is how my Zsh is configured to operate (and damn-near every other CLI program I use); and this was the *first feature* I searched for when comparing the various interactive finder-filter programs / implementations out there.

(I understand that this is a lot of work, and may be outside the scope of this project … but it seemed worth asking for.) <3

**Comment by junegunn** [comment]
Thanks for the suggestion but the answer is no.

- My fzf session usually doesn't last longer than 5 seconds. I just type in a few characters and press enter. Mode switching is clearly an overkill for fzf.
- I use vim, and I can confidently say that I'm not bad at it. But I don't use vi/vim-mode in command line, not just because the implementation is somewhat incomplete, but also because I'm much more productive with the default Readline key bindings (and [I'm not the only one](https://www.reddit.com/r/vim/comments/267vrv/i_am_tim_pope_crafter_of_plugins_ama/chopa7v)). The most useful ones are all available on fzf.
- As you mentioned, implementing and maintaining requires an enormous amount of work and introduces huge complexity to the project. It's not a good use of my (or anyone's) time.

**Comment by ELLIOTTCABLE** [comment]
<3

**Comment by kungfubeaner** [comment]
I was just going to ask for the same feature,  just  a  --modal option on the command like that would enable modal mode where u need to type i  for insert mode where u can fuzzy find   but starting up with j and k for up and down..  Glad I found this so I don't open up a feature request.  I can still keep my hope up though.

**Comment by cohml** [comment]
Seem KA moot at this point but I'll toss in another upvote for this feature request. I am hugely productive with modal editing on the command line, and it hurts my brain to context switch back to readline bindings exclusively for editing queries in fzf. This one niggle aside, fzf is da bomb.

**Comment by siddhantladdha** [comment]
Sorry for necro bumping this. Fzf is da best ❤️.
In some cases where I use it as a search engine in an always open terminal window of its own, I have had too many queries with *jjjkk*.

Adding a comment for anyone landing on this issue.
If you don't have too advanced of a use case and years worth of script baggage built around fzf, `gum filter` might be worth a try for a few such cases. I am not fully certain about the performance differences, hence no comments about it.
Hope this helps!
https://github.com/charmbracelet/gum#filter
