### ISSUE TITLE
0.53.0: --bind behaviour changed?

### ISSUE THREAD

**Issue by 097115** [junegunn/fzf#3865]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Consider this:

    q=''
    q=$(printf "aaa\nbbb\nccc\n" | fzf --bind='f1:execute(printf bbb)+abort' --bind='f2:execute(printf ccc)+accept')
    printf "\n$q\n"

Prior to 0.53.0, pressing F1 would result in setting `$q` to `bbb`, while pressing F2 would result in setting it to `cccaaa`

Now, with 0.53.0, pressing F1 results in printing `bbb` to stdout and leaving `$q` unset, while pressing F2 results in printing `ccc` to stdout and setting `$q` to `aaa`.

So, my question, probably, is if the changes were intentional, and if so, then how can I now replicate the prior-0.53.0 behaviour?

Thanks :)

**Comment by junegunn** [comment]
Yes, it is intentional. `execute` action is for executing an external program in the alternate screen without leaving fzf, and it isn't supposed to affect the final output of fzf.

For example, when you run `selected=$(ls | fzf --bind 'ctrl-o:execute:vim {}')`, you don't want any output from Vim in the final output of fzf. Also, prior to 0.53.0, you would have to redirect the standard output of Vim to `/dev/tty` for it to work properly in this case. Considering the original purpose of `execute`, this was confusing and not ergonomic.

Another mistake here is using `execute` where you should be using `execute-silent`. `execute` runs the command in the alternate screen, you'll notice screen flashing.

```sh
fzf --bind 'space:execute-silent(ls)+accept' --height 30%
```

---

> how can I now replicate the prior-0.53.0 behaviour?

### 1. Use `print` action

```sh
fzf --bind 'f1:print(f1)+accept' fzf --bind 'f2:print(f2)+abort'
```

### 2. Use `become` action

```sh
fzf --bind 'f1:become:echo f1' --bind 'f2:become:echo f2; exit 1'
```

**Comment by 097115** [comment]
So, for the reference, it's 

    --bind 'f2:print(ccc)+accept'

instead of

    --bind='f2:execute(printf ccc)+accept'

to get `ccc aaa` from the example above. And (with optional `exit 1` if needed)

    --bind 'f1:become:echo bbb' 

instead of

    --bind='f1:execute(printf bbb)+abort'

to get `bbb`.

While certainly looking more logical and more consistent, it's quite a breaking change, I'd say...

**Comment by 097115** [comment]
Forgot to say thanks for the explanation :)

**Comment by junegunn** [comment]
> it's quite a breaking change

Yeah, but I'd say it was a misuse of a feature, like the spacebar heating case.

**Comment by mooreye** [comment]
> So, for the reference, it's
> 
> ```
> --bind 'f2:print(ccc)+accept'
> ```
> 
> instead of
> 
> ```
> --bind='f2:execute(printf ccc)+accept'
> ```
How to make it print `ccc` on a new line isntead of with space, like it could have been done before?
