### ISSUE TITLE
Question: What's the expected behavior with --nth and --with-nth together?

### ISSUE THREAD

**Issue by malkomalko** [junegunn/fzf#3873]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.1 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi There,

After reading the man page, my expectation would be that I can control which fields are displayed in the list (--with-nth) and which fields can be used to search over (--nth). However, If I had something like `--nth=1,4.. --with-nth=4..` I can not use the 1st column to search and filter the list since it's not displayed.

Thanks

**Comment by LangLangBart** [comment]
> What's the expected behavior with --nth and --with-nth together?

Initially, I assumed that any values assigned to either flag would reflect the original data. However, `--nth` applies solely to what remains visible after the transformation by `--with-nth`.

Thus, one must anticipate the structure after the transformation and accordingly assign the `--nth` flag.

```sh
printf "%s\n" {1..9} | xargs -n 3
# 1 2 3
# 4 5 6
# 7 8 9
```


❌ No results for the commands below, as **1** is not visible, and **5** is excluded because of `--nth 2..`.
```sh
printf "%s\n" {1..9} | xargs -n 3 | fzf --with-nth 2.. --nth 2.. --filter="1"
printf "%s\n" {1..9} | xargs -n 3 | fzf --with-nth 2.. --nth 2.. --filter="5"
```

✅ Result found

```sh
printf "%s\n" {1..9} | xargs -n 3 | fzf --with-nth 2.. --nth 2.. --filter="9"
# 7 8 9
```

**Comment by junegunn** [comment]
What @LangLangBart described is correct. `--nth` is applied after `--with-nth` transformation is done, and fzf doesn't allow searching against hidden parts. I thought this was mentioned somewhere in the manual page, but it doesn't seem to be.
