### ISSUE TITLE
FZF (from nvim) doesn't bind function keys correctly (for example f4)

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#393]
with the following `.nvimrc`

```
set nocompatible
set rtp+=~/.fzf
```

`FZF_DEFAULT_OPTS="--multi --bind 'f4:toggle-all,ctrl-o:toggle-all'" nvim`

Do : 

`:FZF` 

`ctrl-o` works to toggle-all, but `f4` doesn't

`f4` works correctly from withih `vim` with the same vimrc

`FZF_DEFAULT_OPTS="--multi --bind 'f4:toggle-all,ctrl-o:toggle-all'" vim`

I guess it is a problem in upstream @tarruda

**Comment by junegunn** [comment]
Thanks for the heads up, but this issue is not specific to fzf. So I suggest that you discuss it on the nvim issue tracker. An easier way to reproduce (without fzf):

- Start nvim
- <kbd>F1</kbd> should bring up help window
- `:term`
- Start nvim inside the term window
- <kbd>F1</kbd> does not work there

**Comment by netei** [comment]
Ok, I've opened https://github.com/neovim/neovim/issues/3497 for this
