### ISSUE TITLE
Fzf window not showing in process substitution using zsh 

### ISSUE THREAD

**Issue by luigir-it** [junegunn/fzf#3947]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I made this simple function
```
uuu() {
    while read file
    do
      echo ${file}
    done < <(ls -1 | fzf)
}
```
Fzf window does not appear, the function hangs, but the process is spawn. Also, after `ctrl-c`, the process will still be alive. Killing it with `kill -s KILL <process-id>` leaves it in a _defunct_ state, meaning that is somehow still attached to the current shell.

In bash it works as expected.

If I replace `< <()` with `<<< "$()"` or `< =()` it will work.

Is this the correct behavior? I don't know how zsh handle process substitution, but according to the documentation, as far as I understand it, they both rely on /dev/fd or named pipes, based on the system.

[Doc for bash](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html)
[Doc for zsh](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Process-Substitution)

**Comment by LangLangBart** [comment]
Issue was added with [Commit [5c1654]](https://sourceforge.net/p/zsh/code/ci/5c1654) (zsh >=5.8).
- Related Threads:
  - [[BUG] Ctrl-C stops working after process substitution](https://www.zsh.org/mla/workers/2018/msg00941.html) 
  - [[PATCH] Fix ctrl-c not working after process substitution](https://www.zsh.org/mla/workers/2019/msg00252.html)

Fixed with [Commit [ddfc81]](https://sourceforge.net/p/zsh/code/ci/ddfc81a2b81e) (zsh >5.9).
- Related Threads:
  - [Bug: reading from tty inside process substitution](https://www.zsh.org/mla/workers/2023/msg01023.html)



---

> If I replace < <() with <<< "$()" or < =() it will work.

Try disabling the `monitor` option.

```sh
uuu() {
  setopt localoptions no_monitor
  while read file; do
    echo ${file}
  done < <(ls -1 | fzf)
}
```

or reorder the function

```sh
 uuu() {
  ls -1 | fzf | while read file; do
    echo ${file}
  done
}
```

or use a zsh version `<=5.7 || >5.9`

---

However, `fzf` is not doing anything wrong here, and the issue might be closed.
