### ISSUE TITLE
--walker-root not used

### ISSUE THREAD

**Issue by skarasov** [junegunn/fzf#4027]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (fc69308)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

shell ps 7.4.5

- run command from drive c:
```
cd "$(fzf --walker=dir --walker-root='e:\\')"
```
- cd to any dir in drive e:
- run again 
```
cd "$(fzf --walker=dir --walker-root='e:\\')"
```
- listed current dir but root of 'e:\'

**Comment by junegunn** [comment]
@charlievieth I'm also seeing this unexpected behavior of "root" argument of fastwalk.Walk. Any idea?

```sh
# When run in c:\, this recursively traverses all files under c:\ as expected
cd c:\
fzf --walker-root 'c:\'

# But when not in c:\, this lists hidden files right in the current directory incorrectly prefixed by 'c:\'
cd Users
fzf --walker-root 'c:\'
```

<img width="586" alt="image" src="https://github.com/user-attachments/assets/50ff66ea-2492-4106-8036-3ec8f60873b9">

**Comment by junegunn** [comment]
If I add `.` after `:`, it works as expected.

```sh
fzf --walker-root 'c:\.'
```

**Comment by skarasov** [comment]
Non of this works (from my home dir):
```
cd $(fzf --walker-root='c:.' --walker=dir)
cd $(fzf --walker-root='c:\.' --walker=dir)
cd $(fzf --walker-root='c:\\.' --walker=dir)
```
blank selection ^

**Comment by skarasov** [comment]
As a workaround:
```
cd "e:\$(ls -path 'e:\' -r -ad -n -d 5 | fzf)"
```
but it slooooooooow... even cutted

**Comment by skarasov** [comment]
Maybe its because somewhere walker path/root trimmed from last `\`
`cd c:\` - cd to root of c:
`cd c:` - cd to current dir on c:

**Comment by junegunn** [comment]
It looks like the problem is that fastwalk trims the trailing path separators from the root argument.

https://github.com/charlievieth/fastwalk/blob/a984dac737cfff226f4e1c64646887c058ef6990/fastwalk.go#L628-L638

So `c:\` becomes `c:`, yielding unexpected results as shown in the following image.

<img width="630" alt="image" src="https://github.com/user-attachments/assets/09ae843c-9948-4b5e-b786-5d09f4256ff4">

> Non of this works (from my home dir):

Right, it doesn't work with the latest version of fzf. I accidentally tested with an older version.

**Comment by junegunn** [comment]
Commenting out this line of fastwalk library fixes the issue,

https://github.com/charlievieth/fastwalk/blob/a984dac737cfff226f4e1c64646887c058ef6990/fastwalk.go#L437

but then you get entries with double path separators (i.e. `c:\\...` instead of `c:\...`).

**Comment by charlievieth** [comment]
@skarasov and @junegunn Thank you for reporting this I'll looking into it tonight / tomorrow.

**Comment by charlievieth** [comment]
Thanks for the investigation. This is a bug in `fastwalk` due to [cleanRootPath](https://github.com/charlievieth/fastwalk/blob/a984dac737cfff226f4e1c64646887c058ef6990/fastwalk.go#L628) removing the trailing backslash from the disk designator `C:\` which changes it from a fully qualified (`C:\`) to a relative path (`C:`). Therefore, `C:` is interpreted as the current working directory on drive C instead of the root of drive C ([win32 docs](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths)). I will push a fix later today.

For context, this logic was originally added to make joining paths simpler since it eliminated the need to check if the parent path ends with a file path separator.
