### ISSUE TITLE
[Feature request] Placeholder expression for space-separated query string

### ISSUE THREAD

**Issue by letuanhai** [junegunn/fzf#4033]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

- Use case:
Building on [the example in ADVANCED.md](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode-using-a-single-key-binding) to use `fzf` as interactive `rg` launcher, I also want to pass additional options to `rg`.
Currently, the whole query string `{q}` is replaced as a single-quoted string.
<img width="999" alt="SCR-20241010-iwyn" src="https://github.com/user-attachments/assets/2d5d82d3-b9d4-4ec3-b696-23c541bfc3c2">
I want to have a placeholder expression that will be replaced by a list of single-quoted strings by separating the query string by space characters, essentially doing shell word splitting. For the previous example, I expect the query string to be replaced with: `'--glob=!*.go' 'one'`.

- What I have tried so far:
I've tried replacing `{q}` with the evironment variable `$FZF_QUERY` in the event binding (i.e. `--bind "start:reload:$RG_PREFIX $FZF_QUERY"`), but it does not get replaced with the query string.

Any other suggestions without the need for the additonal placeholder expression would also be great.

**Comment by LangLangBart** [comment]
> * evironment variable `$FZF_QUERY` in the event binding (i.e. `--bind "start:reload:$RG_PREFIX $FZF_QUERY"`), but it does not get replaced with the query string.

The `FZF_QUERY` is an environment variable exported by `fzf` that you must escape when used with double quotes; otherwise, it will expand immediately.

```sh
--bind "start:reload:$RG_PREFIX \$FZF_QUERY"
```

---

> [!NOTE]
> _fzf runs the command with `$SHELL -c` if `SHELL` is set, otherwise with `sh -c`_

> essentially doing shell word splitting.

Try the `(z)`[^1][^2] and `(Q)`[^3] parameter expansion flags on `FZF_QUERY`.

```sh
export test_string='--glob !*.go "immediately after"'
zsh -fxc 'print -- ${(Q)${(z)test_string}}' 
# +zsh:1> print -- --glob '!*.go' 'immediately after'
# --glob !*.go immediately after
```


**TEST:** Search for the string `immediately after` in the `fzf` repo with the option `--glob !*.go` passed along.
```sh
: | SHELL=$(which zsh) fzf \
  --bind "start:become:rg --column --line-number --no-heading \${(Q)\${(z)FZF_QUERY}}" \
  --disabled \
  --query '--glob !*.go "immediately even"'

# CHANGELOG.md:1160:28:    - Vim plugin will stop immediately even when the source command hasn't finished
```

Instead of `SHELL=$(which zsh)`, one can also use the `--with-shell "$(which zsh) -c"` flag. The latter allows passing additional options. This feature was added in version `0.51.0`[^4].

[^1]: [zsh: 14 Expansion](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion-Flags)
[^2]: [Zsh Parameter Expansion z](https://www.bashsupport.com/zsh/parameter-expansion-flags/z/)
[^3]: [Zsh Parameter Expansion Q](https://www.bashsupport.com/zsh/parameter-expansion-flags/q_uppercase/)
[^4]: [fzf/CHANGELOG.md - 0.51.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0510)

**Comment by letuanhai** [comment]
> You can find it in the man page.

Hi, thanks for checking the issue again.
Yes I've found out about the environment variable from the man page. That's why I've mentioned it in my original post. However, I didn't find any example of its usage, and was failed to use it correctly.

What I think should be documented is the following note about its usage:

> The FZF_QUERY is an environment variable exported by fzf that you must escape when used with double quotes; otherwise, it will expand immediately.
> ```--bind "start:reload:$RG_PREFIX \$FZF_QUERY"```
