### ISSUE TITLE
Configurable alt-c command

### ISSUE THREAD

**Issue by Eisfreak7** [junegunn/fzf#408]
Is there a reason there is ```FZF_CTRL_T_COMMAND``` to configure ctrl-t but no ```FZF_META_C_COMMAND``` to do the same for alt-c?
I'm using zsh, I don't know if its the same with other shells.
I'd prefer to use something faster than find, but currently I have to recreate the cd widget altogether.

**Comment by netei** [comment]
It was introduced here : https://github.com/junegunn/fzf/issues/280#issuecomment-115305279

**Comment by junegunn** [comment]
Because there was no request for it and I'm lazy :) Updating support for bash, zsh, and fish is quite tedious so it's not something I'd like to do often. And I'm reluctant to add yet another variable when there's not much demand for it.

> I'd prefer to use something faster than find

Care to share good alternatives?

> currently I have to recreate the cd widget altogether

It isn't too bad, right? That's the ultimate way of customizing the behavior and I don't think it's a bad practice at all especially when there's been little update in the provided key bindings.

**Comment by Eisfreak7** [comment]
I'd try locate (although that obviously wouldnt be as current as find).

Ah okay I can understand that. Redefining the widget isn't too bad a solution, I just thought since there exists a variable for ctrl-t it might just be an oversight that there is no such thing for meta-c.

Thanks for the explanation

**Comment by junegunn** [comment]
Okay, I added `$FZF_ALT_C_COMMAND` for completeness' sake.

**Comment by Eisfreak7** [comment]
Thank you

**Comment by lukelbd** [comment]
Thanks very much. One handy usage for this (e.g. if you are completing in the `home` directory chock full of folders) is to add `export FZF_ALT_C_COMMAND='find . -maxdepth 1'`.
