### ISSUE TITLE
0.56.1/2 breaks my `FZF_COMPLETION_TRIGGER`

### ISSUE THREAD

**Issue by jefferickson** [junegunn/fzf#4088]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.2

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Thank you for the great work!

In my `.zshrc`, I set ``FZF_COMPLETION_TRIGGER='`'``. With up to 0.56.0 installed, this works well (and has for years). 

Starting in 0.56.1 and still existing in 0.56.2, this no longer works. When I type for example `` cd `<TAB> ``, nothing happens. If I set the env var to nearly anything else, it works again.

If I downgrade to 0.56.0, it works again.

The fzf portion of my `.zshrc`: https://github.com/jefferickson/dotfiles/blob/d552e8eae75edd1ce4d14b11ae960a9aeccb370a/.zshrc#L96-L106

**Comment by LangLangBart** [comment]
Thanks for the report. I can reproduce it; the issue lies with the `words` array
parameter provided by `zsh`.

When the trigger consists of only one back-tick, the `words` array is empty.

For now, you could modify your shell setup in your `zshrc` by commenting out
this line, though it's not recommended because the actual command you use for
your completion will not be correctly identified, and just fallback to the default.

https://github.com/junegunn/fzf/blob/215ab48222ac5fa8855c1e5bbf56742276b57324/shell/completion.zsh#L343

---

It's **better** to use a different trigger. The construction of the `words` array is
hardcoded in the C part, and it seems the parser has trouble correctly
identifying a `word` in this situation (tentatively hinting at a bug in `zsh`).

```bash
# Use ~~ as the trigger sequence instead of the default **
export FZF_COMPLETION_TRIGGER='~~'
# Two back-ticks seems to work 
export FZF_COMPLETION_TRIGGER='``'
```

It would be possible to fall back to the old extraction method (prior to the PR
linked below) if the `words` array is empty and the `LBUFFER` is not, to at
least provide the user with a partial solution. However, this approach would
only work for the first command.

- Ref: #4082

**Comment by jefferickson** [comment]
Thank you for the detailed response. I'd like to find a way to keep the backtick as my trigger as I have 6+ years of muscle memory and it's very convenient as it's right next to the TAB on an American layout. Alternatively, I can stay at version 0.56.0 for the time being.

**Comment by mathieu-lemay** [comment]
I'm using `;;` as a completion trigger and it is also not working anymore, since 0.56.1.

**Comment by LangLangBart** [comment]
> I'd like to find a way to keep the backtick as my trigger

Right, any solution should allow the same characters that can be used in `bash`
to maintain consistent behavior between both shells.

> I'm using `;;` as a completion trigger and it is also not working anymore, since 0.56.1.

Characters found to cause issues are these:

| Symbol  | Common Name  | ASCII | Occurrences in Public Git Repos |
| ------- | ------------ | ----- | --------------------------------------- |
| `&`     | Ampersand    | 38    | 1                                       |
| `;`     | Semicolon    | 59    | ~25                                     |
| `[`     | Left Bracket | 91    | 1                                       |
| `` ` `` | Back-tick    | 96    | ~20                                     |
| `\|`    | Pipe         | 124   | 0                                       |
