### ISSUE TITLE
Error: Unsupported-key: backward-eof

### ISSUE THREAD

**Issue by Anon258** [junegunn/fzf#4096]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.20.0

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

I am using Ubuntu 20.04 WSL, for which fzf 0.20.0 is the latest version according to apt package manager.
When doing an fzf query, I get this error "unsupported key: backward-eof" due to one of the local-binds. I believe this problem can be fixed if I can remove eof key from my local binds, is there a way to do that? Or any other way to fix this?

I cannot upgrade my Ubuntu version due to company tools and restrictions

**Comment by LangLangBart** [comment]
The issue is reproducible when assigning the `backward-eof` event to an action in `Ubuntu 20.04`.
```bash
docker run --tty --interactive --rm --privileged ubuntu:20.04 sh -uec ' 
apt-get update && apt-get install -y fzf
echo "export FZF_DEFAULT_OPTS=\"--bind backward-eof:abort\"" > ~/.bashrc
/bin/bash'
```

According to the changelog, the event was added in `0.22.0`[^1][^2].

>  I believe this problem can be fixed if I can remove eof key from my local binds, is there a way to do that? Or any other way to fix this?

Can you try adjusting your `FZF_DEFAULT_OPTS`?

[^1]: [fzf/CHANGELOG.md · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0220)
[^2]: [Add backward-eof event for --bind · junegunn/fzf@a7aa08c · GitHub](https://github.com/junegunn/fzf/commit/a7aa08ce07e2)

**Comment by junegunn** [comment]
> due to one of the local-binds.

What exactly is it, and where is it defined?

> I cannot upgrade my Ubuntu version due to company tools and restrictions

You can still download the latest binary from [the releases page](https://github.com/junegunn/fzf/releases) and put it in your `$PATH`.
