### ISSUE TITLE
[Feature request] less(1)-like mode UI

### ISSUE THREAD

**Issue by vt-alt** [junegunn/fzf#4105]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.2 (altlinux)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

I'd suggest `--less` to trigger more a `less(1)`-like interface.
1. Currently, when unfamiliar to fzf users, if they want to abandon selection and exit intuitively press `q` which (confusingly for them) triggers a search and not an exit.
2. In the `less`-like mode it could behave like this: search prompt is hidden by default, and `q` triggers a `abort`, when user presses `/` search prompt appears (as in default interface) and what is typed is searched, (optionally with `esc` it switches back into a selection-only mode).

I tried this workaround `--bind='q:abort,/:unbind(q)+unbind(/)'` but dedicated interface would be a better UI/UX. As it will signal with prompt presence what mode it is. Also, with this workaround familiar to fzf users can start search and `abort` inadvertently when typing `q`.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I don't want to add this to fzf because fzf is not less. Users who are not familiar with fzf should familiarize themselves with it before using it, instead of trying to use it like a different program.

**Comment by vt-alt** [comment]
Thanks for the response. Yes If my goal is to be dedicated fzf user. But most of the times, fzf is integrated in other scripts, and users expect standard UNIX tui experience. Quitting with `q` is common, not just in less, but also man, info, top, mutt, lynx, tig, mpg123.

The suggested option is not needed to be called `--less` too. Because, what is important is smoothness of UI/UX.

Also, with `--disabled` the prompt is not hidden and is possible to enter text which is confusing UI. I was only suggesting to improve user experience, which I thought one of the fzf goals.

**Comment by junegunn** [comment]
> Quitting with `q` is common, not just in less, but also man, info, top, mutt, lynx, tig, mpg123.

TBH, I don't think it makes a good point, because fzf is not like any of those programs. fzf is a text filter program like `grep`, and none of the mentioned programs is a filter. You probably shouldn't use fzf in place of less in the first place.

And there are standard Unix tools that don't quit on `q`, vim, emacs, vmstat, to name a few. Well, this doesn't make much point either because they are not like fzf.

On the other hand, the suggested behavior will confuse the users who are already familiar with fzf, and they have to learn how this new `less`-like mode works; the similarities and the differences because we can't 100% replicate less behavior in fzf.

> Also, with `--disabled` the prompt is not hidden and is possible to enter text which is confusing UI.

See https://github.com/junegunn/fzf/issues/2890#issuecomment-1204693200

**Comment by vt-alt** [comment]
JFYI. In [my use case](https://github.com/vt-alt/ktools/blob/master/log#L34) fzf is a front end to select *.log files and then `less` is started to view the selected one. And yes I intuitively pressed `q` frequently (then `esc`) to quit the menu before starting `less`. This is because with `--preview` feature I can see everything already (tail of the selected log). I don't though this is abuse of fzf interface.
