### ISSUE TITLE
Reason why you don't use readline

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#411]
Is they any particular reason that you have chosen not to use readline ?

Wouldn't it remove lots of code on your side that you have to maintain, and at the same time give full readline capacity ?

I guess one problem is to integrate readline inside ncurses, here's an example of that in C, https://github.com/ulfalizer/readline-and-ncurses , I don't know if it is a hacky solution or if that technique could also be used from inside fzf.

**Comment by junegunn** [comment]
Thanks for the info. I had no experience using readline on ncurses and didn't know if it was possible, so that's why. Still we don't know if they work together flawlessly. I could've looked into it, but since now we have every relevant readline binding working fine (is there anything you miss? Full read-line support, such as reverse-search, rather seems like overkill to me), so there's little reason for me to take time to switch. But if someone sends me a PR that replaces the current implementation with readline, I wouldn't refuse merging it.

**Comment by netei** [comment]
Ok, I'm not missing anything in particular from readline for know.

I think it might be beneficial to use readline (less code, less maintenance, less documentation), but I also see that it represents some amount of work.
