### ISSUE TITLE
Add --ignore-unknown-options or --assert-exists-options $options,

### ISSUE THREAD

**Issue by zoodogood** [junegunn/fzf#4113]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.46.1

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Expected behavior:
There is an option to provide the latest fzf functions in the script without behavior like the `unknown option: --wrap`

Current behavior: There seems to be no such option or other ways to pass parameters safely.

Note: I use the latest version specified for my distribution

**Comment by junegunn** [comment]
Even if we add such an option to fzf, you won't have it unless you upgrade your fzf to the latest version on GitHub (you can just download the binary and put it in your `$PATH`). And once you upgrade, you have all the options previously unavailable to you. So I don't really see the point of such an option.

If you need this because you want to distribute your script that requires some options to a group of users, your script should check the version number of the fzf installed on the user's system (`fzf --version`) and act accordingly.
