### ISSUE TITLE
Feature Request: Event for "down" when already on the last item

### ISSUE THREAD

**Issue by ejrichards** [junegunn/fzf#4128]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.3 (add1aec)

### OS

- [X] Linux
- [X] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

It would be great to have an event similar to `backward-eof`, but for pressing `down` when already on the last item of the list. My use case is using the up arrow to trigger `fzf` on my shell history, so if I press down, I'd like to call the `abort` action. I've been searching the docs for a while now and don't see a way to currently do this.

**Comment by LangLangBart** [comment]
> pressing down when already on the last item of the list.

Assign the transform[^1] action to the `down` key paired with a condition that may work depending on your layout.


#### reverse layout
`abort` if `FZF_MATCH_COUNT` and `FZF_POS` are equal; otherwise, `down`. 
```bash
seq 3 |  fzf --layout=reverse \
  --bind 'down:transform:((FZF_MATCH_COUNT == FZF_POS)) && echo abort || echo down'
```

#### normal layout
`abort` if `FZF_POS` is one or smaller; otherwise, `down`. 
```bash
seq 3 |  fzf --layout=default  \
  --bind 'down:transform:((FZF_POS <= 1)) && echo abort || echo down'
```

[^1]: [fzf/CHANGELOG.md 0.45.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0450)
[^2]: [fzf/CHANGELOG.md 0.46.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0460)

**Comment by ejrichards** [comment]
Thanks, I misunderstood what "transform states" meant for `transform`, makes more sense now.

I'm working on some `elvish` shell integrations, here is the solution when it is set as your shell:

```elvish
--bind 'down:transform:if (<= $E:FZF_POS 1) { print abort } else { print down }'
```
