### ISSUE TITLE
Allow 'execute(...)' action to act on selected entries

### ISSUE THREAD

**Issue by qoxxxx** [junegunn/fzf#413]
As far as I know it can only act on highlighted entry.

**Comment by junegunn** [comment]
Yes, so what do you have in mind?

**Comment by qoxxxx** [comment]
Well, something like
- Search files with fzf
- Select some
- Use key to execute a script that take all those files in argument (gnome-open ...)

**Comment by junegunn** [comment]
And you don't want to close the fzf process while doing it, right? Cause if it doesn't matter you can easily do that with the script around fzf.

To support that we'll need a separate action, because we don't want to lose the current behavior. (e.g. previewing an entry using execute binding and select it) I think about it.

**Comment by qoxxxx** [comment]
Closing the process, sure, but above all, it's about choosing what action to do while in fzf. 
Would be interesting to me to be able to launch fzf with multiple actions set, search, and then choose (keybinding) which one to execute. 
It would allow me to launch (almost) always the same fzf command for multiple purposes. 
I understand if that's not how fzf is intended to be used.

**Comment by junegunn** [comment]
Well then, have you considered using `--expect` option? e.g. https://github.com/junegunn/fzf/wiki/Examples#opening-files

**Comment by qoxxxx** [comment]
I didn't. I will now. Thanks ! And sorry for not seeing it before.
I still don't think the "action on selected entries" feature would be useless but it's up to you as I will be satisfied enough with the above example.

**Comment by tagwint** [comment]
I've just successfully utilized the execute-multi action. Could you tell me if there is a length limitation
for {} placeholder? It does not seem to cope with veeery looong lists.
(thanks for fzf, it's just great)

**Comment by junegunn** [comment]
@tagwint How long? It's probably the limitation of your shell ("argument list too long").

**Comment by tagwint** [comment]
I thought that direction too, the problem is i cannot see the error message, even if I redirect the stderr
It probably depends on the total size of what {} contains. I experimented with the output of find command
the lines were of different length, but by redirecting output (printf "%s\n" {} > /somefile ) I could estimate 
that the limit is around 140Kbytes. I will check if shell limitation is similar to that or not.
BTW, is there a way to know the number of selected lines w/o leaving fzf, to prevent passing long arg to the execute-multi ?

**Comment by tagwint** [comment]
By more precise check, I've run into 128K limit which seems to be hard-coded MAX_ARG_STRLEN kernel parameter. Unlike the MAX_ARG paramter which can be extended in system by increasing stack size, the MAX_ARG_STRLEN cannot. I tried to increase the system stack and that did not help since {} is seemingly  interpreted as a single argument not as a numbers of arguments.

**Comment by junegunn** [comment]
> is there a way to know the number of selected lines

fzf shows the info right above your prompt: e.g. `109389/109389 (5)` Or, are you referring to something else? To be honest, I'd never imagined that someone would hit that limit, what are you using `execute-multi` for?

**Comment by tagwint** [comment]
Оf course it does show the number. I asked about how to know the number inside the script that calls fzf before it exits.  In other words the number of items in  {}  when it is in execute-multi context.
I use execute muti to handle list of files from find output from remote hosts. I select files on remote hosts using dynamic criteria on their name/location (that's where fzf is the king) -
after selection i can do some action on the found files - zip, transfer, compare, delete etc. It is much handier not to leave fzf and use execute-multi.

**Comment by junegunn** [comment]
Hmm, no. And I can't help but feel that it's beyond the scope of fzf. fzf starts child processes using [`$SHELL`, `-c`, `COMMAND`] internally, so maybe it's possible to somehow *abuse* the fact. i.e. overriding `$SHELL`.

**Comment by tagwint** [comment]
Ok I see the reasoning, will think of how to handle that. 
Thank you for clarifying the points.

**Comment by Onturenio** [comment]
Hi, I'm using FZF 0.46.0. I don't see the `execute-multi` action. Has it been removed later on? It's exactly what I'd need to turn FZF into some sort of "task manager" to do actions based on fuzzy-search plus selection on a bunch of tasks. Is there a different, alternative way to achieve that?

Thanks!

**Comment by junegunn** [comment]
It's deprecated in favor of `{+}`.
https://github.com/junegunn/fzf/commit/ed57dcb924112192636260fb31d0db54352c517a


```
seq 10 | fzf --multi --sync --bind 'start:toggle-up+toggle-up+execute:for item in {+}; do echo $item; done; read'
```

**Comment by Onturenio** [comment]
Great, thanks. I had missed that functionality.
