### ISSUE TITLE
Can you wrap lines so that they are fully displayed?

### ISSUE THREAD

**Issue by infokiller** [junegunn/fzf#461]
My most common usecase for fzf is search through my history, which often contains very long commands. When the terminal window is too narrow for the full command line, it is trimmed. Is it possible to wrap instead? ideally, I'd be able to specify the maximum number of lines that are used for the wrapping. This way I can make sure that extremely long items don't take all the screen, but also that I can see more of every item.

Thanks!

**Comment by junegunn** [comment]
Hi, thanks for the suggestion. It's currently not possible and unfortunately, implementing it is not at all trivial. See the previous (related) discussion here: https://github.com/junegunn/fzf/issues/154#issuecomment-84503814. I'm closing this not because this is a bad idea, but I can't see myself implementing it in a foreseeable future.

**Comment by infokiller** [comment]
Thanks a lot for your quick response!

**Comment by gatoatigrado** [comment]
I'd use this too, if you or anyone else gets around to implementing it. But yeah, if it's complicated, maybe not worth the time currently.

**Comment by sucrecacao** [comment]
It there any update on that ? Will it stay a "won't fix" ?

I would like to have beautiful input like 
```
echo " option1_title \n option1_text \00 option2_title \n  option2_text" | fzf --read0
```
