### ISSUE TITLE
fasd:2: fork failed: resource temporarily unavailable

### ISSUE THREAD

**Issue by SharkIng** [junegunn/fzf#464]
Is there any solution for it?

**Comment by junegunn** [comment]
I don't think it's related to fzf. Google will probably give you some pointers.

**Comment by raphaelfeng** [comment]
@SharkIng 
I had the same problem and I found I define a function which is the example from the fzf project.
 v() {
    # local file
    # file="$(fasd -Rfl "$1" | fzf -1 -0 --no-sort +m)" && vi "${file}" || return 1
 }

And I also have an alias defined as
alias v="fasd -e vim"
which is an example from the fasd project.

The problem was solved by removing either of them.
I guess the same name caused some recursive calls which run out of the process resource.
