### ISSUE TITLE
[bash] Let Ctrl+T work mid-word like **<Tab>

### ISSUE THREAD

**Issue by d-lord** [junegunn/fzf#473]
Hey, fzf rocks, big fan :)

In the bash completion, when you get halfway through a path and decide to fuzzy-complete it, you can use **<Tab> to open fzf on the rest of the path.

Is it possible to enable Ctrl+T to do that too? Currently it starts a new completion 'session' from the cwd.

**Comment by junegunn** [comment]
Unfortunately, I don't think it's possible on bash. It's possible [on zsh](https://github.com/junegunn/fzf/wiki/Fuzzy-completion#zsh) but on bash what we can do with ordinary key bindings is very limited so we have to override the one and only completion system. Therefore if we set `FZF_COMPLETION_TRIGGER` to an empty string and bind `CTRL-T` to `complete`, normal tab completion will always start fzf since tab is also mapped to `complete`, which is definitely not what you'd want.
