### ISSUE TITLE
History with timestamps

### ISSUE THREAD

**Issue by eyalev** [junegunn/fzf#504]
Is there a way to see timestamps in the history list?

Currently I'm on Ubuntu with oh-my-zsh.
I can see history timestamps with (e.g):

 `$ fc -li -5`

```
17734  2016-02-22 13:54  command1
17735  2016-02-22 13:56  command2
17736  2016-02-22 13:56  command3
17737  2016-02-22 13:57  command4
17738  2016-02-22 13:57  command5
```

Is there a way to get similar output in `fzf`?

Thanks

**Comment by junegunn** [comment]
Currently, the command is [hard-coded](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh#L39-L49), and you'll have to put a modified version of `fzf-history-widget` in your zsh configuration (of course after `source ~/.fzf.zsh`). I'll think about ways to make it configurable without having to duplicate the whole function, but it's tricky since the format affects the implementation.
