### ISSUE TITLE
Regex Word Boundary

### ISSUE THREAD

**Issue by MichaelMackus** [junegunn/fzf#534]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I would think that FZF would allow the PCRE word boundary `\b` but searching for `test\b` doesn't work. I would love if this feature could be added since I'm using this to search for tags and want to search something like: `^test\b` using fzf.vim :Tags ex command

I tried using `--nth=1` and just doing `^test$` which worked, but then I can't further limit the result set in any of the other fields.

**Comment by junegunn** [comment]
> but then I can't further limit the result set in any of the other fields.

`--nth` option can take multiple ranges, so you can do something like `--nth=1,2..` or `--nth=1,..` which will help in this case. I'll consider applying the option to `:Tags` command.

Regarding `\b`, I'm not thinking of adding more operators to the current search syntax to keep things simple and easy. Instead, I'll experiment with the scoring function so that it prefers matches on word boundary.

**Comment by MichaelMackus** [comment]
@junegunn thanks... I'd just like to match the tag exactly. Unfortunately, `--nth=1,..` doesn't quite help since there's still no way to match on the full exact tag (from what I can tell at least).

Makes sense you don't want to overcomplicate things, though. So far, my current approach is working better than standard vim `C-]` at least. If anybody is interested, here's my function:

```vim
nnoremap <C-]> :call FzfGoToTag(expand("<cword>"))<CR>

" Search tag stack with fzf
function! FzfGoToTag(tag)
  let curatedTag = substitute(a:tag, "\\$", "", "")
  return fzf#vim#tags('^'.curatedTag.' ', { 'options': '+i -e --nth=1,..' })
endfunction
```
