### ISSUE TITLE
First entry is not shown immediately if using -1

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#563]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

With the following command : 

```
{ printf "foo\n" && sleep 1 && printf "bar\n" && sleep 1 && printf "baz\n" ;} | FZF_DEFAULT_OPTS="-1" fzf
```

# What I get : I see 

```
foo
bar
```

after 1 second

# What I expect : 

See `foo` immediately, then bar after one second.

The -1 should only tell that if the incoming pipe is finished and contains only one element, fzf should exit and output that line. 

What do you think ?

**Comment by junegunn** [comment]
More precisely, `-1` is the option that tells fzf not to start the interactive ncurses finder when there's only one possible match and just stop there. It makes more sense when `-q` option is also specified.

```sh
# No -q, interpreted as empty query string which matches every item.
# When bar comes in, fzf realizes there's more than one match already and starts ncurses finder
{ echo foo && sleep 1 && echo bar && sleep 1 && echo baz ;} | fzf -1

# f matches foo only. But we can't be sure until the stream is finalized
{ echo foo && sleep 1 && echo bar && sleep 1 && echo baz ;} | fzf -1 -qf

# b matches bar and baz. On baz, there are already two matches, start the finder
{ echo foo && sleep 1 && echo bar && sleep 1 && echo baz ;} | fzf -1 -qb
```

The option was added for scripting purposes where you don't want to start interactive finder unless it's necessary. If we start ncurses finder with when the option is set, there are a few problems:
- User can change the query, so the condition dynamically changes. Should we just cancel out the option, or should we still stop fzf when there's only one match for the updated query? It can be confusing.
- Finder pops up and closes immediately in many cases, screen unnecessarily flickers.

So what you described above is the expected behavior of the option.

**Comment by edi9999** [comment]
Ok, so I guess I will remove that option from my .bashrc :-)
