### ISSUE TITLE
fzf shows something weird color on white background

### ISSUE THREAD

**Issue by aseom** [junegunn/fzf#568]
- Category
    - [x] fzf binary
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

![fzf_color_issue](https://cloud.githubusercontent.com/assets/16207504/15096778/33fa6532-1542-11e6-91d9-37ce2a23eb33.png)

I'm using iTerm2 (2.9) with white background colorscheme.
And `$TERM` is set to `screen-256color`

It shows something weird color like screenshot.
Tried `--no-256` option, but same result :(

**Comment by junegunn** [comment]
Not sure what you find strange? Those are the default colors chosen to look good on terminals with dark background. Since you're on a light background, you might want to try `--color=light` option (put it in your `FZF_DEFAULT_OPTS`). Or you can even customize the colors. See https://github.com/junegunn/fzf/wiki/Color-schemes

**Comment by aseom** [comment]
Oh... i see.
I read whole readme but didn't know about that until now.
Sorry... ㅎ

**Comment by junegunn** [comment]
No problem. You'll find more info on the man page (`man fzf`).
