### ISSUE TITLE
Freeze when Ctrl + T on Cygwin + Tmux + Fish

### ISSUE THREAD

**Issue by Neo-Wang** [junegunn/fzf#589]
- [x] fzf-tmux script
- [x] Windows
- [x] fish

The whole mintty freezes when pressing Ctrl + T. The fzf pane shows up and disappear before that.

**Comment by junegunn** [comment]
Hi, sorry to say this but I'm planning to stop supporting Windows environment since the latest version of fzf does not compile on Windows. What you have there is the old Ruby version which hasn't been updated for a year an a half. The maintainer of the Cygwin package of fzf (ruby) showed his interest to take over the maintenance of the Ruby version. See https://github.com/me-and/Cygwin-fzf/issues/2

**Comment by justinmk** [comment]
>  latest version of fzf does not compile on Windows.

Why is that? I had hoped that the internals of fzf could be modularized so that other applications could use it for filtering. 

I vaguely recall the idea of fzf as a library being discussed, but can't find it on the issue tracker, and don't recall the conclusion.

**Comment by junegunn** [comment]
@justinmk  Because of ncurses and some other unixy stuff. #147 has been open for a while, but nobody has presented a complete solution to the problem. I'm probably not going to spend my time on Windows support (I don't even have a Windows PC) or extracting non-UI part as a library because I don't need it. He that would eat the fruit must climb the tree.

**Comment by justinmk** [comment]
I suppose I am asking only that #147 be kept open. I have not really looked closely, but my guess (please correct) is that the work to be done is mostly mechanical, not requiring any risky refactoring. 

Do any specific cases come to mind where you believe it would be difficult to provide a "bare bones" (i.e., no highlight, no cursor placement--only a list of sorted items) result? 

My thoughts are: 

- The key parts of fzf are the asynchronous collection and on-the-fly matching. 
- Inputs:
    1. Stream of lines 
    2. Stream of user keystrokes
- Output:
    1. Sorted list of lines

The multi-selection, key bindings, etc., seem like things that can overlayed by a host application.

If I'm missing a key detail I would appreciate any corrections. Is there some other comparable cross-platform option?

**Comment by junegunn** [comment]
By "library", do you mean a real library that you can link to your program, or (still) a standalone executable that provides some kind of barebone mode (or maybe a socket server?)

Stripping out visual elements will not be difficult (`terminal.go` is only responsible for UI), but the asynchronous nature of fzf may not fit well with the classic request-response model.

**Comment by justinmk** [comment]
> a standalone executable that provides some kind of barebone mode (or maybe a socket server?)

Yes, that. 

> but the asynchronous nature of fzf may not fit well with the classic request-response model.

I'm thinking more of an embedded fzf (similar to `nvim --embed`) which the parent process communicates with via stdin/stdout.
