### ISSUE TITLE
**<Tab> does not respect agignore like Ctrl-T and fzf does 

### ISSUE THREAD

**Issue by letientai299** [junegunn/fzf#597]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Use case:
```
vim **<TAB>
```

My setting for both `$FZF_CTRL_T_COMMAND` and `$FZF_DEFAULT_COMMAND`:  
```
ag --path-to-agignore ~/.agignore -g ""
```

**Comment by junegunn** [comment]
See
- https://github.com/junegunn/fzf#settings
- https://github.com/junegunn/fzf/blob/master/shell/completion.bash#L13
- https://github.com/junegunn/fzf/blob/master/shell/completion.zsh#L13

So why is it different? Because in fuzzy completion we have to take the prefix into account unlike in `FZF_CTRL_T_COMMAND` and `FZF_DEFAULT_COMMAND`. Take `vim ~jg/**` for example, we can't just start `ag --path-to-agignore ~/.agignore -g "" ` and pass `~jg/` as the default query. The command should handle the prefix, so we use functions.

**Comment by letientai299** [comment]
Thanks, I will try to customize the 2 functions.
