### ISSUE TITLE
Add option to auto-complete input box from item list

### ISSUE THREAD

**Issue by awalGarg** [junegunn/fzf#606]
- Category
    - [x] fzf binary

Hi, it'd be great to have a "typeahead" action so we can
bind a key (say, Tab), to change the contents of the input
to the selected entry (if any).

Use case:

I have a script which lists some items and pipes to fzf.
I'd like to pass additional text the recieving end which
called fzf with `--print-query` so it gets the additional
argument. It'd be great for UX if user can complete the
input from the entry list and type only the additional data
instead of copying from the item list to input box manually
and typing the additional data.

I'd have gone as far as suggesting to bind this to `Tab` by
default but it seems it is pre-occupied :)

Here is a patch to implement this:

```diff
From b9575f83de8a52badca4f0d01e0a28b9c00a0a70 Mon Sep 17 00:00:00 2001
From: Awal Garg <awalgarg@gmail.com>
Date: Sat, 25 Jun 2016 21:33:32 +0530
Subject: [PATCH] add typeahead option

---
 man/man1/fzf.1  | 1 +
 src/options.go  | 2 ++
 src/terminal.go | 6 ++++++
 3 files changed, 9 insertions(+)

diff --git a/man/man1/fzf.1 b/man/man1/fzf.1
index bdd6d19..78847fa 100644
--- a/man/man1/fzf.1
+++ b/man/man1/fzf.1
@@ -393,6 +393,7 @@ e.g. \fBfzf --bind=ctrl-j:accept,ctrl-k:kill-line\fR
 
   \fBACTION:               DEFAULT BINDINGS (NOTES):
     \fBabort\fR                 \fIctrl-c  ctrl-g  ctrl-q  esc\fR
+    \fBtypeahead\fR             (set input text to selected entry)
     \fBaccept\fR                \fIenter   double-click\fR
     \fBbackward-char\fR         \fIctrl-b  left\fR
     \fBbackward-delete-char\fR  \fIctrl-h  bspace\fR
diff --git a/src/options.go b/src/options.go
index 2a72427..90ebec1 100644
--- a/src/options.go
+++ b/src/options.go
@@ -575,6 +575,8 @@ func parseKeymap(keymap map[int]actionType, execmap map[int]string, str string)
 			keymap[key] = actAbort
 		case "accept":
 			keymap[key] = actAccept
+		case "typeahead":
+			keymap[key] = actTypeahead
 		case "print-query":
 			keymap[key] = actPrintQuery
 		case "backward-char":
diff --git a/src/terminal.go b/src/terminal.go
index 213d3b0..e0b6aa2 100644
--- a/src/terminal.go
+++ b/src/terminal.go
@@ -127,6 +127,7 @@ const (
 	actMouse
 	actBeginningOfLine
 	actAbort
+	actTypeahead
 	actAccept
 	actBackwardChar
 	actBackwardDeleteChar
@@ -1181,6 +1182,11 @@ func (t *Terminal) Loop() {
 			case actUp:
 				t.vmove(1)
 				req(reqList)
+			case actTypeahead:
+				if t.cy > 0 && !t.multi {
+					t.input = []rune(t.current())
+					t.cx = len(t.input)
+				}
 			case actAccept:
 				req(reqClose)
 			case actClearScreen:
-- 
2.8.3
```

**Comment by junegunn** [comment]
Thanks for the suggestion. But after some consideration, I decided that I don't want the option in fzf.

> It'd be great for UX if user can complete the input from the entry list and type only the additional data

I'm not sure about this. I don't see why we have to use fzf to take the extra data for the found match. It's not how fzf was designed to be used. First you type in the initial query string to find the match, and you get what you want highlighted. But then if you type in the additional data for the match, the query changes accordingly, and you no longer see the same result, which I believe can be quite confusing. The confusion is unavoidable since the input prompt of fzf is strictly for narrowing down the candidates.

Another subtle problem with the approach is that fzf does not take the query string literally unless extended-search mode is turned off, so it is not always guaranteed that you will still see the item at the head of the list after you replace the query string to it (e.g. `echo 'if !cond' | fzf -q 'if !cond'`). And for the sake of simplicity, I'm not considering the addition of escaping syntaxes.

Although fzf provides a rich feature set that allows more sophisticated use cases, fundamentally, it's still an interactive unix filter. I believe you can find a more *orthodox* solution to the problem. For example, you may use `--expect` option to set up an alternative accept key that can be used to optionally start an extra prompt for the extra data.

```sh
IFS=$'\n' read -d '' -r -a lines < <(fzf --expect space)
[[ ${lines[0]} = space ]] || extra="" && read -p "${lines[1]}> " extra
```

**Comment by awalGarg** [comment]
> For example, you may use `--expect` option to set up an alternative accept key that can be used to optionally start an extra prompt for the extra data.

Indeed, that better serves the use case. Thanks for the pointer!

**Comment by awalGarg** [comment]
Hi.

Sorry for bumping this again, but I have run into another use-case where this could be helpful. The list of entries piped to fzf are of the form:

```
foo
foo a
foo b
foo c
foo d
bar
bar e
bar f
bar g
bar h
...

```

So basically lots of repetition in the first column(s) and then some more columns. It would be cool if we can just do this:

```
type "f" // list narrows and first option is foo
hit "Tab" // or any other keybinding, which fills the input with the first option which is foo
type " c" // instead of typing "foo c" or manually selecting downwards
hit return 
```

Do you think there is a better way to do this with current fzf feature set? If not, would you reconsider the originally proposed extension to fzf?

**Comment by junegunn** [comment]
How about just typing in `fc`? That's what I'd do. Or to be more precise, `f ^c` with `--nth ..,2..` option. It's hard to evaluate the usefulness of the feature with the synthetic input you provided above. fzf is a line-oriented Unix filter and I believe it is most natural to use it with flat list of things presented as lines.
