### ISSUE TITLE
Donate to fzf

### ISSUE THREAD

**Issue by eyalev** [junegunn/fzf#631]
How can I donate money to this project?

Thanks :)

**Comment by junegunn** [comment]
Thanks. You can donate via PayPal on [this page](http://junegunn.kr/projects/), but hey, just knowing that you like this project so much that you even consider donation is rewarding enough for me at the moment :)

**Comment by edi9999** [comment]
Just did my first donation that is recurrent monthly , your software is really great !

**Comment by junegunn** [comment]
@edi9999 Thanks Edgar, I really appreciate it!

@eyalev Thank you!

**Comment by eyalev** [comment]
Welcome!

I hope a day will come and you could work on open source exclusively (if that's something you want :)

And I should add that `fzf` is one of the most productivity boosting programs I use. Thank you.

**Comment by edi9999** [comment]
> I hope a day will come and you could work on open source exclusively (if that's something you want :)

I would definitely back you a bit if you decided to do that :-)
You're one of the person I know that communicates very clearly, always taking the time to express your intent and know when to accept/decline features.

**Comment by pyrho** [comment]
I can't find the paypal link on the page you linked earlier t_t

As mentioned above by others, `fzf` is the single most useful tool I've discovered since Vim that helps me _every.single.day_, so a huge thank you for that.

I would love to make a donation, and I'm guessing I'm not the only one, you should consider putting at the bottom of the README.

<3

**Comment by hieu-n** [comment]
> Thanks. You can donate via PayPal on [this page](http://junegunn.kr/projects/), but hey, just knowing that you like this project so much that you even consider donation is rewarding enough for me at the moment :)

@junegunn
Hi, I want to donate, but also don't find your Paypal info on your website. There is a link to your paypal on your Github Profile: https://paypal.me/junegunn Just want to confirm that you are still able to receive donation from that link/account, before i donate. 

Cheers!

**Comment by pyrho** [comment]
Also maybe consider Github's sponsor program, not sure how it works but as a donor it's a dead simple UX.

**Comment by junegunn** [comment]
@hieu-n Thank you. Yes, [the PayPal link](https://paypal.me/junegunn) is still valid.

@pyrho Thanks for the suggestion. Unfortunately, GitHub Sponsors is not yet available in my country.

**Comment by hieu-n** [comment]
@junegunn I just made a small donation. 
There are two options:
- Just sending money: Paypal will charge me $5.63 USD. From what I read, that's because we are in different countries.
- Paying for products/services (which I chose): There is no fee for payers.

I'm not sure how much Paypal would charge you for receiving payments. You may consider adding Paypal Donation button which would charge less than usual for receiving donations.

**Comment by junegunn** [comment]
@hieu-n I will look into it. Much appreciated.
