### ISSUE TITLE
Micro-optimizations

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#637]
I'm working on a set of micro-optimizations to further reduce the memory footprint and improve the overall query performance and the result so far looks promising.

- Memory footprint
    - 0.13.4: 43% of that of 0.13.3
    - WIP: 34% of that of 0.13.3
- Query response time (`head -$LINES $INPUT | fzf -f $QUERY > head -50`, extremely low selectivity)
![perf-noopts](https://cloud.githubusercontent.com/assets/700826/17710869/3bfa4a0e-642a-11e6-88cb-3594d3638799.png)
- The new Go 1.7 also gives free performance improvement (around 3~5%)

**Comment by balta2ar** [comment]
This is great! You know, being a huge fan of fzf, I check the repo almost every day to see whether there are new commits or anything. If it's not too much of a hassle for you, may I ask you to push your progress into a pull request as you develop, for visibility? I'd be happy to see how the code evolves as you make those changes.

Here is another idea. How about adding benchmarking tests that set certain bottom line CPU- and memory-wise in a number of different use cases? You're obviously doing that manually, but I'm talking about something automatic, some performance regression tests (probably go supports that out-of-the-box?). This will also be easier for contributors to make sure their changes do not degrade the performance.

**Comment by junegunn** [comment]
I'm currently in the process of experimenting with different ideas. Some turned out to be great, some not so great, or even flawed. So it's a bit early to commit and push to master, which I try to keep stable if possible as some users prefer to build from the latest master. But I'll try to push changes that I can be comfortable with.

A couple days ago I wrote a script that measures the query performance and the memory consumption of the latest releases and creates chart images (the one you see above). The script currently is not portable, I'd like to clean it up and include it in the repo when time allows. Ideally, test for performance regression can be run on Travis CI, but it'll probably yield many false positives.

**Comment by junegunn** [comment]
As of f8fdf9618adf831b614a9b69e90eca53b9e37a28,

Memory:
![mem-baseline](https://cloud.githubusercontent.com/assets/700826/17821762/4e62ad1a-668e-11e6-9a39-b6ca2e0d4e9e.png)

Response time:
![perf-baseline](https://cloud.githubusercontent.com/assets/700826/17821763/4e69b934-668e-11e6-9dd9-1448b80a8053.png)

**Comment by balta2ar** [comment]
Looks great! Could you describe what is "after-search" and "before-search"? Also, having ticks on Y axis would be nice.

**Comment by junegunn** [comment]
Resident memory size just after fzf finishied consuming the input (`fzf < data` where data is the output from `find /` command so every line starts with `/`), and the memory size after search for `/` is finished. fzf used to hold the list of matches using the Item struct, but I realized that it's a huge waste of memory and introduced more compact Result struct for that purpose.

I intentionally removed the y axis to focus on the relative change in values as the absolute values can vary depending on the input data, and the performance of the system. But yeah, I guess it's fine to have it.

**Comment by balta2ar** [comment]
Removing Y axis makes it unclear because the observer does not know what's the value at the start of the Y axis. A good practice is to set it to zero, but I've seen plots where Y axis starts far from zero showing only a small part of Y: https://en.wikipedia.org/wiki/Misleading_graph#Truncated_graph. On the other hand, as far as you have logarithmic X axis, Y could also easily be logarithmic, and it would make a huge difference. It doesn't look like it's the case here though, but again, omitting labels may be misleading.

As for optimizations, I've been thinking about ring buffer for input data. I'm not sure that memory allocations are still noticeable in comparison to overall code performance, but here is the idea: we allocate a fixed size array (say, 32Mb) for the input. We read stdin line by line directly into that buffer, hopefully avoiding memory allocations and creation of new slices for each line of the input. Two indices are tracked: one for the writer, one for the reader — matcher in this case. Unfortunately, it is only applicable for the filtering mode where we don't store the input. I don't think it's viable for the interactive mode. Anyway, does this make any sense?

**Comment by junegunn** [comment]
We already don't keep the result in memory in that case, i.e. when both `--filter` and `--no-sort` are set, also `--no-tac`. It's an unusual case though. Thanks for your feedback.

Anyway, I think we have made a good progress here that I can close this issue for now. I'll probably release a new binary at this point and will work on #638 that is focused on the quality of the result rather than the performance.
