### ISSUE TITLE
Directly support some features from default bindings

### ISSUE THREAD

**Issue by sambrightman** [junegunn/fzf#659]
I've seen a few feature requests closed because you don't want to support endless features when they can be built on top of `fzf`. That's reasonable, so I'm asking this as a bit of a general question rather than submitting a PR.

Examples:

* `fzf` is slow on large directory structures

There are all kinds of things you could do to mitigate this and e.g. #578 was closed. But you could also support a maximum depth in the default `find` command.

* `fzf` doesn't support "frecent" or "favourite" directories

Likewise, many suggestions for combining with `fasd` or `j`/`z`. But you could also inject something like `FZF_EXTRA_DIRECTORIES` into the default find command.

The motivation for supporting a couple of things like this natively would be:

* simplicity of setup for users of common features
* avoid soft-forking the default command (can continue to take improvements/compatibility changes to it in future, whereas setting e.g. `FZF_ALT_C_COMMAND` yourself sort of forks you from the defaults.

Can submit PRs if you are open to such things.

**Comment by laur89** [comment]
I see where you're coming from, but don't quite agree. All the reasons for rejecting such PRs are imo completely justified, for the same reasons you just gave.

It's just not worth it complicating a nice program that does one thing really good, with countless other options.

While using/setting up fasd et al do require extra effort, users still end up with far superior configuration. The setup isn't difficult per se, it just takes some additional time.

The fact that fzf adheres to the [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) makes it extremely usable by writing your own logic in shell functions and binding them up with fzf. That sort of extra functionality simply belongs outside the scope of fzf.

**Comment by sambrightman** [comment]
I understand. I would add though that composability is a key part of that philosophy. I'm particularly not keen on the soft-fork issue, which is more like overriding inheritance than composition. Is the currently a way to achieve such things as the second part with overriding the whole `FZF_ALT_C_COMMAND`? 

Relative complexity in the examples of integrating with other tools could be a sign that composability is not optimal as well. Replacing `cd` with `pushd` then needs to also replace the entire key binding/`__fzfcd__` function. I see the generic version of default functionality as "find dirs starting from some roots, apply some filtering, print the selected one as the input to another command". The root dirs, filters and command are the potential modification points. However, I can certainly see that you might not want to be generic, and just make the statement "the default functionality is exactly the function provided and no more".

**Comment by junegunn** [comment]
Please don't forget to fill in [the form](https://github.com/junegunn/fzf/blob/master/.github/ISSUE_TEMPLATE.md) when you create an issue to avoid confusion. I thought you were talking about extending fzf binary beyond `FZF_DEFAULT_OPTS` and `FZF_DEFAULT_COMMAND`, which direction I and @laur89 don't agree with. But reading your second comment, I realized that you were actually talking about the key bindings for bash/zsh/fish. Unix philosophy and composability are the concepts that apply to fzf, the program, but not necessarily to those extra key bindings. They are fully-implemented features or applications, rather than composable building blocks.

Basically, the extra shell stuff this repository provides is optional and is not the core part of the project. I see it as a reference implementation, an example of what one can build with fzf and it's not something you have to use. We provide a few basic ways to configure their behavior, and probably that's good enough for many users, but no more than that. If you want to further customize the behavior, it's better, much more flexible and probably easier that you just write your own version.

I'm not interested in extending the extra shell stuff in this repository because of maintenance burden. We can even consider extracting them out as a separate repository, and there have been some attempts (e.g. https://github.com/atweiden/fzf-extras) but I'm keeping them for backward compatibility, for the users who expect them to be readily available when they clone the repository.

**Comment by sambrightman** [comment]
Clear, thanks.
