### ISSUE TITLE
[FR] add option to define item delimiter 

### ISSUE THREAD

**Issue by laur89** [junegunn/fzf#660]
Currently it's not possible to pipe null-terminated `find` results into `fzf`. Perhaps add an option to define the delimiter, so this would be possible:

    find . -type f -print0 | fzf

**Comment by junegunn** [comment]
There is an undocumented `--read0` option you can use, but there's no promise the option will be available in the future releases. I decided to leave it as undocumented because

- the interface of fzf is not suitable for multi-line entries
- the output will be ambiguous when `--multi` is set unless we also add `--print0`

See https://github.com/junegunn/fzf/commit/8270f7f0cadf14c76feaadfb4068ccdf599a25e8

Is there any reason you have to use `-print0`? Because of multi-line entries?

**Comment by laur89** [comment]
I've come to understand using null-terminated input/output is de facto data standard for foolproof parsing. Never come across a filename that incorporates newlines, but all the custom find wrappers I'm using and now am in process of integrating with fzf output ` \0`-terminated list, and other functions that use this wrapper already assume to consume it.

Changing my wrappers to produce & consume newline-delimited data would be trivial, but because of the mentioned understanding I feel like `\0`-terminated feed would be more.. i dunno, standard?

But yeah, displaying a single item spanning over multiple lines in fzf is a pickle alright.
Not a nice solution, but perhaps display it in a single line, but add `\n` in the name for displaying purpose?

**Comment by junegunn** [comment]
Come to think about it, it makes sense for fzf to have `--print0` though I'm still not convinced about `--read0`

```sh
> echo something > foo\ bar

> find * -name 'foo bar'
foo bar

> find * -name 'foo bar' | xargs cat
cat: foo: No such file or directory
cat: bar: No such file or directory

> find * -name 'foo bar' -print0 | xargs -0 cat
something
```

**Comment by laur89** [comment]
Actually fzf is already displaying filenames neatly, if `--read0` is provided. See yourself:

    touch "foo
    bar"

and compare

    find . -mindepth 1 -maxdepth 1 -name foo* -print | fzf

vs

    find . -mindepth 1 -maxdepth 1 -name foo* -print0 | fzf --read0

**Comment by junegunn** [comment]
> Your proposed solution

Nah, it's not a solution to your problem. I wanted to present a case where `--print0` would be useful, that is passing file names with spaces (not newlines) to xargs for further processing.

```sh
# Delete selected files. No error even if names contain spaces
fzf --print0 | xargs -0 rm
```

So I mean, although I still don't see a practical value in `--read0` since I've never needed to pass items with newlines characters, `--print0` has a valid use case.

> How likely you are to remove that option?

Not likely. The new line character is not correctly displayed on the screen and simply ignored, I'll have to mend it somehow in the future if I'm going to keep the option.

**Comment by laur89** [comment]
> The new line character is not correctly displayed on the screen and simply ignored, I'll have to mend it somehow in the future if I'm going to keep the option.

But isn't it good that it's ignored? Following the example I gave in the previous post, the newline containing `foo\nbar` would appear in `fzf --read0` as `foobar` on a single line, which imo is as good as it gets.

I'm going to hope that the option is kept in, and start using it. Fzf really is an awesome tool, thanks again.

**Comment by junegunn** [comment]
> But isn't it good that it's ignored?

Then there is no way to tell the difference between `foobar` and `foo\nbar`, or even `f\no\no\nb\na\nr` so I think there should be an indicator of the presence of a newline character.

**Comment by laur89** [comment]
Fair enough. Perhaps add differently colored `\n` as a placeholder?

**Comment by junegunn** [comment]
> Perhaps add differently colored \n as a placeholder?

Yeah, that's what I have in mind. But it's not on my priority as it's unlikely that one will use fzf with multi-line entries. Anyway, I just released a new version of fzf, with `--read0` and `--print0`.

**Comment by laur89** [comment]
> just released a new version of fzf, with --read0 and --print0

Boom. Seriously, fzf is the next best thing since sliced internet.
