### ISSUE TITLE
incomplete ansi color support

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#674]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

$ ansi_colors
$ ansi_colors | fzf --ansi

only some of the ansi code are rendered properly

~~~~
function ansi_colors()
{
for clbg in 040 100 ; do
        #Foreground
        for clfg in {30..37} {90..97} 39 ; do
                #Formatting
                for attr in 0 1 2 4 5 7 ; do
                        #Print the result
                        echo -en "\e[${attr};${clbg};${clfg}m ^[${attr};${clbg};${clfg}m \e[0m"
                done
                echo #Newline
        done
done
}

**Comment by DanielFGray** [comment]
This seems like a terminal issue to me, using `urxvt` this works just fine for me.

**Comment by junegunn** [comment]
Thanks for the script. It's a known issue that fzf does not support all ANSI attributes. I'll see what I can do when I get some time. Please note that some attributes cannot be displayed correctly due to the limitation of ncurses, for example, italics. The recent version of ncurses seems to support it, but upgrading ncurses dependency may have compatibility issues on older linux distros. I'll also have to look into that.

**Comment by nkh** [comment]
Thank you for your quick answer. I have no real problems with this, it's just what I used to test it when I saw the functionality.

Nifty little app, using it more and more, Thank you.
