### ISSUE TITLE
leave part of current display visible when searching

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#686]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

When a margin is given as a parameter, do not erase the current background completely, instead allow the user to give a border width which should be erased (some color option maybe?)

In some situations I like to give a border to the fzf command, but it erases the background completely, I find it a bit much more ergonomic to keep the current display.

**Comment by junegunn** [comment]
Unfortunately this is not possible since fzf is an ncurses application. Some users even suggested creating a stripped-down version that does not depend on ncurses sacrificing fancy features like preview, margin, mouse, execute, etc that are non-trivial to implement without ncurses. But it's not my priority as I'm always on tmux and I'm really happy with fzf-tmux script for its versatility. e.g. `fzf-tmux -l30`, `fzf-tmux -u40%`.

[![](http://junegunn.kr/images/fzf-git-gh.png)](http://junegunn.kr/2016/07/fzf-git/)

**Comment by nkh** [comment]
What about taking a screen shot of the current window, drawing it in the
ncurses application, drawing over it?

That should work in tmux too.

**Comment by junegunn** [comment]
I don't think it's possible.

**Comment by nkh** [comment]
taking a text screenshot is possible in screen (built in) and in tmux (via plugin), I wrote a text screencast tool, I'll look in it.

Of course this complexity should no go into fzf but if it would take a file containing the screenshot and display it as background, that would go a long way.
