### ISSUE TITLE
Use environment variable in fzf#run

### ISSUE THREAD

**Issue by john-kurkowski** [junegunn/fzf#697]
- Category
  - [x] fzf binary
  - [x] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [x] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [ ] bash
  - [x] zsh
  - [ ] fish

Similar request to #481, which permitted the use of `$SHELL` instead of `sh`. However, commands that go through `fzf#run` are still [hardcoded to use `sh`](https://github.com/junegunn/fzf/blob/01b88539ba912da4f49cfba48e2a736c04ec6006/plugin/fzf.vim#L214). Can that function use `$SHELL` instead? To pick up environment variables, aliases, etc.

I encountered this trying to use junegunn/fzf.vim#36. Its `fzf#vim#grep` runs its grep command via `fzf#run`.

**Comment by junegunn** [comment]
We had issues using `system()` function with fish or tcsh and that's why we set `&shell` to `sh`. See:

- https://github.com/junegunn/fzf/issues/204
- https://github.com/junegunn/vim-plug/issues/159

Looks like fish no longer has the issue, but I'm still not sure if it's safe to remove the hard-coded `sh` (e.g. tcsh). Until we can be sure that we no longer need it, you can pass something like `zsh -c 'your-command'` as a workaround.
