### ISSUE TITLE
Is the search algo working right?

### ISSUE THREAD

**Issue by chrisamow** [junegunn/fzf#727]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [X] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Doing a ctrl-r history search
![screen](http://i.imgur.com/KiYehtW.png) 

Is it reasonable to find that git command on 10400 instead of the sort on 10392 ?
Just checking, I'll close it out if that is obvious to you, I don't understand the algo well enough.

Thanks!

**Comment by mjwestcott** [comment]
I believe your outcome is expected because the history search by default orders the lines by the number on the left, i.e. how recent the commands were executed.

You can sort the results by pressing `ctrl-r` a second time, or [see here](https://github.com/junegunn/fzf/issues/526) for modifying the default behaviour.

**Comment by chrisamow** [comment]
understood - thank you sir

**Comment by junegunn** [comment]
You might want to take a look at https://github.com/junegunn/fzf/wiki/Configuring-shell-key-bindings
