### ISSUE TITLE
Show recorded times on righthand side

### ISSUE THREAD

**Issue by rojaro** [junegunn/fzf#73]
When using i.e. HISTTIMEFORMAT the timestamps are recorded for every command. It would be really nice if there was an option to display them on the right hand side.

**Comment by waldauf** [comment]
Hello,
how can I display timestamp in history in ZSH, please?

**Comment by eyalev** [comment]
Is there an updated method to show timestamps in bash?

Updating `HISTTIMEFORMAT` in:

https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash#L51

doesn't seem to make an effect.

**Comment by MartenBE** [comment]
Caould this be re-opened? I am also looking for a solution to this. `FZF_CTRL_R_OPTS="--with-nth .."` doesn't work, probably because the `--with-nth 2..,..` is alread hardcoded before `FZF_CTRL_R_OPTS` at https://github.com/junegunn/fzf/blob/27dab2422e5faa6149b302d941280fcb8f9fe74c/shell/key-bindings.bash#L102
