### ISSUE TITLE
fzf.vim doesn't work on windows

### ISSUE THREAD

**Issue by prabirshrestha** [junegunn/fzf#750]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [X] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

fzf binary does work on windows but seems like fzf.vim doesn't work at all.

Managed to grab a screenshot when running `:Files` and seems like it is trying to execute `sh` instead of `cmd`.

![image](https://cloud.githubusercontent.com/assets/287744/20726431/687f5a4a-b62a-11e6-80e3-e05e85a2e167.png)

**Comment by junegunn** [comment]
Thanks for letting me know. Would you be interested in fixing this? I personally don't use Windows so I can't find enough time to look into the issues on the platform.

**Comment by prabirshrestha** [comment]
I could give it a shot in few days but I'm definitely not a viml expert.

**Comment by junegunn** [comment]
Check out #785 and #787.

**Comment by prabirshrestha** [comment]
`:Files` seems to work in both gvim and terminal vim on windows. `:Colors` and `:Filetypes` seem to work on in terminal vim and not in gvim.

Terminal vim shows fzf inline, Would it be possible to do the same for gvim too?

**Comment by junegunn** [comment]
> :Colors and :Filetypes seem to work on in terminal vim and not in gvim.

Yeah, I don't think most commands in fzf.vim except for the basic Files/FZF should work on Windows. And since I don't use Windows, we need someone else dedicated to work on Windows compatibility to push things forward.

> Terminal vim shows fzf inline, Would it be possible to do the same for gvim too?

Don't think it's possible on gvim, since fzf is a command-line program that runs in a terminal emulator. A GUI version of Neovim can do it using its embedded terminal emulator, but I'm not sure about its Windows support.

**Comment by janlazo** [comment]
Would removing the double quotes on the s:fzf_exec() fix the issue for `:Colors` and `:Filetypes`?
It may interfere with cmd.exe because of escaping issues.

Both commands work for me regardless of the double quotes but I'm using Vim 8.0.69 on Windows.
I tested on the latest commits for fzf and fzf.vim

Can you post the finalized command passed to the shell (cmd.exe) when running any of the commands from fzf.vim?

**Comment by janlazo** [comment]
>  A GUI version of Neovim can do it using its embedded terminal emulator, but I'm not sure about its Windows support.
:terminal is not supported yet in NyaoVim and Neovim-qt and `!fzf` doesn't start a new terminal.
`!start fzf` works though but passing the output to temporary file is another issue.

**Comment by prabirshrestha** [comment]
I got `:Colors` and `:Filetypes` working in windows. Sent the PR https://github.com/junegunn/fzf/pull/836

**Comment by SalahuddinAsh** [comment]
I'm working on Windows. all fzf commands run in Vim except for :Files. It shows 0/0!
Any suggestions how to get it to work?

**Comment by janlazo** [comment]
@SalahuddinAsh Can you open a new ticket at https://github.com/jungunn/fzf.vim? `:Files` should work if `:FZF` works.

**Comment by SalahuddinAsh** [comment]
`:FZF` doesn't work too.
