### ISSUE TITLE
Tiebreak option to prefer shorter filepath

### ISSUE THREAD

**Issue by myitcv** [junegunn/fzf#804]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Related to #802, it would be useful to have a tiebreak option that prefers a shorter filepath (i.e. the match with the least number of path separators). I can of course do things like:

```
git ls-files | awk '{print gsub(/\//,"/"), $0}' | sort -s -n -k 1,1 | cut -d\  -f2-
```

but will need to do this for every source (I'm using Neovim).

Thoughts?

**Comment by junegunn** [comment]
Thanks for the suggestion, but for now, I don't want to make the search/sort depend on the context to keep things simple. And I've had mixed feelings about `--tiebreak` option in general since 0.15.0 where we introduced sophisticated matching/sorting algorithm, which made `--tiebreak` much less important. I may retire the option in the future to make fzf simpler.

**Comment by myitcv** [comment]
Understood and thanks for the response; I have a work-around (as shown above) for now in any case.
