### ISSUE TITLE
Make --help more complete

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#822]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
- Version
   - [x] 0.16.2

Hey! :smile:

Just an uninteresting issue: I have [noticed](https://gist.github.com/D630/6f95439237e9000480ce286d8c1d47f4#command-line-options), that the following options are documented in the man page, but not listed via `--help`:

```
black
print0
read0
```

**Comment by junegunn** [comment]
Hi, thanks for the great summary.

- `--black` was added to workaround [the display issue in msys2](https://github.com/junegunn/fzf/issues/18#issuecomment-36785131) before fzf was rewritten in Go. Since the current version of fzf does not run in msys2 or cygwin, and moreover we now have a more flexible way to set the background color (`--color bg:0`), the option is no longer needed. It is still there not to break backward compatibility, but we'll eventually remove it in the end.
- Another option we may deprecate in the future is `--toggle-sort`, in favor of `--bind KEY:toggle-sort`.
- `--print0` and `--read0` are excluded in the `--help` on purpose, because I'm not sure about the benefits. You can find the reasoning behind the decision in https://github.com/junegunn/fzf/issues/660

**Comment by junegunn** [comment]
Let me add `--print0` and `--read0` to `--help`.
