### ISSUE TITLE
some questions, suggestions, maybe bugs.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [junegunn/fzf#856]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

1. I find in your gif at homepage , your fzf window is at the bottom of the screen, but when i set height=40%, my fzf window is just under cursor line, in the middle of the screen. how to make it like your gif?

2. I think only set FZF_DEFAULT_OPTS is enough, both FZF_CTRL_T_OPTS and FZF_CTRL_R_OPTS should use it by default, unless I set them explicitly. BTW, maybe a bug, my FZF_CTRL_T_OPTS is the same as FZF_DEFAULT_OPTS, but the input line of ctrl-t  is at the top but I do not set --reverse.

3. The default prompt and pointer icon is '>', it's not nice. i have already reset the prompt to '▸' but there is no --pointer option to reset it. Please think about to add --pointer in fzf and fzf.vim. Oh, i can not understand the fzf.vim status line config example int fzf.vim homepage.

4. Neovim has a buildin terminal emulator, so a neovim GUI app, for instance, neovim-dot-app works with fzf.vim very well with out any terminal support. I hope users of fzf know it.  When i launch the fzf in vim, the only way to quit fzf is press :q if i do not select any line to open. Is there a way to press only one key to quit fzf window in vim, like press esc in terminal?

5. to be confirm, fzf use unix find by default, and you recommend to use ag, so fzf will respect the .agignore file of ag ? Is this the only way to config fzf ignore patterns?

**Comment by junegunn** [comment]
1. It's using `fzf-tmux` script. It was primarily used before we added `--height` option.
2. FZF_DEFAULT_OPTS always applies. FZF_CTRL_{T,R}_OPTS allow you to further customize the options. Since the addition of `--height`, we set `--reverse` by default to CTRL-T and ALT-C, as top-down layout looks better in non-full screen mode. You can add `--no-reverse` to FZF_DEFAULT_OPTS to override it.
3. I'll think about it. But I'm basically reluctant to add more options for tweaking minor UI elements at the moment to avoid proliferation of non-essential options that will inevitably make fzf more complex in the long run. You can find my previous comment on that matter [here](https://github.com/junegunn/fzf/issues/692#issuecomment-251436739). fzf is an open-source project, you can always change things and build it yourself.
4. You mean in Neovim? ESC works as expected. You probably have mapped ESC to something using `tnoremap`. Or you can simply hit CTRL-C instead.
5. No. ag, rg, ... whatever works best for you.

**Comment by FinallyFinancialFreedom** [comment]
thank you for reply, and your amazing fzf and fzf.vim, and i just notice that the vim-plug is created by you too after i used it for months. How great you are in vim world!
You are right to focus your precious time on the essential functions. Although I pay more attention on UI, I don't like too many customise options. Anyway a default beautiful UI is attractive. I'm sure spacemacs gains a lot of users through it's nice UI.
