### ISSUE TITLE
Add zsh source to .zshrc.local instead of .zshrc if it exists

### ISSUE THREAD

**Issue by nh2** [junegunn/fzf#859]
- Category
    - [x] Etc.
- OS
    - [x] Linux
- Shell
    - [x] zsh

It is popular for zsh configs (e.g. by the wildly used https://grml.org/zsh/) to have an immutable `~/.zshrc` and a `~/.zshrc.local` that contains local modifications over what is provided e.g. by grml's config.

By default fzf's setup adds `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh` to `.zshrc`, I'm suggesting that we might want to add it to `.zshrc.local` if it exists.

**Comment by junegunn** [comment]
Thanks for the suggestion. While I like the idea, I'm not sure if we should do so. Because the existence of the file does not guarantee that it's actually loaded by zshrc. fzf has been around for a few years by now, so I'm also a bit concerned about the confusion the sudden change might bring.

The install script asks if it should update shell configuration files, and it provides `--no-update-rc` option so one can write `./install --all --no-update-rc`. So the users who want the line in different files can put it manually in whichever file they prefer, and I think it suffices for now.

**Comment by tony** [comment]
I had an issue where `.zshrc` kept having `` added every update

Before:

```vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
```

After:

```vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all --no-update-rc' }
Plug 'junegunn/fzf.vim'
```

Shell: [.zshrc](https://github.com/tony/.dot-config/blob/b33ece0/.zshrc#L143) sourcing [env.d/fzf.zsh](https://github.com/tony/.dot-config/blob/1485be5/.shell/env.d/fzf.sh)
