### ISSUE TITLE
Query option not working in completion

### ISSUE THREAD

**Issue by quicknir** [junegunn/fzf#863]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm having trouble using the query option as part of my default options. I have

```
export FZF_DEFAULT_OPTS="-e --query='!^. '"
```

When I use `^T`, this works fine. However, it does not work from fzf completion; that is the query group is not already present when completion begins. I've tried various things with quoting, `FZF_COMPLETION_OPTS`, etc. Interestingly the `-e` option does seem to be working.

**Comment by junegunn** [comment]
Because fuzzy completion overrides `--query` option to start fzf with an initial query. e.g. `vim /bin/sh**<tab>` will start fzf in `/bin` directory with the initial query `sh`. So unfortunately, you can't use it with your `--query`.

Fundamentally, I don't think it's a good idea to put `--query` in your `FZF_DEFAULT_OPTS` since fzf is not just for filtering files, but for any list of things. The static query doesn't makes sense in different contexts.

**Comment by quicknir** [comment]
Yes, I thought some more about this after. The problem I was trying to solve was to have a convenient way to have hidden excluded by default, yet easily reachable. Filtering out hidden files in the initial command makes it impossible to see them later so it's not a solution. I still think that starting with a query group to exclude hidden files is one of the better solutions, at least without requiring changes on your end (or at least, so I thought). Maybe there could be an env variable that concatenates onto query, for path searches from auto completion? This doesn't seem so unreasonable, imho, anyone who ever has any reason to make query a default option for C-t searches, will be surprised that when paths are searched due to completion, things are not consistent.
