### ISSUE TITLE
Feature request. Serialize, deserialize fzf state with properties file

### ISSUE THREAD

**Issue by ezh** [junegunn/fzf#883]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Add argument to select the specific line if there is any. For example --line="previous_selection"

Use case: loop in script with `fzf`:
- start `fzf`, select or move cursor to something, exit from `fzf`
- process selected entry
- start `fzf` with the same startup options

Right now cursor at the first line.
Expected that cursor will be at last selected position.
This will be useful in huge amount of fzf scripts with **while** or **for** blocks
It will allow to process flawlessly list of fzf entries one by one.

**Comment by junegunn** [comment]
Hi, this was discussed in the past but I can't find the specific issue. Actually desigining the feature is not so trivial.
- fzf run asynchronously, i.e. it starts the finder before input stream is complete. We can't tell when the designated line will come, or will ever appear. To avoid confusion fzf will have to block until the line appears or the stream is complete.
- If the line doesn't appear on page 1, fzf will have to start with non-zero scroll offset. It can be really confusing to the use as we don't have scroll indicator.
- The idea expands. Should we also allow multiple pre-selections for `--multi` option? Should we allow regular expressions for pre-selecting? Yes, a few users may find these features useful, but adding more option will make fzf more complex and make it harder for me to maintain. I'd really like to avoid adding new features.

Having said that, I believe there are a couple of different approaches you might want to consider instead
- Using `execute` or `execute-silent` bindings will solve your problem nicely if you don't have to refresh the list every time. fzf uses `$SHELL` to start the command specified in `execute` body, so you can export shell functions and use it from there.
- If you do have to refresh the list, then the script starting fzf can reorder the input so that the previous selection comes first.

**Comment by ezh** [comment]
This is my use case https://github.com/ezh/fzf-ls

I am sure that there are a lot of complex cases that hard to implement.

It is possible to make it a little, step by step.

For example as first step, select if possible after timeout only if text is already visible.

Since there will be improvements in future, the parameter may be complex:
`--line="timeout_ms,selection text"`

If you decide that this is out of scope, please close this thread.

**Comment by ezh** [comment]
I think that my feature request is incorrect.
The proposal is
* to save fzf state to properties file at exit (option --save state.conf)
  as the first step content with property of selected names
* to load fzf state after a while from properties file (option --load timeout_ms,state.conf)
  the state is restored as much as possible

This allows to serialize more parameters in the future.
This allows to prepare complex state by external tool and initialize fzf with precise control.

**Comment by junegunn** [comment]
Thanks for the clarification. The idea is intriguing, but it will certainly bring up many subtle design choices we'll have to make along the way and it seems inevitable that we'll end up with a pack of new options only for very advanced, exceptional use cases. The question is if it's worth it.

But after looking at your project, I think what you really need is `execute` action I suggested above. Please experiment with it first and let me know what you can't implement with it. You also might want to consider using `--no-clear` option to avoid flickering of the screen between fzf sessions (just don't forget to `tput rmcup` when you're done).

**Comment by ezh** [comment]
Thank you for suggestion and hints. Anyway serialization of state is useful for some cases but I understand risks of API overload. This only your decision.

Quality is much better than quantity.
