### ISSUE TITLE
git checkout ** completion

### ISSUE THREAD

**Issue by codeinabox** [junegunn/fzf#913]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Is there a way to configure fuzzy completion for `git checkout **`. For now I am just using the alias `git checkout $(git branch | fzf)`

**Comment by junegunn** [comment]
This repository only implements generic path/directory completion. If you want to implement specialized completion for git and its subcommands, refer to
https://github.com/junegunn/fzf/wiki/Examples-(completion).

But instead of using `**` completion, I define and use a set of key bindings for git objects.

- https://junegunn.kr/2016/07/fzf-git/
- https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
