### ISSUE TITLE
Alt-c binding does not fire precmd_functions in zsh, so things like direnv do not work

### ISSUE THREAD

**Issue by aaronjensen** [junegunn/fzf#915]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

If I use Alt-c to change directories, the directory change happens, but precmd_functions (like the one installed by direnv) do not fire. This means I need to hit return one more time to get a new prompt and trigger direnv.

I originally reported this here: https://github.com/urbainvaes/fzf-marks/issues/6 but it is an issue here as well. I don't know enough about zsh/zle/etc to fix it myself, so I'm hoping someone here has an idea. Thanks!

**Comment by DanielFGray** [comment]
this seems odd to me, since Alt-c just calls `cd` directly: https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh#L49

**Comment by aaronjensen** [comment]
It probably has to do with the fact that cd is called within a widget, so it does not count as a command, so precmd_functions are not called. (guessing here, I know little about this)

**Comment by spatz** [comment]
I think that instead of calling `zle reset-prompt` after running `cd` you should call `zle redraw-prompt`.

**Comment by aaronjensen** [comment]
@spatz Just gave that a shot, but: `No such widget `redraw-prompt'` am I missing something?

**Comment by spatz** [comment]
You are correct, I was a silly. I forgot long ago I had defined a `redraw-prompt` widget:
```sh
redraw-prompt() {
    local precmd
    for precmd in $precmd_functions; do
        $precmd
    done
    zle reset-prompt
}
zle -N redraw-prompt
```
Maybe something like this should be used in `fzf`.

**Comment by aaronjensen** [comment]
Very interesting, I was wondering if there was a way to invoke the precmd hook. This makes sense. Unfortunately, for me it breaks zsh autosuggest:

```
_zsh_autosuggest_async_pty_create:zpty:12: pty command name already used: zsh_autosuggest_pty
_zsh_autosuggest_async_pty_create:zle:22: Bad file descriptor number for -F: _zsh_autosuggest_async_response
```

**Comment by geoelectric** [comment]
One option comes with a small (but IMO beneficial) behavior change. 

This code actually captures the original line buffer, replaces the line buffer with the cd and executes that, then restores the original buffer on the next prompt. This not only updates the prompt, it leaves the cd itself in your scrollback and history since it's automating you typing the cd in instead of doing it in the background.

I like it because it's much more explicit in behavior while still preserving the original flow. I don't like that the original directory change was completely invisible.

```
# ALT-C - cd into the selected directory
fzf-cd-widget() {
  local cmd="${FZF_ALT_C_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type d -print 2> /dev/null | cut -b3-"}"
  setopt localoptions pipefail 2> /dev/null
  local dir="$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" $(__fzfcmd) +m)"
  if [[ -z "$dir" ]]; then
    zle redisplay
    return 0
  fi
  zle kill-whole-line
  zle -U "$CUTBUFFER"
  BUFFER="cd \"$dir\""
  zle accept-line
  local ret=$?
  zle reset-prompt
  typeset -f zle-line-init >/dev/null && zle zle-line-init
  return $ret
}
```

The new parts are the `zle kill-whole-line` to move the line into `$CUTBUFFER`, appending to zle's "after the widget executes" command line with `-U`, stuffing the `cd` into the buffer, and `accept-line`ing it. 

I didn't change anything else, but I'm not sure if the reset-prompt would be strictly necessary (my experimental version didn't need it, since you're automating the execution of the cd so the precmd fires normally) and have no idea at all what the typeset line is actually doing.

I did try it with a multiline prompt and it seemed ok, as well as ctrl-c'ing the alt-C find. I don't know enough about autosuggest to try it, but it should work since this automates instead of hooks.

FWIW, I tried a number of other methods, and I found no way to make it work completely inline like the current behavior and immediately show the cd in the prompt.

I think that's because the precmd thing is a red herring. The issue is more that direct execution doesn't cause another prompt to be generated at all, and the widget is otherwise just keeping the same line in place. You have to execute a line before things update. You can, for example, do the cd in the background like we do now and then accept-line an empty line after to create another prompt, but it seemed cleaner to just make the cd show explicitly instead.

Let me know what y'all think. I don't want to generate a blind PR because of the behavior change but am otherwise happy to do so.

**Comment by geoelectric** [comment]
@aaronjensen : I just tried the redraw-prompt (pasted verbatim just above fzf-cd-widget, and replacing reset-prompt) and didn't run into the autosuggestions incompatibility.

Can you give more detail on how you set that experiment up, and maybe what your precmd_functions looks like? I'd like to dig in further, as I don't see a path other than either running the precmds manually or changing flow so that the prompt is no longer changed in place. If I can reproduce your failure case it might help give some ideas.

**Comment by aaronjensen** [comment]
@geoelectric it actually works now for me w/o those warnings. It could have been an older version of zsh autosuggest or it could have been conflicting w/ some of the stuff I was trying out w/ zsh autosuggest at the time, I'm not sure.

So, this appears to work. The only thing that it does that's not perfect is that it overwrites one of the lines from direnv's output, but that's minor.

**Comment by geoelectric** [comment]
@spatz, if the conflict isn't reproduceable now I think your solution might be the best strategy.

**Comment by bew** [comment]
I have the same issue, but about `chpwd` (e.g: for `cdr`) hooks not triggering.
