### ISSUE TITLE
length tiebreak not working as expected

### ISSUE THREAD

**Issue by rcorre** [junegunn/fzf#932]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

```
[rodencor@heredesk dir]$ tree
.
├── lib
│   └── MyWebSocket.js
└── node_modules
    └── WebSocket.js

2 directories, 2 files
[rodencor@heredesk dir]$ fzf --tiebreak length -f web
node_modules/WebSocket.js
lib/MyWebSocket.js
[rodencor@heredesk dir]$
```

Why is `node_modules/WebSocket.js` first when `lib/MyWebSocket.js` is shorter?

I usually want to search my own code, which will often have a shorter path. When I want to search my dependencies, I will type `node` (or `vendor`, `.tox`, whatever) and then the rest of my search. However, since `--tiebreak length` doesn't seem to work as documented, I often unintentionally end up with dependency code at the top of the list with my own code somewhere in the middle.

P.S. `fzf` is great overall. Keep up the good work!

**Comment by junegunn** [comment]
> Why is node_modules/WebSocket.js first when lib/MyWebSocket.js is shorter?

The former has a higher score than the latter, because `Web` in the former is *the head of a camel*, and that in the latter is *a hump of a camel*. So they are not tied and `--tiebreak` has no effect here. Actually since [the revision of the scoring algorithm](https://github.com/junegunn/fzf/issues/638), ties are much rarer and `--tiebreak` usually has little impact on the result.

`node_modules` is usually ignored by git, and you might want to [set up the default command to reflect that](https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore). If you do need to find the entries that are ignored, you can set up multiple functions or aliases with different sources (e.g. `alias gfzf='git ls-files | fzf'`). Another option would be to type in `!node web`.

**Comment by rcorre** [comment]
makes sense. I don't want to ignore it though, and I'd like to avoid having multiple separate commands (and corresponding vim keybindings). One of the nice bits about fzf is it is fast and (usually) smart enough to get what you want without ignoring things. Is there any way I could keep vendor directories in the output but reduce their score?

**Comment by junegunn** [comment]
No, because fzf is just a text filter and is context-free. Now knowing that fzf gives bonus scores to matches at word boundaries, you should be able to come up with better queries that would produce better results in most cases. For example, in the above case, try `mweb` or `mws` instead of just `web`.
