### ISSUE TITLE
option to get input query if it returns zero match for Ctrl-R (fuzzy history search)

### ISSUE THREAD

**Issue by thisguychris** [junegunn/fzf#993]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Scenario: If I try to type a new command from Ctrl-R and get zero results.  Doing escape or enter would delete the input query.

I was looking at issue #389 and tried adding --print-query to `FZF_DEFAULT_OPTS` and it seems it just breaks the whole fuzzy search in Ctrl-R.

**Comment by junegunn** [comment]
It is not clear if the suggested behavior is always desirable. Because you don't type in the exact command as the search query. Say we want to find `git clone` commands, but not the ones from `bitbucket.org`, we can type in `gclon !bbo`. This is a valid fzf query, but we definitely don't want to paste it on our shell prompt.

But if you're willing to customize your version of the binding. Yes, `--print-query` is what you should check out.

**Comment by NightMachinary** [comment]
@junegunn `--print-query` returns non-zero when a non-existent query is accepted via `<enter>`, and there is no way to distinguish that from a cancel triggered by, e.g., `ESC`.

`--expect` makes the UI suck needlessly.

I propose having a `--add-query-to-candidates` that adds the typed query to one of the candidates for selection, perhaps with the special provision that when this option is enabled, the cursor will by default be on the second input candidate instead of the first (which will always be the typed query.).

If this option is too much, please at least make `fzf` return 0 when `--print-query` is enabled and the user actively accepts a nonexistent query like this:
![image](https://user-images.githubusercontent.com/36224762/82832785-6189dd80-9ed1-11ea-8813-e9a6416d892d.png)

**Comment by junegunn** [comment]
Excerpt from man page:

```
EXIT STATUS
       0      Normal exit
       1      No match
       2      Error
       130    Interrupted with CTRL-C or ESC
```

**Comment by NightMachinary** [comment]
@junegunn Right. Sorry. :-)

**Comment by KhaimovMR** [comment]
@NightMachinary seems like you have the same struggle that I'm facing right now. What was your solution in the end?

**Comment by KhaimovMR** [comment]
I mean that your suggestion to add option `--add-query-to-candidates` will significantly ease the usage of fzf when you want it to return the file name that you've entered in case there were not matches.
I could suggest the same thing but from the other view point `--return-query-on-no-matches`.

When you're looking for the file and you find out that it doesn't exist still - it would be much more convenient to return the exact query you've entered to process it with like `mkdir -p %s` or `touch %s`.

At this time I've ended up using a wrapper around `fzf` that parses the results returned from it and in case of 130 error code it returns the printed query... - kind of a dirty solution.

**Comment by NightMachinary** [comment]
@KhaimovMR I don't remember exactly what I ended up doing, but I use a lot of wrapper code around my tools, including `fzf`. What matters is that the underlying toll exposes enough APIs that you can write the wrapper you need. It's not 'dirty' at all; The wrappers are robust.

There are some problems that cannot be solved easily via wrappers. For example, I have a wrapper script that adds most-recently-used candidates to the top of `fzf`'s results, but since `fzf` does not expose an API to weigh different candidates differently, this is a 'dirty' hack with limited capabilities.

**Comment by kaddkaka** [comment]
Did someone find a way to copy the query to the command line? Even if I can look at the return I wouldn't know how to copy the query prompt to the command line after exit.

It would be nice to be able to start history search with `ctrl-R` and then exit fzf with a keybinding separate from `enter` that selects the query instead of an item in the list and put that on the command line. I wouldn't know how to write a wrapper for this and I think having the functionality within fzf makes sense. Sometimes the fzf query might be a "garbage command" like `gclon !bbo` but other times I actually start to type out the real command from the beginning and realize after some last characters that what I'm looking for isn't there. In those cases there is still value in keeping my query even if there are a few unwanted or 0 matches.

**Comment by cristiansofronie** [comment]
This is my solution.

Put this  in a file somewhere in the fpath (like PATH but for functions, in my case i named it fzf-custom-history-widget):
```zsh
# Fuzzy search through history

fzf_keybindings=(
  ctrl-t:toggle-preview,
  ctrl-k:preview-up,
  ctrl-j:preview-down
)

preview_command='print {} | bat --style=plain --color=always -'

fzf_opt=(
  --query=$BUFFER
  --bind ${(j::)fzf_keybindings}
  --preview $preview_command
  --preview-window=hidden,down
  --ansi
  --layout=reverse
  --height=100%
  --print-query
  --expect=enter,esc
)

choice=( "${(f)$(fc -rl 1 | fzf $fzf_opt)}" )

if [[ $choice[2] == enter ]]; then
  zle vi-fetch-history -n $choice[3]
  return 0
elif [[ $choice[2] == esc ]]; then
  BUFFER=$choice[1]
  zle vi-end-of-line
  return 0
fi

return 1
```

And then add this to your zshrc:
```zsh
autoload fzf-custom-history-widget
zle -N fzf-custom-history-widget
bindkey "\er" fzf-custom-history-widget
bindkey -M vicmd "\er" fzf-custom-history-widget
```
Some things might need to be changed.
